// src/react/views/public/PublicEstimateView.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useLocation } from 'react-router-dom'
import api from '../../../services/api'
import Button from '../../components/ui/Button'
import Badge from '../../components/ui/Badge'
import Loading from '../../components/ui/Loading'
import { useToast } from '../../stores/toast'

const formatCurrency = (amount) => `$${Number(amount || 0).toFixed(2)}`

const statusLabels = {
  approved: 'Approved',
  rejected: 'Rejected',
  pending: 'Pending',
  sent: 'Sent',
  partial: 'Partially Approved',
  declined: 'Declined',
  expired: 'Expired',
}

const statusVariants = {
  approved: 'success',
  rejected: 'danger',
  pending: 'warning',
  sent: 'info',
  partial: 'warning',
  declined: 'danger',
  expired: 'danger',
}

function SignaturePad({ onChange }) {
  const canvasRef = useRef(null)
  const drawing = useRef(false)

  const resizeCanvas = useCallback(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const parent = canvas.parentElement
    if (!parent) return
    const ratio = window.devicePixelRatio || 1
    const width = parent.clientWidth
    const height = 180
    canvas.width = width * ratio
    canvas.height = height * ratio
    canvas.style.width = `${width}px`
    canvas.style.height = `${height}px`
    const ctx = canvas.getContext('2d')
    if (ctx) {
      ctx.scale(ratio, ratio)
      ctx.lineWidth = 2
      ctx.lineCap = 'round'
      ctx.strokeStyle = '#111827'
    }
  }, [])

  useEffect(() => {
    resizeCanvas()
    window.addEventListener('resize', resizeCanvas)
    return () => window.removeEventListener('resize', resizeCanvas)
  }, [resizeCanvas])

  const getPosition = (event) => {
    const canvas = canvasRef.current
    if (!canvas) return { x: 0, y: 0 }
    const rect = canvas.getBoundingClientRect()
    return {
      x: event.clientX - rect.left,
      y: event.clientY - rect.top,
    }
  }

  const handlePointerDown = (event) => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    drawing.current = true
    const { x, y } = getPosition(event)
    ctx.beginPath()
    ctx.moveTo(x, y)
  }

  const handlePointerMove = (event) => {
    if (!drawing.current) return
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    const { x, y } = getPosition(event)
    ctx.lineTo(x, y)
    ctx.stroke()
  }

  const handlePointerUp = () => {
    if (!drawing.current) return
    drawing.current = false
    const canvas = canvasRef.current
    if (!canvas) return
    onChange?.(canvas.toDataURL('image/png'))
  }

  const clear = () => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return
    ctx.clearRect(0, 0, canvas.width, canvas.height)
    onChange?.('')
  }

  return (
    <div className="space-y-3">
      <div className="rounded-lg border border-dashed border-gray-300 bg-white">
        <canvas
          ref={canvasRef}
          className="w-full touch-none"
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerLeave={handlePointerUp}
        />
      </div>
      <Button variant="ghost" size="sm" onClick={clear}>
        Clear Signature
      </Button>
    </div>
  )
}

export default function PublicEstimateView() {
  const location = useLocation()
  const { success, error } = useToast()
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState('')
  const [estimate, setEstimate] = useState(null)
  const [customer, setCustomer] = useState(null)
  const [vehicle, setVehicle] = useState(null)
  const [jobs, setJobs] = useState([])
  const [terms, setTerms] = useState('')
  const [hasSignature, setHasSignature] = useState(false)
  const [token, setToken] = useState('')
  const [shortCode, setShortCode] = useState('')
  const [signerName, setSignerName] = useState('')
  const [signerEmail, setSignerEmail] = useState('')
  const [signatureData, setSignatureData] = useState('')
  const [comment, setComment] = useState('')
  const [legalConsent, setLegalConsent] = useState(false)
  const [consentText, setConsentText] = useState('')
  const [rejectionReasons, setRejectionReasons] = useState([])
  const [jobNotes, setJobNotes] = useState({})
  const [jobRejectionReasons, setJobRejectionReasons] = useState({})
  const [submitting, setSubmitting] = useState(false)

  const query = useMemo(() => new URLSearchParams(location.search), [location.search])

  const loadEstimate = useCallback(async () => {
    setLoading(true)
    setLoadError('')
    try {
      const tokenParam = query.get('token') || ''
      const codeParam = query.get('code') || ''
      setToken(tokenParam)
      setShortCode(codeParam)

      if (!tokenParam && !codeParam) {
        setLoadError('Missing estimate link details. Please use the link provided in your notification.')
        return
      }

      const response = tokenParam
        ? await api.get('/public/estimate', { params: { token: tokenParam } })
        : await api.get(`/public/estimate/by-code/${codeParam}`)

      setEstimate(response.data.estimate)
      setCustomer(response.data.customer)
      setVehicle(response.data.vehicle)
      setJobs(response.data.jobs || [])
      setTerms(response.data.terms || '')
      setHasSignature(Boolean(response.data.has_signature))
      setConsentText(response.data.terms || '')
    } catch (loadFailure) {
      console.error('Failed to load estimate:', loadFailure)
      setLoadError(loadFailure.response?.data?.error || 'Failed to load estimate.')
    } finally {
      setLoading(false)
    }
  }, [query])

  const loadRejectionReasons = useCallback(async () => {
    try {
      const response = await api.get('/public/estimate/rejection-reasons')
      setRejectionReasons(response.data.reasons || [])
    } catch (err) {
      console.error('Failed to load rejection reasons:', err)
    }
  }, [])

  useEffect(() => {
    loadEstimate()
    loadRejectionReasons()
  }, [loadEstimate, loadRejectionReasons])

  const jobStatusSummary = useMemo(() => {
    const approved = jobs.filter((job) => job.customer_status === 'approved').length
    const rejected = jobs.filter((job) => job.customer_status === 'rejected').length
    const pending = jobs.length - approved - rejected
    return { approved, rejected, pending }
  }, [jobs])

  const allJobsResponded = useMemo(
    () => jobs.length > 0 && jobs.every((job) => job.customer_status === 'approved' || job.customer_status === 'rejected'),
    [jobs]
  )

  const updateJobStatus = (jobId, status) => {
    setJobs((prev) =>
      prev.map((job) => (job.id === jobId ? { ...job, customer_status: status } : job))
    )
  }

  const submitJobAction = async (jobId, status) => {
    const payload = {
      token,
      short_code: shortCode,
      job_id: jobId,
      signer_name: signerName || undefined,
      signer_email: signerEmail || undefined,
      comment: jobNotes[jobId] || undefined,
    }

    if (status === 'rejected') {
      payload.rejection_reason = jobRejectionReasons[jobId] || undefined
    }

    const endpoint = status === 'approved' ? '/public/estimate/approve-job' : '/public/estimate/reject-job'
    await api.post(endpoint, payload)
    updateJobStatus(jobId, status)
  }

  const handleApproveJob = async (jobId) => {
    try {
      await submitJobAction(jobId, 'approved')
      success('Job approved.')
    } catch (approveError) {
      console.error('Failed to approve job:', approveError)
      error(approveError.response?.data?.error || 'Failed to approve job.')
    }
  }

  const handleRejectJob = async (jobId) => {
    try {
      await submitJobAction(jobId, 'rejected')
      success('Job rejected.')
    } catch (rejectError) {
      console.error('Failed to reject job:', rejectError)
      error(rejectError.response?.data?.error || 'Failed to reject job.')
    }
  }

  const handleSignEstimate = async () => {
    if (!signerName.trim()) {
      error('Please enter your name to sign.')
      return
    }
    if (!signatureData) {
      error('Please provide your signature.')
      return
    }
    if (!legalConsent) {
      error('Please accept the consent terms to continue.')
      return
    }

    setSubmitting(true)
    try {
      const pendingJobs = jobs.filter((job) => job.customer_status !== 'approved')
      for (const job of pendingJobs) {
        await submitJobAction(job.id, 'approved')
      }

      await api.post('/public/estimate/signature', {
        token,
        short_code: shortCode,
        name: signerName,
        email: signerEmail || undefined,
        signature_data: signatureData,
        comment: comment || undefined,
        legal_consent: legalConsent,
        consent_text: consentText || undefined,
      })

      setHasSignature(true)
      success('Estimate approved and signed. Thank you!')
      loadEstimate()
    } catch (signatureError) {
      console.error('Failed to sign estimate:', signatureError)
      error(signatureError.response?.data?.error || 'Failed to sign estimate.')
    } finally {
      setSubmitting(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loading size="xl" text="Loading estimate..." />
      </div>
    )
  }

  if (loadError) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-16 text-center">
        <h2 className="text-2xl font-semibold text-gray-900">Unable to load estimate</h2>
        <p className="mt-3 text-gray-600">{loadError}</p>
      </div>
    )
  }

  if (!estimate) {
    return (
      <div className="mx-auto max-w-3xl px-4 py-16 text-center">
        <h2 className="text-2xl font-semibold text-gray-900">Estimate not found</h2>
        <p className="mt-3 text-gray-600">The estimate link might be expired or invalid.</p>
      </div>
    )
  }

  return (
    <div className="bg-gray-50 min-h-screen">
      <div className="mx-auto max-w-5xl px-4 py-10">
        <div className="bg-white shadow-sm rounded-2xl p-6 space-y-6">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Estimate #{estimate.number}</h1>
              <p className="mt-1 text-sm text-gray-500">Thank you for choosing our shop. Review and approve below.</p>
            </div>
            <Badge variant={statusVariants[estimate.status] || 'info'} size="lg">
              {statusLabels[estimate.status] || estimate.status}
            </Badge>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            <div className="rounded-xl border border-gray-200 p-4">
              <h2 className="text-sm font-semibold text-gray-700 uppercase">Customer</h2>
              <p className="mt-2 text-lg font-medium text-gray-900">{customer?.name || 'Customer'}</p>
              <p className="text-sm text-gray-500">{customer?.email || 'Email not available'}</p>
              <p className="text-sm text-gray-500">{customer?.phone || 'Phone not available'}</p>
            </div>
            <div className="rounded-xl border border-gray-200 p-4">
              <h2 className="text-sm font-semibold text-gray-700 uppercase">Vehicle</h2>
              <p className="mt-2 text-lg font-medium text-gray-900">
                {[vehicle?.year, vehicle?.make, vehicle?.model].filter(Boolean).join(' ') || 'Vehicle'}
              </p>
              <p className="text-sm text-gray-500">VIN: {vehicle?.vin || 'N/A'}</p>
              <p className="text-sm text-gray-500">Plate: {vehicle?.license_plate || 'N/A'}</p>
            </div>
          </div>

          <div className="rounded-xl border border-gray-200 p-4">
            <h2 className="text-lg font-semibold text-gray-900">Job Summary</h2>
            <p className="mt-1 text-sm text-gray-500">
              {jobStatusSummary.approved} approved · {jobStatusSummary.rejected} rejected · {jobStatusSummary.pending} pending
            </p>
          </div>

          <div className="space-y-6">
            {jobs.map((job) => (
              <div key={job.id} className="rounded-xl border border-gray-200 p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">{job.title || `Job #${job.id}`}</h3>
                    {job.description ? <p className="mt-1 text-sm text-gray-500">{job.description}</p> : null}
                  </div>
                  <Badge variant={statusVariants[job.customer_status] || 'warning'}>
                    {statusLabels[job.customer_status] || 'Pending'}
                  </Badge>
                </div>

                {job.items?.length ? (
                  <div className="mt-4 overflow-x-auto">
                    <table className="min-w-full text-sm">
                      <thead className="text-gray-500">
                        <tr>
                          <th className="py-2 text-left font-medium">Item</th>
                          <th className="py-2 text-right font-medium">Qty</th>
                          <th className="py-2 text-right font-medium">Price</th>
                          <th className="py-2 text-right font-medium">Total</th>
                        </tr>
                      </thead>
                      <tbody className="text-gray-700">
                        {job.items.map((item) => (
                          <tr key={item.id || `${job.id}-${item.name}`}>
                            <td className="py-2">{item.description || item.name || 'Line item'}</td>
                            <td className="py-2 text-right">{item.quantity || 1}</td>
                            <td className="py-2 text-right">{formatCurrency(item.unit_price)}</td>
                            <td className="py-2 text-right">
                              {formatCurrency((Number(item.quantity) || 1) * (Number(item.unit_price) || 0))}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ) : null}

                <div className="mt-4 grid gap-3 md:grid-cols-2">
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Comment (optional)</label>
                    <textarea
                      value={jobNotes[job.id] || ''}
                      onChange={(event) =>
                        setJobNotes((prev) => ({ ...prev, [job.id]: event.target.value }))
                      }
                      rows={2}
                      className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                      placeholder="Add a note about this job"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700">Rejection reason</label>
                    <select
                      value={jobRejectionReasons[job.id] || ''}
                      onChange={(event) =>
                        setJobRejectionReasons((prev) => ({ ...prev, [job.id]: event.target.value }))
                      }
                      className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                    >
                      <option value="">Select a reason</option>
                      {rejectionReasons.map((reason) => (
                        <option key={reason} value={reason}>
                          {reason}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="mt-4 flex flex-wrap gap-3">
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={() => handleApproveJob(job.id)}
                    disabled={job.customer_status === 'approved'}
                  >
                    Approve Job
                  </Button>
                  <Button
                    variant="danger"
                    size="sm"
                    onClick={() => handleRejectJob(job.id)}
                    disabled={job.customer_status === 'rejected'}
                  >
                    Reject Job
                  </Button>
                </div>
              </div>
            ))}
          </div>

          <div className="rounded-xl border border-gray-200 p-5">
            <h2 className="text-lg font-semibold text-gray-900">Estimate Totals</h2>
            <div className="mt-4 grid gap-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-600">Subtotal</span>
                <span className="font-medium text-gray-900">{formatCurrency(estimate.subtotal)}</span>
              </div>
              {Number(estimate.call_out_fee) > 0 ? (
                <div className="flex justify-between">
                  <span className="text-gray-600">Call out fee</span>
                  <span className="font-medium text-gray-900">{formatCurrency(estimate.call_out_fee)}</span>
                </div>
              ) : null}
              {Number(estimate.mileage_total) > 0 ? (
                <div className="flex justify-between">
                  <span className="text-gray-600">Mileage</span>
                  <span className="font-medium text-gray-900">{formatCurrency(estimate.mileage_total)}</span>
                </div>
              ) : null}
              {Number(estimate.discounts) > 0 ? (
                <div className="flex justify-between">
                  <span className="text-gray-600">Discounts</span>
                  <span className="font-medium text-gray-900">-{formatCurrency(estimate.discounts)}</span>
                </div>
              ) : null}
              <div className="flex justify-between">
                <span className="text-gray-600">Tax</span>
                <span className="font-medium text-gray-900">{formatCurrency(estimate.tax)}</span>
              </div>
              <div className="flex justify-between border-t border-gray-200 pt-2 text-base font-semibold">
                <span>Total</span>
                <span>{formatCurrency(estimate.grand_total)}</span>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-gray-200 p-6 space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-gray-900">Digital Signature</h2>
              {hasSignature ? <Badge variant="success">Signed</Badge> : null}
            </div>
            <p className="text-sm text-gray-500">
              Please sign to approve the estimate and authorize work. Your signature records your approval.
            </p>

            <div className="grid gap-4 md:grid-cols-2">
              <div>
                <label className="block text-sm font-medium text-gray-700">Your name</label>
                <input
                  type="text"
                  value={signerName}
                  onChange={(event) => setSignerName(event.target.value)}
                  className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                  placeholder="Enter full name"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Email (optional)</label>
                <input
                  type="email"
                  value={signerEmail}
                  onChange={(event) => setSignerEmail(event.target.value)}
                  className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                  placeholder="name@email.com"
                />
              </div>
            </div>

            <SignaturePad onChange={setSignatureData} />

            <div>
              <label className="block text-sm font-medium text-gray-700">Comment (optional)</label>
              <textarea
                value={comment}
                onChange={(event) => setComment(event.target.value)}
                rows={3}
                className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                placeholder="Add any notes about this approval"
              />
            </div>

            {terms ? (
              <div className="rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm text-gray-600">
                <div className="mb-2 font-medium text-gray-700">Estimate Terms</div>
                <div
                  className="prose max-w-none text-sm text-gray-600"
                  dangerouslySetInnerHTML={{ __html: terms }}
                />
              </div>
            ) : null}

            <label className="flex items-start gap-2 text-sm text-gray-700">
              <input
                type="checkbox"
                className="mt-1 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                checked={legalConsent}
                onChange={(event) => setLegalConsent(event.target.checked)}
              />
              <span>I agree to the estimate terms and authorize the work described above.</span>
            </label>

            <div className="flex flex-wrap items-center gap-3">
              <Button
                variant="primary"
                onClick={handleSignEstimate}
                disabled={hasSignature || submitting || !jobs.length}
                loading={submitting}
              >
                Approve & Sign Estimate
              </Button>
              {!allJobsResponded ? (
                <p className="text-sm text-gray-500">
                  You can sign now to approve all remaining jobs, or approve/reject each item above.
                </p>
              ) : null}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/views/public/PublicEstimateView.vue
<template>
  <div class="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto">
      <!-- Loading State -->
      <div v-if="loading" class="text-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
        <p class="mt-4 text-gray-600">Loading estimate...</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
        <h2 class="text-xl font-semibold text-red-800">Unable to Load Estimate</h2>
        <p class="mt-2 text-red-600">{{ error }}</p>
      </div>

      <!-- Estimate Content -->
      <div v-else-if="estimate">
        <!-- Header -->
        <div class="bg-white shadow rounded-lg p-6 mb-6">
          <div class="flex justify-between items-start">
            <div>
              <h1 class="text-2xl font-bold text-gray-900">Estimate #{{ estimate.number }}</h1>
              <p class="mt-1 text-gray-600">
                Status:
                <span :class="statusClass">{{ estimate.status }}</span>
              </p>
            </div>
            <div class="text-right">
              <p class="text-sm text-gray-500">Created</p>
              <p class="font-medium">{{ formatDate(estimate.created_at) }}</p>
              <p v-if="estimate.expiration_date" class="mt-2 text-sm text-gray-500">Expires</p>
              <p v-if="estimate.expiration_date" class="font-medium">{{ formatDate(estimate.expiration_date) }}</p>
            </div>
          </div>
        </div>

        <!-- Customer & Vehicle Info -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div class="bg-white shadow rounded-lg p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-3">Customer</h2>
            <p class="font-medium">{{ customer?.name || 'N/A' }}</p>
            <p v-if="customer?.email" class="text-gray-600">{{ customer.email }}</p>
            <p v-if="customer?.phone" class="text-gray-600">{{ customer.phone }}</p>
          </div>
          <div class="bg-white shadow rounded-lg p-6">
            <h2 class="text-lg font-semibold text-gray-900 mb-3">Vehicle</h2>
            <p class="font-medium">{{ vehicleDescription }}</p>
            <p v-if="vehicle?.vin" class="text-gray-600">VIN: {{ vehicle.vin }}</p>
            <p v-if="vehicle?.license_plate" class="text-gray-600">License: {{ vehicle.license_plate }}</p>
          </div>
        </div>

        <!-- Jobs -->
        <div class="bg-white shadow rounded-lg p-6 mb-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Services</h2>

          <div v-for="(job, jobIndex) in jobs" :key="job.id" class="border border-gray-200 rounded-lg overflow-hidden mb-4 last:mb-0">
            <!-- Job Header -->
            <div class="bg-gray-50 px-4 py-3 flex justify-between items-center">
              <div>
                <h3 class="font-medium text-gray-900">{{ job.title || job.name || `Job ${jobIndex + 1}` }}</h3>
                <p v-if="job.notes" class="text-sm text-gray-600 mt-1">{{ job.notes }}</p>
              </div>
              <div class="flex items-center gap-3">
                <span class="font-semibold text-gray-900">${{ formatNumber(calculateJobTotal(job)) }}</span>
                <span v-if="job.customer_status" :class="jobStatusClass(job.customer_status)" class="text-xs px-2 py-1 rounded font-medium">
                  {{ formatJobStatus(job.customer_status) }}
                </span>
              </div>
            </div>

            <!-- Line Items Table -->
            <div v-if="job.items && job.items.length" class="overflow-x-auto">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                    <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                    <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Qty</th>
                    <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Unit Price</th>
                    <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Total</th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <tr v-for="item in job.items" :key="item.id">
                    <td class="px-4 py-2 whitespace-nowrap">
                      <span :class="item.type === 'LABOR' ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'" class="text-xs px-2 py-1 rounded font-medium">
                        {{ item.type === 'LABOR' ? 'Labor' : 'Part' }}
                      </span>
                    </td>
                    <td class="px-4 py-2">
                      <div class="text-sm text-gray-900">{{ item.description }}</div>
                      <div v-if="item.sku" class="text-xs text-gray-500">SKU: {{ item.sku }}</div>
                    </td>
                    <td class="px-4 py-2 text-right text-sm text-gray-900 whitespace-nowrap">
                      {{ item.quantity }}
                    </td>
                    <td class="px-4 py-2 text-right text-sm text-gray-900 whitespace-nowrap">
                      ${{ formatNumber(item.unit_price) }}
                    </td>
                    <td class="px-4 py-2 text-right text-sm font-medium text-gray-900 whitespace-nowrap">
                      ${{ formatNumber((item.quantity || 0) * (item.unit_price || 0)) }}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <!-- Individual Job Actions -->
            <div v-if="canTakeAction && jobNeedsResponse(job)" class="bg-gray-50 px-4 py-3 border-t border-gray-200 flex justify-end gap-2">
              <button
                @click="approveJob(job)"
                :disabled="submitting"
                class="bg-green-600 text-white text-sm py-1.5 px-4 rounded font-medium hover:bg-green-700 disabled:opacity-50"
              >
                Approve Job
              </button>
              <button
                @click="openRejectJobModal(job)"
                :disabled="submitting"
                class="bg-red-600 text-white text-sm py-1.5 px-4 rounded font-medium hover:bg-red-700 disabled:opacity-50"
              >
                Reject Job
              </button>
            </div>
          </div>
        </div>

        <!-- Totals -->
        <div class="bg-white shadow rounded-lg p-6 mb-6">
          <div class="space-y-2">
            <div class="flex justify-between">
              <span class="text-gray-600">Subtotal</span>
              <span>${{ formatNumber(estimate.subtotal) }}</span>
            </div>
            <div v-if="estimate.discounts > 0" class="flex justify-between text-green-600">
              <span>Discounts</span>
              <span>-${{ formatNumber(estimate.discounts) }}</span>
            </div>
            <div v-if="estimate.tax > 0" class="flex justify-between">
              <span class="text-gray-600">Tax</span>
              <span>${{ formatNumber(estimate.tax) }}</span>
            </div>
            <div class="flex justify-between text-lg font-bold border-t pt-2">
              <span>Total</span>
              <span>${{ formatNumber(estimate.grand_total) }}</span>
            </div>
          </div>
        </div>

        <!-- Notes -->
        <div v-if="estimate.customer_notes" class="bg-white shadow rounded-lg p-6 mb-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-3">Notes</h2>
          <p class="text-gray-600 whitespace-pre-wrap">{{ estimate.customer_notes }}</p>
        </div>

        <!-- Actions (if estimate is pending/sent and has pending jobs) -->
        <div v-if="canTakeAction && hasPendingJobs" class="bg-white shadow rounded-lg p-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Quick Actions</h2>
          <p class="text-gray-600 mb-4">
            You can approve or reject individual jobs above, or use the buttons below to respond to all remaining jobs at once.
          </p>

          <div class="flex gap-4">
            <button
              @click="approveAllPendingJobs"
              :disabled="submitting"
              class="flex-1 bg-green-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-green-700 disabled:opacity-50"
            >
              {{ submitting ? 'Processing...' : 'Approve All Remaining Jobs' }}
            </button>
            <button
              @click="showDeclineModal = true"
              :disabled="submitting"
              class="flex-1 bg-red-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-red-700 disabled:opacity-50"
            >
              Reject All Remaining Jobs
            </button>
          </div>
        </div>

        <!-- Status Message when all jobs have been responded to -->
        <div v-if="canTakeAction && !hasPendingJobs && jobs.length > 0" class="bg-green-50 border border-green-200 rounded-lg p-6">
          <h2 class="text-lg font-semibold text-green-800 mb-2">Thank You!</h2>
          <p class="text-green-700">You have responded to all jobs on this estimate.</p>
        </div>
      </div>
    </div>

    <!-- Decline All Modal -->
    <div v-if="showDeclineModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white rounded-lg p-6 max-w-md w-full">
        <h3 class="text-lg font-semibold mb-4">Reject All Remaining Jobs</h3>
        <p class="text-gray-600 mb-4">This will reject all jobs that haven't been responded to yet.</p>
        <div class="space-y-3">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Reason for rejection</label>
            <select
              v-model="selectedDeclineReason"
              class="w-full border border-gray-300 rounded-lg p-3 bg-white focus:ring-2 focus:ring-red-500 focus:border-red-500"
            >
              <option value="">Select a reason...</option>
              <option v-for="reason in rejectionReasons" :key="reason" :value="reason">
                {{ reason }}
              </option>
            </select>
          </div>
          <div v-if="selectedDeclineReason === 'Other'">
            <label class="block text-sm font-medium text-gray-700 mb-1">Please specify</label>
            <textarea
              v-model="declineReasonOther"
              placeholder="Please let us know why you're rejecting..."
              class="w-full border border-gray-300 rounded-lg p-3 h-24 focus:ring-2 focus:ring-red-500 focus:border-red-500"
            ></textarea>
          </div>
        </div>
        <div class="flex gap-4 mt-4">
          <button
            @click="closeDeclineModal"
            class="flex-1 border border-gray-300 py-2 px-4 rounded-lg hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            @click="rejectAllPendingJobs"
            :disabled="submitting || !selectedDeclineReason"
            class="flex-1 bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700 disabled:opacity-50"
          >
            {{ submitting ? 'Processing...' : 'Confirm Reject All' }}
          </button>
        </div>
      </div>
    </div>

    <!-- Reject Individual Job Modal -->
    <div v-if="showRejectJobModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div class="bg-white rounded-lg p-6 max-w-md w-full">
        <h3 class="text-lg font-semibold mb-4">Reject Job</h3>
        <p class="text-gray-600 mb-4">
          You are rejecting: <strong>{{ rejectingJob?.title || rejectingJob?.name || 'This job' }}</strong>
        </p>
        <div class="space-y-3">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Reason for rejection</label>
            <select
              v-model="selectedJobRejectReason"
              class="w-full border border-gray-300 rounded-lg p-3 bg-white focus:ring-2 focus:ring-red-500 focus:border-red-500"
            >
              <option value="">Select a reason...</option>
              <option v-for="reason in rejectionReasons" :key="reason" :value="reason">
                {{ reason }}
              </option>
            </select>
          </div>
          <div v-if="selectedJobRejectReason === 'Other'">
            <label class="block text-sm font-medium text-gray-700 mb-1">Please specify</label>
            <textarea
              v-model="rejectJobReasonOther"
              placeholder="Please let us know why you're rejecting this job..."
              class="w-full border border-gray-300 rounded-lg p-3 h-24 focus:ring-2 focus:ring-red-500 focus:border-red-500"
            ></textarea>
          </div>
        </div>
        <div class="flex gap-4 mt-4">
          <button
            @click="closeRejectJobModal"
            class="flex-1 border border-gray-300 py-2 px-4 rounded-lg hover:bg-gray-50"
          >
            Cancel
          </button>
          <button
            @click="confirmRejectJob"
            :disabled="submitting || !selectedJobRejectReason"
            class="flex-1 bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700 disabled:opacity-50"
          >
            {{ submitting ? 'Processing...' : 'Confirm Reject' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import api from '@/services/api'

const route = useRoute()

const loading = ref(true)
const error = ref(null)
const estimate = ref(null)
const customer = ref(null)
const vehicle = ref(null)
const jobs = ref([])
const token = ref('')
const shortCode = ref('')

const submitting = ref(false)
const showDeclineModal = ref(false)
const selectedDeclineReason = ref('')
const declineReasonOther = ref('')
const showRejectJobModal = ref(false)
const rejectingJob = ref(null)
const selectedJobRejectReason = ref('')
const rejectJobReasonOther = ref('')
const rejectionReasons = ref([])

const vehicleDescription = computed(() => {
  if (!vehicle.value) return 'N/A'
  const parts = [vehicle.value.year, vehicle.value.make, vehicle.value.model].filter(Boolean)
  return parts.join(' ') || 'N/A'
})

const statusClass = computed(() => {
  const status = estimate.value?.status
  const classes = {
    pending: 'text-yellow-600',
    sent: 'text-blue-600',
    approved: 'text-green-600',
    rejected: 'text-red-600',
    expired: 'text-gray-600',
    converted: 'text-purple-600'
  }
  return classes[status] || 'text-gray-600'
})

const canTakeAction = computed(() => {
  const status = estimate.value?.status
  return status === 'pending' || status === 'sent'
})

const hasPendingJobs = computed(() => {
  return jobs.value.some(job => jobNeedsResponse(job))
})

// Check if a job hasn't been approved or rejected yet
function jobNeedsResponse(job) {
  return job.customer_status !== 'approved' && job.customer_status !== 'rejected'
}

function jobStatusClass(status) {
  const classes = {
    approved: 'bg-green-100 text-green-800',
    rejected: 'bg-red-100 text-red-800',
    pending: 'bg-yellow-100 text-yellow-800'
  }
  return classes[status] || 'bg-gray-100 text-gray-800'
}

function formatJobStatus(status) {
  if (!status) return ''
  return status.charAt(0).toUpperCase() + status.slice(1)
}

function calculateJobTotal(job) {
  if (!job.items || !job.items.length) return job.total || 0
  return job.items.reduce((sum, item) => {
    const quantity = Number(item.quantity) || 0
    const unitPrice = Number(item.unit_price) || 0
    return sum + (quantity * unitPrice)
  }, 0)
}

function formatDate(dateStr) {
  if (!dateStr) return 'N/A'
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

function formatNumber(num) {
  return Number(num || 0).toFixed(2)
}

async function loadEstimate() {
  loading.value = true
  error.value = null

  try {
    token.value = route.query.token || ''
    shortCode.value = route.query.code || ''

    let response
    if (token.value) {
      response = await api.get('/public/estimate', { params: { token: token.value } })
    } else if (shortCode.value) {
      response = await api.get(`/public/estimate/by-code/${shortCode.value}`)
    } else {
      throw new Error('No token or code provided')
    }

    estimate.value = response.data.estimate
    customer.value = response.data.customer
    vehicle.value = response.data.vehicle
    jobs.value = response.data.jobs || []
  } catch (err) {
    console.error('Failed to load estimate:', err)
    error.value = err.response?.data?.error || err.message || 'Failed to load estimate'
  } finally {
    loading.value = false
  }
}

// Approve a single job
async function approveJob(job) {
  if (!token.value || submitting.value) return

  submitting.value = true
  try {
    await api.post('/public/estimate/approve-job', {
      token: token.value,
      job_id: job.id
    })
    // Reload to show updated status
    await loadEstimate()
  } catch (err) {
    console.error('Failed to approve job:', err)
    error.value = err.response?.data?.error || 'Failed to approve job'
  } finally {
    submitting.value = false
  }
}

// Open modal to reject a single job
function openRejectJobModal(job) {
  rejectingJob.value = job
  selectedJobRejectReason.value = ''
  rejectJobReasonOther.value = ''
  showRejectJobModal.value = true
}

function closeRejectJobModal() {
  showRejectJobModal.value = false
  rejectingJob.value = null
  selectedJobRejectReason.value = ''
  rejectJobReasonOther.value = ''
}

function closeDeclineModal() {
  showDeclineModal.value = false
  selectedDeclineReason.value = ''
  declineReasonOther.value = ''
}

// Get the final rejection reason text
function getDeclineReasonText() {
  if (selectedDeclineReason.value === 'Other') {
    return declineReasonOther.value || 'Other'
  }
  return selectedDeclineReason.value
}

function getJobRejectReasonText() {
  if (selectedJobRejectReason.value === 'Other') {
    return rejectJobReasonOther.value || 'Other'
  }
  return selectedJobRejectReason.value
}

// Confirm rejection of a single job
async function confirmRejectJob() {
  if (!token.value || !rejectingJob.value || submitting.value) return

  submitting.value = true
  try {
    await api.post('/public/estimate/reject-job', {
      token: token.value,
      job_id: rejectingJob.value.id,
      rejection_reason: getJobRejectReasonText()
    })
    closeRejectJobModal()
    // Reload to show updated status
    await loadEstimate()
  } catch (err) {
    console.error('Failed to reject job:', err)
    error.value = err.response?.data?.error || 'Failed to reject job'
  } finally {
    submitting.value = false
  }
}

// Approve all pending jobs
async function approveAllPendingJobs() {
  if (!token.value || submitting.value) return

  submitting.value = true
  try {
    // Approve only jobs that haven't been responded to
    const pendingJobs = jobs.value.filter(job => jobNeedsResponse(job))
    for (const job of pendingJobs) {
      await api.post('/public/estimate/approve-job', {
        token: token.value,
        job_id: job.id
      })
    }
    // Reload to show updated status
    await loadEstimate()
  } catch (err) {
    console.error('Failed to approve:', err)
    error.value = err.response?.data?.error || 'Failed to approve jobs'
  } finally {
    submitting.value = false
  }
}

// Reject all pending jobs
async function rejectAllPendingJobs() {
  if (!token.value || submitting.value) return

  submitting.value = true
  try {
    // Reject only jobs that haven't been responded to
    const pendingJobs = jobs.value.filter(job => jobNeedsResponse(job))
    const reasonText = getDeclineReasonText()
    for (const job of pendingJobs) {
      await api.post('/public/estimate/reject-job', {
        token: token.value,
        job_id: job.id,
        rejection_reason: reasonText
      })
    }
    closeDeclineModal()
    // Reload to show updated status
    await loadEstimate()
  } catch (err) {
    console.error('Failed to reject:', err)
    error.value = err.response?.data?.error || 'Failed to reject jobs'
  } finally {
    submitting.value = false
  }
}

// Load rejection reasons from settings
async function loadRejectionReasons() {
  try {
    const response = await api.get('/public/estimate/rejection-reasons')
    rejectionReasons.value = response.data.reasons || []
  } catch (err) {
    console.error('Failed to load rejection reasons:', err)
    // Fallback defaults
    rejectionReasons.value = [
      'Price too high',
      'Found a better deal elsewhere',
      'Decided not to proceed with repairs',
      'Going to a different shop',
      'Vehicle no longer owned',
      'Other'
    ]
  }
}

onMounted(() => {
  loadEstimate()
  loadRejectionReasons()
})
</script>
