// src/react/views/settings/SettingsPage.jsx
import { Link } from 'react-router-dom'

import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import { fetchSettings, saveSettings } from '../../../services/settings.service'

const settingsLinks = [
  {
    title: 'Shop profile',
    description: 'Update shop contact details, branding, and address information.',
    to: '/cp/settings/profile',
  },
  pricing: { taxRate: 0, laborRate: 0, callOutFee: 0, mileageRate: 0 },
  notifications: { fromName: '', fromAddress: '', smsNumber: '', twilioSid: '', twilioToken: '' },
  smtp: { host: '', port: 587, username: '', password: '', encryption: 'tls' },
  payments: {
    successUrl: '',
    cancelUrl: '',
    stripePublic: '',
    stripeSecret: '',
    stripeWebhook: '',
    squareToken: '',
    squareSignature: '',
    paypalClientId: '',
    paypalClientSecret: '',
    paypalWebhook: '',
  {
    title: 'Terms & Documents',
    description: 'Manage estimate and invoice terms shown to customers.',
    to: '/cp/settings/terms',
  },
  {
    title: 'Rejection reasons',
    description: 'Maintain the predefined reasons customers can select when declining work.',
    to: '/cp/settings/rejection-reasons',
  },
  {
    title: 'Pricing',
    description: 'Set default tax, labor, and fee values for new work.',
    to: '/cp/settings/pricing',
  },
  {
    title: 'Notifications',
    description: 'Configure outbound email and SMS settings.',
    to: '/cp/settings/notifications',
  },
  {
    title: 'Payments',
    description: 'Connect payment processors and update redirect URLs.',
    to: '/cp/settings/payments',
  },
  {
    title: 'Integrations',
    description: 'Manage third-party integrations like Zoho, reCAPTCHA, and PartsTech.',
    to: '/cp/settings/integrations',
  },
  {
    title: 'Service types',
    description: 'Add and organize service categories used across estimates and bundles.',
    to: '/cp/settings/services',
  },
]

export default function SettingsPage() {
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [form, setForm] = useState(initialFormState)

  const hydrate = useCallback(async () => {
    setLoading(true)
    setError('')

    try {
      const settings = await fetchSettings()
      setForm((prev) => {
        const addressSetting = getSetting(settings, 'shop.address', {}) || {}
        const markup = getSetting(settings, 'integrations.partstech.markup_tiers', [])
        const partsTechMarkup = markup && markup.length ? JSON.stringify(markup, null, 2) : ''

        return {
          ...prev,
          profile: {
            ...prev.profile,
            name: getSetting(settings, 'shop.name', ''),
            email: getSetting(settings, 'shop.email', ''),
            phone: getSetting(settings, 'shop.phone', ''),
            logoUrl: getSetting(settings, 'shop.logo_url', ''),
            address: {
              street: addressSetting?.street ?? '',
              city: addressSetting?.city ?? '',
              state: addressSetting?.state ?? '',
              postal_code: addressSetting?.postal_code ?? '',
              country: addressSetting?.country ?? '',
            },
          },
          pricing: {
            taxRate: Number(getSetting(settings, 'pricing.tax_rate', 0)),
            laborRate: Number(getSetting(settings, 'pricing.labor_rate', 0)),
            callOutFee: Number(getSetting(settings, 'pricing.call_out_fee', 0)),
            mileageRate: Number(getSetting(settings, 'pricing.mileage_rate', 0)),
          },
          notifications: {
            fromName: getSetting(settings, 'notifications.mail.from_name', ''),
            fromAddress: getSetting(settings, 'notifications.mail.from_address', ''),
            smsNumber: getSetting(settings, 'notifications.sms.from_number', ''),
            twilioSid: getSetting(settings, 'integrations.twilio.sid', ''),
            twilioToken: getSetting(settings, 'integrations.twilio.token', ''),
          },
          smtp: {
            host: getSetting(settings, 'integrations.smtp.host', ''),
            port: Number(getSetting(settings, 'integrations.smtp.port', 587)),
            username: getSetting(settings, 'integrations.smtp.username', ''),
            password: getSetting(settings, 'integrations.smtp.password', ''),
            encryption: getSetting(settings, 'integrations.smtp.encryption', 'tls'),
          },
          payments: {
            successUrl: getSetting(settings, 'payments.urls.success', ''),
            cancelUrl: getSetting(settings, 'payments.urls.cancel', ''),
            stripePublic: getSetting(settings, 'integrations.stripe.public_key', ''),
            stripeSecret: getSetting(settings, 'integrations.stripe.secret_key', ''),
            stripeWebhook: getSetting(settings, 'integrations.stripe.webhook_secret', ''),
            squareToken: getSetting(settings, 'integrations.square.token', ''),
            squareSignature: getSetting(settings, 'integrations.square.webhook_signature_key', ''),
            paypalClientId: getSetting(settings, 'integrations.paypal.client_id', ''),
            paypalClientSecret: getSetting(settings, 'integrations.paypal.client_secret', ''),
            paypalWebhook: getSetting(settings, 'integrations.paypal.webhook_id', ''),
          },
          security: {
            recaptchaEnabled: !!getSetting(settings, 'integrations.recaptcha.enabled', false),
            recaptchaSiteKey: getSetting(settings, 'integrations.recaptcha.site_key', ''),
            recaptchaSecretKey: getSetting(settings, 'integrations.recaptcha.secret_key', ''),
          },
          integrations: {
            zohoClientId: getSetting(settings, 'integrations.zoho.client_id', ''),
            zohoClientSecret: getSetting(settings, 'integrations.zoho.client_secret', ''),
            zohoRefreshToken: getSetting(settings, 'integrations.zoho.refresh_token', ''),
            zohoOrgId: getSetting(settings, 'integrations.zoho.org_id', ''),
            partsTechBase: getSetting(settings, 'integrations.partstech.api_base', ''),
            partsTechKey: getSetting(settings, 'integrations.partstech.api_key', ''),
            partsTechMarkup,
          },
        }
      })
    } catch (fetchError) {
      setError(fetchError?.message || 'Unable to load settings.')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    hydrate()
  }, [hydrate])

  const updateField = (path, value) => {
    setForm((prev) => {
      const next = { ...prev }
      let target = next
      for (let i = 0; i < path.length - 1; i += 1) {
        target[path[i]] = { ...target[path[i]] }
        target = target[path[i]]
      }
      target[path[path.length - 1]] = value
      return next
    })
  }

  const parseMarkup = useCallback(() => {
    if (!form.integrations.partsTechMarkup) {
      return []
    }

    try {
      const parsed = JSON.parse(form.integrations.partsTechMarkup)
      return Array.isArray(parsed) ? parsed : []
    } catch (parseError) {
      throw new Error('PartsTech markup tiers must be valid JSON.')
    }
  }, [form.integrations.partsTechMarkup])

  const payload = useMemo(() => {
    return {
      'shop.name': form.profile.name,
      'shop.email': form.profile.email,
      'shop.phone': form.profile.phone,
      'shop.logo_url': form.profile.logoUrl,
      'shop.address': { ...form.profile.address },
      'pricing.tax_rate': Number(form.pricing.taxRate) || 0,
      'pricing.labor_rate': Number(form.pricing.laborRate) || 0,
      'pricing.call_out_fee': Number(form.pricing.callOutFee) || 0,
      'pricing.mileage_rate': Number(form.pricing.mileageRate) || 0,
      'notifications.mail.from_name': form.notifications.fromName,
      'notifications.mail.from_address': form.notifications.fromAddress,
      'notifications.sms.from_number': form.notifications.smsNumber,
      'integrations.twilio.sid': form.notifications.twilioSid,
      'integrations.twilio.token': form.notifications.twilioToken,
      'integrations.smtp.host': form.smtp.host,
      'integrations.smtp.port': Number(form.smtp.port) || 0,
      'integrations.smtp.username': form.smtp.username,
      'integrations.smtp.password': form.smtp.password,
      'integrations.smtp.encryption': form.smtp.encryption,
      'payments.urls.success': form.payments.successUrl,
      'payments.urls.cancel': form.payments.cancelUrl,
      'integrations.stripe.public_key': form.payments.stripePublic,
      'integrations.stripe.secret_key': form.payments.stripeSecret,
      'integrations.stripe.webhook_secret': form.payments.stripeWebhook,
      'integrations.square.token': form.payments.squareToken,
      'integrations.square.webhook_signature_key': form.payments.squareSignature,
      'integrations.paypal.client_id': form.payments.paypalClientId,
      'integrations.paypal.client_secret': form.payments.paypalClientSecret,
      'integrations.paypal.webhook_id': form.payments.paypalWebhook,
      'integrations.recaptcha.enabled': !!form.security.recaptchaEnabled,
      'integrations.recaptcha.site_key': form.security.recaptchaSiteKey,
      'integrations.recaptcha.secret_key': form.security.recaptchaSecretKey,
      'integrations.zoho.client_id': form.integrations.zohoClientId,
      'integrations.zoho.client_secret': form.integrations.zohoClientSecret,
      'integrations.zoho.refresh_token': form.integrations.zohoRefreshToken,
      'integrations.zoho.org_id': form.integrations.zohoOrgId,
      'integrations.partstech.api_base': form.integrations.partsTechBase,
      'integrations.partstech.api_key': form.integrations.partsTechKey,
    }
  }, [form])

  const handleSave = async () => {
    setSaving(true)
    setMessage('')
    setError('')

    let markupTiers = []
    try {
      markupTiers = parseMarkup()
    } catch (parseError) {
      setSaving(false)
      setError(parseError.message)
      return
    }

    try {
      await saveSettings({
        ...payload,
        'integrations.partstech.markup_tiers': markupTiers,
      })
      setMessage('Settings saved successfully.')
    } catch (saveError) {
      setError(saveError?.response?.data?.message || saveError?.message || 'Failed to save settings.')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Settings overview</h1>
        <p className="mt-1 text-sm text-gray-500">
          Jump into a category to update your shop settings.
        </p>
      </div>

      {message ? <Alert variant="success" className="mb-4">{message}</Alert> : null}
      {error ? <Alert variant="danger" className="mb-4">{error}</Alert> : null}

      {loading ? <div className="text-gray-500">Loading settings...</div> : (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Shop Profile</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Shop Name</label>
                  <Input
                    value={form.profile.name}
                    placeholder="Demo Auto Shop"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'name'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Notification Email</label>
                  <Input
                    value={form.profile.email}
                    placeholder="noreply@example.com"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'email'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Phone</label>
                  <Input
                    value={form.profile.phone}
                    placeholder="+1 (555) 123-4567"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'phone'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Logo URL</label>
                  <Input
                    value={form.profile.logoUrl}
                    placeholder="https://cdn.example.com/logo.png"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'logoUrl'], event.target.value)}
                  />
                </div>
              </div>
              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Street</label>
                  <Input
                    value={form.profile.address.street}
                    placeholder="123 Main St"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'address', 'street'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">City</label>
                  <Input
                    value={form.profile.address.city}
                    placeholder="Anytown"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'address', 'city'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">State/Province</label>
                  <Input
                    value={form.profile.address.state}
                    placeholder="CA"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'address', 'state'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Postal Code</label>
                  <Input
                    value={form.profile.address.postal_code}
                    placeholder="90210"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'address', 'postal_code'], event.target.value)}
                  />
                </div>
                <div className="md:col-span-2">
                  <label className="block text-sm font-medium text-gray-700">Country</label>
                  <Input
                    value={form.profile.address.country}
                    placeholder="United States"
                    className="mt-1"
                    onChange={(event) => updateField(['profile', 'address', 'country'], event.target.value)}
                  />
                </div>
              </div>
            </Card>

            <Card>
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Terms &amp; Documents</h2>
              <p className="text-sm text-gray-500">
                Terms and conditions are now managed in the Terms settings page.
              </p>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Pricing Defaults</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Tax Rate (%)</label>
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={form.pricing.taxRate}
                    className="mt-1"
                    onChange={(event) => updateField(['pricing', 'taxRate'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Labor Rate (per hour)</label>
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={form.pricing.laborRate}
                    className="mt-1"
                    onChange={(event) => updateField(['pricing', 'laborRate'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Call-out Fee</label>
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={form.pricing.callOutFee}
                    className="mt-1"
                    onChange={(event) => updateField(['pricing', 'callOutFee'], event.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Mileage Rate</label>
                  <Input
                    type="number"
                    step="0.01"
                    min="0"
                    value={form.pricing.mileageRate}
                    className="mt-1"
                    onChange={(event) => updateField(['pricing', 'mileageRate'], event.target.value)}
                  />
                </div>
              </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {settingsLinks.map((link) => (
          <Link key={link.to} to={link.to} className="group">
            <Card className="h-full transition group-hover:shadow-md">
              <h2 className="text-lg font-semibold text-gray-900">{link.title}</h2>
              <p className="mt-2 text-sm text-gray-500">{link.description}</p>
              <span className="mt-4 inline-flex text-sm font-medium text-primary-600">
                Manage settings →
              </span>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  )
}

// src/views/settings/SettingsPage.vue
<template>
  <div>
    <div class="mb-6 flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Settings</h1>
        <p class="mt-1 text-sm text-gray-500">Manage shop profile, terms, pricing defaults, and integrations.</p>
      </div>
      <Button :loading="saving" @click="save">Save Settings</Button>
    </div>

    <Alert v-if="message" variant="success" class="mb-4">{{ message }}</Alert>
    <Alert v-if="error" variant="danger" class="mb-4">{{ error }}</Alert>

    <div v-if="loading" class="text-gray-500">Loading settings...</div>

    <div v-else class="space-y-6">
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Shop Profile</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Shop Name</label>
              <Input v-model="form.profile.name" placeholder="Demo Auto Shop" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Notification Email</label>
              <Input v-model="form.profile.email" placeholder="noreply@example.com" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Phone</label>
              <Input v-model="form.profile.phone" placeholder="+1 (555) 123-4567" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Logo URL</label>
              <Input v-model="form.profile.logoUrl" placeholder="https://cdn.example.com/logo.png" class="mt-1" />
            </div>
          </div>
          <div class="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Street</label>
              <Input v-model="form.profile.address.street" placeholder="123 Main St" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">City</label>
              <Input v-model="form.profile.address.city" placeholder="Anytown" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">State/Province</label>
              <Input v-model="form.profile.address.state" placeholder="CA" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Postal Code</label>
              <Input v-model="form.profile.address.postal_code" placeholder="90210" class="mt-1" />
            </div>
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">Country</label>
              <Input v-model="form.profile.address.country" placeholder="United States" class="mt-1" />
            </div>
          </div>
        </Card>

        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Terms & Documents</h2>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Estimate Terms</label>
              <Textarea v-model="form.terms.estimates" :rows="4" placeholder="Terms shown on estimates" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Invoice Terms</label>
              <Textarea v-model="form.terms.invoices" :rows="4" placeholder="Terms shown on invoices" class="mt-1" />
            </div>
          </div>
        </Card>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Pricing Defaults</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Tax Rate (%)</label>
              <Input v-model.number="form.pricing.taxRate" type="number" step="0.01" min="0" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Labor Rate (per hour)</label>
              <Input v-model.number="form.pricing.laborRate" type="number" step="0.01" min="0" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Call-out Fee</label>
              <Input v-model.number="form.pricing.callOutFee" type="number" step="0.01" min="0" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Mileage Rate</label>
              <Input v-model.number="form.pricing.mileageRate" type="number" step="0.01" min="0" class="mt-1" />
            </div>
          </div>
        </Card>

        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Notifications & Mail</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">From Name</label>
              <Input v-model="form.notifications.fromName" placeholder="Demo Auto Shop" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">From Email</label>
              <Input v-model="form.notifications.fromAddress" placeholder="noreply@example.com" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">SMS From Number</label>
              <Input v-model="form.notifications.smsNumber" placeholder="+15551234567" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Twilio SID</label>
              <Input v-model="form.notifications.twilioSid" placeholder="ACXXXXXXXXXXXXXXXX" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Twilio Token</label>
              <Input v-model="form.notifications.twilioToken" placeholder="••••••••" class="mt-1" />
            </div>
          </div>
          <div class="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">SMTP Host</label>
              <Input v-model="form.smtp.host" placeholder="smtp.mailgun.org" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">SMTP Port</label>
              <Input v-model.number="form.smtp.port" type="number" min="1" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">SMTP Username</label>
              <Input v-model="form.smtp.username" placeholder="user" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">SMTP Password</label>
              <Input v-model="form.smtp.password" placeholder="••••••••" class="mt-1" />
            </div>
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">SMTP Encryption</label>
              <Input v-model="form.smtp.encryption" placeholder="tls" class="mt-1" />
            </div>
          </div>
        </Card>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Payments</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">Success URL</label>
              <Input v-model="form.payments.successUrl" placeholder="https://app.example.com/payment/success" class="mt-1" />
            </div>
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">Cancel URL</label>
              <Input v-model="form.payments.cancelUrl" placeholder="https://app.example.com/payment/cancel" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Stripe Publishable Key</label>
              <Input v-model="form.payments.stripePublic" placeholder="pk_live_" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Stripe Secret Key</label>
              <Input v-model="form.payments.stripeSecret" placeholder="sk_live_" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Stripe Webhook Secret</label>
              <Input v-model="form.payments.stripeWebhook" placeholder="whsec_" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Square Token</label>
              <Input v-model="form.payments.squareToken" placeholder="sq0atp-" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Square Webhook Signature Key</label>
              <Input v-model="form.payments.squareSignature" placeholder="sig_key" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">PayPal Client ID</label>
              <Input v-model="form.payments.paypalClientId" placeholder="paypal client id" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">PayPal Client Secret</label>
              <Input v-model="form.payments.paypalClientSecret" placeholder="paypal secret" class="mt-1" />
            </div>
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">PayPal Webhook ID</label>
              <Input v-model="form.payments.paypalWebhook" placeholder="WH-XXXX" class="mt-1" />
            </div>
          </div>
        </Card>

        <Card>
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Integrations</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">reCAPTCHA Site Key</label>
              <Input v-model="form.security.recaptchaSiteKey" placeholder="site key" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">reCAPTCHA Secret Key</label>
              <Input v-model="form.security.recaptchaSecretKey" placeholder="secret key" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Zoho Client ID</label>
              <Input v-model="form.integrations.zohoClientId" placeholder="Zoho client id" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Zoho Client Secret</label>
              <Input v-model="form.integrations.zohoClientSecret" placeholder="Zoho client secret" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Zoho Refresh Token</label>
              <Input v-model="form.integrations.zohoRefreshToken" placeholder="Zoho refresh token" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Zoho Org ID</label>
              <Input v-model="form.integrations.zohoOrgId" placeholder="Zoho org id" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">PartsTech API Base</label>
              <Input v-model="form.integrations.partsTechBase" placeholder="https://api.partstech.com" class="mt-1" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">PartsTech API Key</label>
              <Input v-model="form.integrations.partsTechKey" placeholder="PartsTech key" class="mt-1" />
            </div>
          </div>
          <div class="mt-4">
            <label class="block text-sm font-medium text-gray-700">PartsTech Markup Tiers (JSON)</label>
            <Textarea
              v-model="form.integrations.partsTechMarkup"
              :rows="3"
              placeholder='[{"threshold":0,"markup":0.2}]'
              class="mt-1"
            />
          </div>
        </Card>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import Alert from '@/components/ui/Alert.vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import Textarea from '@/components/ui/Textarea.vue'
import { fetchSettings, saveSettings } from '@/services/settings.service'

const loading = ref(true)
const saving = ref(false)
const message = ref('')
const error = ref('')

const form = reactive({
  profile: {
    name: '',
    email: '',
    phone: '',
    logoUrl: '',
    address: { street: '', city: '', state: '', postal_code: '', country: '' },
  },
  terms: { estimates: '', invoices: '' },
  pricing: { taxRate: 0, laborRate: 0, callOutFee: 0, mileageRate: 0 },
  notifications: { fromName: '', fromAddress: '', smsNumber: '', twilioSid: '', twilioToken: '' },
  smtp: { host: '', port: 587, username: '', password: '', encryption: 'tls' },
  payments: {
    successUrl: '',
    cancelUrl: '',
    stripePublic: '',
    stripeSecret: '',
    stripeWebhook: '',
    squareToken: '',
    squareSignature: '',
    paypalClientId: '',
    paypalClientSecret: '',
    paypalWebhook: '',
  },
  security: { recaptchaSiteKey: '', recaptchaSecretKey: '' },
  integrations: {
    zohoClientId: '',
    zohoClientSecret: '',
    zohoRefreshToken: '',
    zohoOrgId: '',
    partsTechBase: '',
    partsTechKey: '',
    partsTechMarkup: '',
  },
})

const getSetting = (settings, key, fallback = null) => {
  return settings?.[key]?.value ?? fallback
}

const hydrate = async () => {
  loading.value = true
  error.value = ''
  try {
    const settings = await fetchSettings()
    form.profile.name = getSetting(settings, 'shop.name', '')
    form.profile.email = getSetting(settings, 'shop.email', '')
    form.profile.phone = getSetting(settings, 'shop.phone', '')
    form.profile.logoUrl = getSetting(settings, 'shop.logo_url', '')
    form.profile.address = {
      street: getSetting(settings, 'shop.address', {})?.street ?? '',
      city: getSetting(settings, 'shop.address', {})?.city ?? '',
      state: getSetting(settings, 'shop.address', {})?.state ?? '',
      postal_code: getSetting(settings, 'shop.address', {})?.postal_code ?? '',
      country: getSetting(settings, 'shop.address', {})?.country ?? '',
    }

    form.terms.estimates = getSetting(settings, 'documents.terms.estimates', '')
    form.terms.invoices = getSetting(settings, 'documents.terms.invoices', '')

    form.pricing.taxRate = Number(getSetting(settings, 'pricing.tax_rate', 0))
    form.pricing.laborRate = Number(getSetting(settings, 'pricing.labor_rate', 0))
    form.pricing.callOutFee = Number(getSetting(settings, 'pricing.call_out_fee', 0))
    form.pricing.mileageRate = Number(getSetting(settings, 'pricing.mileage_rate', 0))

    form.notifications.fromName = getSetting(settings, 'notifications.mail.from_name', '')
    form.notifications.fromAddress = getSetting(settings, 'notifications.mail.from_address', '')
    form.notifications.smsNumber = getSetting(settings, 'notifications.sms.from_number', '')
    form.notifications.twilioSid = getSetting(settings, 'integrations.twilio.sid', '')
    form.notifications.twilioToken = getSetting(settings, 'integrations.twilio.token', '')

    form.smtp.host = getSetting(settings, 'integrations.smtp.host', '')
    form.smtp.port = Number(getSetting(settings, 'integrations.smtp.port', 587))
    form.smtp.username = getSetting(settings, 'integrations.smtp.username', '')
    form.smtp.password = getSetting(settings, 'integrations.smtp.password', '')
    form.smtp.encryption = getSetting(settings, 'integrations.smtp.encryption', 'tls')

    form.payments.successUrl = getSetting(settings, 'payments.urls.success', '')
    form.payments.cancelUrl = getSetting(settings, 'payments.urls.cancel', '')
    form.payments.stripePublic = getSetting(settings, 'integrations.stripe.public_key', '')
    form.payments.stripeSecret = getSetting(settings, 'integrations.stripe.secret_key', '')
    form.payments.stripeWebhook = getSetting(settings, 'integrations.stripe.webhook_secret', '')
    form.payments.squareToken = getSetting(settings, 'integrations.square.token', '')
    form.payments.squareSignature = getSetting(settings, 'integrations.square.webhook_signature_key', '')
    form.payments.paypalClientId = getSetting(settings, 'integrations.paypal.client_id', '')
    form.payments.paypalClientSecret = getSetting(settings, 'integrations.paypal.client_secret', '')
    form.payments.paypalWebhook = getSetting(settings, 'integrations.paypal.webhook_id', '')

    form.security.recaptchaSiteKey = getSetting(settings, 'integrations.recaptcha.site_key', '')
    form.security.recaptchaSecretKey = getSetting(settings, 'integrations.recaptcha.secret_key', '')

    form.integrations.zohoClientId = getSetting(settings, 'integrations.zoho.client_id', '')
    form.integrations.zohoClientSecret = getSetting(settings, 'integrations.zoho.client_secret', '')
    form.integrations.zohoRefreshToken = getSetting(settings, 'integrations.zoho.refresh_token', '')
    form.integrations.zohoOrgId = getSetting(settings, 'integrations.zoho.org_id', '')
    form.integrations.partsTechBase = getSetting(settings, 'integrations.partstech.api_base', '')
    form.integrations.partsTechKey = getSetting(settings, 'integrations.partstech.api_key', '')
    const markup = getSetting(settings, 'integrations.partstech.markup_tiers', [])
    form.integrations.partsTechMarkup = markup && markup.length ? JSON.stringify(markup, null, 2) : ''
  } catch (e) {
    error.value = e?.message || 'Unable to load settings.'
  } finally {
    loading.value = false
  }
}

const parseMarkup = () => {
  if (!form.integrations.partsTechMarkup) {
    return []
  }

  try {
    const parsed = JSON.parse(form.integrations.partsTechMarkup)
    return Array.isArray(parsed) ? parsed : []
  } catch (e) {
    throw new Error('PartsTech markup tiers must be valid JSON.')
  }
}

const save = async () => {
  saving.value = true
  message.value = ''
  error.value = ''

  let markupTiers = []
  try {
    markupTiers = parseMarkup()
  } catch (e) {
    saving.value = false
    error.value = e.message
    return
  }

  const payload = {
    'shop.name': form.profile.name,
    'shop.email': form.profile.email,
    'shop.phone': form.profile.phone,
    'shop.logo_url': form.profile.logoUrl,
    'shop.address': { ...form.profile.address },
    'documents.terms.estimates': form.terms.estimates,
    'documents.terms.invoices': form.terms.invoices,
    'pricing.tax_rate': Number(form.pricing.taxRate) || 0,
    'pricing.labor_rate': Number(form.pricing.laborRate) || 0,
    'pricing.call_out_fee': Number(form.pricing.callOutFee) || 0,
    'pricing.mileage_rate': Number(form.pricing.mileageRate) || 0,
    'notifications.mail.from_name': form.notifications.fromName,
    'notifications.mail.from_address': form.notifications.fromAddress,
    'notifications.sms.from_number': form.notifications.smsNumber,
    'integrations.twilio.sid': form.notifications.twilioSid,
    'integrations.twilio.token': form.notifications.twilioToken,
    'integrations.smtp.host': form.smtp.host,
    'integrations.smtp.port': Number(form.smtp.port) || 0,
    'integrations.smtp.username': form.smtp.username,
    'integrations.smtp.password': form.smtp.password,
    'integrations.smtp.encryption': form.smtp.encryption,
    'payments.urls.success': form.payments.successUrl,
    'payments.urls.cancel': form.payments.cancelUrl,
    'integrations.stripe.public_key': form.payments.stripePublic,
    'integrations.stripe.secret_key': form.payments.stripeSecret,
    'integrations.stripe.webhook_secret': form.payments.stripeWebhook,
    'integrations.square.token': form.payments.squareToken,
    'integrations.square.webhook_signature_key': form.payments.squareSignature,
    'integrations.paypal.client_id': form.payments.paypalClientId,
    'integrations.paypal.client_secret': form.payments.paypalClientSecret,
    'integrations.paypal.webhook_id': form.payments.paypalWebhook,
    'integrations.recaptcha.site_key': form.security.recaptchaSiteKey,
    'integrations.recaptcha.secret_key': form.security.recaptchaSecretKey,
    'integrations.zoho.client_id': form.integrations.zohoClientId,
    'integrations.zoho.client_secret': form.integrations.zohoClientSecret,
    'integrations.zoho.refresh_token': form.integrations.zohoRefreshToken,
    'integrations.zoho.org_id': form.integrations.zohoOrgId,
    'integrations.partstech.api_base': form.integrations.partsTechBase,
    'integrations.partstech.api_key': form.integrations.partsTechKey,
    'integrations.partstech.markup_tiers': markupTiers,
  }

  try {
    await saveSettings(payload)
    message.value = 'Settings saved successfully.'
  } catch (e) {
    error.value = e?.response?.data?.message || e?.message || 'Failed to save settings.'
  } finally {
    saving.value = false
  }
}

onMounted(hydrate)
</script>
