// src/react/views/Reports.jsx
import { useEffect, useMemo, useState } from 'react'

import BarChart from '../components/charts/BarChart'
import LineChart from '../components/charts/LineChart'
import Button from '../components/ui/Button'
import Card from '../components/ui/Card'
import Input from '../components/ui/Input'
import FinancialReports from './financial/Reports'
import reportsService from '../../services/reports.service'
import { useToast } from '../stores/toast.jsx'

const tabs = [
  { key: 'technician', label: 'Technician Margins' },
  { key: 'financial', label: 'Financial Reports' },
]

function formatCurrency(value) {
  return `$${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function formatPercent(value) {
  return `${Number(value || 0).toFixed(2)}%`
}

function TechnicianMargins() {
  const toast = useToast()
  const [loading, setLoading] = useState(false)
  const [filters, setFilters] = useState({ start_date: '', end_date: '', branch_id: '' })
  const [report, setReport] = useState({
    data: [],
    summary: {
      total_billed_labor: 0,
      total_actual_cost: 0,
      total_actual_minutes: 0,
      total_margin: 0,
      overall_margin_percentage: 0,
      default_labor_rate: 0,
    },
  })

  useEffect(() => {
    const today = new Date()
    const endDate = today.toISOString().slice(0, 10)
    const monthAgo = new Date()
    monthAgo.setDate(monthAgo.getDate() - 30)
    const startDate = monthAgo.toISOString().slice(0, 10)
    setFilters({ start_date: startDate, end_date: endDate, branch_id: '' })
  }, [])

  useEffect(() => {
    if (filters.start_date && filters.end_date) {
      fetchReport()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters.start_date, filters.end_date])

  const fetchReport = () => {
    if (!filters.start_date || !filters.end_date) {
      toast.error('Start and end date are required')
      return
    }

    setLoading(true)
    reportsService
      .technicianMargins({
        start_date: filters.start_date,
        end_date: filters.end_date,
        branch_id: filters.branch_id || undefined,
      })
      .then((data) => {
        setReport({
          data: data.data || [],
          summary: data.summary || report.summary,
        })
      })
      .catch(() => toast.error('Failed to load technician margin report'))
      .finally(() => setLoading(false))
  }

  const technicianChartData = useMemo(() => {
    if (!report.data.length) {
      return { labels: [], datasets: [] }
    }

    return {
      labels: report.data.map((row) => row.technician_name || `Tech #${row.technician_id}`),
      datasets: [
        {
          label: 'Billed Labor',
          data: report.data.map((row) => row.billed_labor),
          backgroundColor: 'rgba(59, 130, 246, 0.8)',
        },
        {
          label: 'Actual Labor Cost',
          data: report.data.map((row) => row.actual_labor_cost),
          backgroundColor: 'rgba(239, 68, 68, 0.75)',
        },
        {
          label: 'Margin',
          data: report.data.map((row) => row.margin),
          backgroundColor: 'rgba(16, 185, 129, 0.75)',
        },
      ],
    }
  }, [report.data])

  const marginPercentageData = useMemo(() => {
    if (!report.data.length) {
      return { labels: [], datasets: [] }
    }

    return {
      labels: report.data.map((row) => row.technician_name || `Tech #${row.technician_id}`),
      datasets: [
        {
          label: 'Margin %',
          data: report.data.map((row) => row.margin_percentage),
          borderColor: 'rgba(16, 185, 129, 0.9)',
          backgroundColor: 'rgba(16, 185, 129, 0.2)',
          tension: 0.3,
        },
      ],
    }
  }, [report.data])

  const currencyChartOptions = {
    plugins: {
      tooltip: {
        callbacks: {
          label: (context) => `${context.dataset.label}: ${formatCurrency(context.parsed.y)}`,
        },
      },
    },
    scales: {
      y: {
        ticks: {
          callback: (value) => formatCurrency(value),
        },
      },
    },
  }

  const marginChartOptions = {
    plugins: {
      tooltip: {
        callbacks: {
          label: (context) => `${context.dataset.label}: ${formatPercent(context.parsed.y)}`,
        },
      },
    },
    scales: {
      y: {
        ticks: {
          callback: (value) => formatPercent(value),
        },
      },
    },
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">Technician Efficiency Dashboard</h1>
        <p className="text-sm text-gray-600">Track billed labor vs. actual labor cost by technician.</p>
      </div>

      <Card className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">Start Date</label>
            <Input
              modelValue={filters.start_date}
              type="date"
              onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, start_date: value }))}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">End Date</label>
            <Input
              modelValue={filters.end_date}
              type="date"
              onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, end_date: value }))}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Branch (optional)</label>
            <Input
              modelValue={filters.branch_id}
              type="number"
              placeholder="Branch ID"
              onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, branch_id: value }))}
            />
          </div>
          <div className="flex items-end">
            <Button className="w-full" onClick={fetchReport} disabled={loading}>
              {loading ? 'Loading...' : 'Refresh'}
            </Button>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <p className="text-sm text-gray-600">Total Billed Labor</p>
          <p className="text-2xl font-semibold text-gray-900">{formatCurrency(report.summary.total_billed_labor)}</p>
        </Card>
        <Card>
          <p className="text-sm text-gray-600">Actual Labor Cost</p>
          <p className="text-2xl font-semibold text-gray-900">{formatCurrency(report.summary.total_actual_cost)}</p>
        </Card>
        <Card>
          <p className="text-sm text-gray-600">Total Margin</p>
          <p className="text-2xl font-semibold text-gray-900">{formatCurrency(report.summary.total_margin)}</p>
        </Card>
        <Card>
          <p className="text-sm text-gray-600">Overall Margin %</p>
          <p className="text-2xl font-semibold text-gray-900">{formatPercent(report.summary.overall_margin_percentage)}</p>
          <p className="text-xs text-gray-500">Default labor rate: {formatCurrency(report.summary.default_labor_rate)}/hr</p>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="h-96">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Billed vs. Actual Labor</h3>
          <BarChart data={technicianChartData} options={currencyChartOptions} />
        </Card>
        <Card className="h-96">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Margin Percentage by Technician</h3>
          <LineChart data={marginPercentageData} options={marginChartOptions} />
        </Card>
      </div>

      <Card>
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Technician Margin Details</h3>
        {report.data.length ? (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Technician</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Billed Labor</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actual Cost</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Margin</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Margin %</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actual Minutes</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {report.data.map((row) => (
                  <tr key={row.technician_id}>
                    <td className="px-4 py-3 text-sm font-medium text-gray-900">
                      {row.technician_name || `Tech #${row.technician_id}`}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-700 text-right">{formatCurrency(row.billed_labor)}</td>
                    <td className="px-4 py-3 text-sm text-gray-700 text-right">{formatCurrency(row.actual_labor_cost)}</td>
                    <td className="px-4 py-3 text-sm text-gray-700 text-right">{formatCurrency(row.margin)}</td>
                    <td className="px-4 py-3 text-sm text-gray-700 text-right">{formatPercent(row.margin_percentage)}</td>
                    <td className="px-4 py-3 text-sm text-gray-700 text-right">{Number(row.actual_minutes || 0).toFixed(0)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="text-sm text-gray-500">No technician labor data found for the selected range.</p>
        )}
      </Card>
    </div>
  )
}

export default function Reports() {
  const [activeTab, setActiveTab] = useState('technician')

  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-wrap gap-2">
        {tabs.map((tab) => (
          <Button
            key={tab.key}
            variant={activeTab === tab.key ? 'primary' : 'secondary'}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
          </Button>
        ))}
      </div>

      {activeTab === 'technician' ? <TechnicianMargins /> : null}
      {activeTab === 'financial' ? <FinancialReports /> : null}
    </div>
  )
}

// src/views/financial/Reports.vue
<template>
  <div class="p-6 space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-semibold text-gray-900">Financial Reports</h1>
        <p class="text-sm text-gray-600">Monthly breakdowns of income, expenses, and purchases with CSV export.</p>
      </div>
      <button
        class="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
        @click="exportReport"
      >
        Export CSV
      </button>
    </div>

    <div class="bg-white shadow rounded p-4 space-y-4">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700">Start Date</label>
          <input v-model="filters.start_date" type="date" class="mt-1 w-full border-gray-300 rounded" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700">End Date</label>
          <input v-model="filters.end_date" type="date" class="mt-1 w-full border-gray-300 rounded" />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700">Category</label>
          <input v-model="filters.category" type="text" class="mt-1 w-full border-gray-300 rounded" />
        </div>
        <div class="flex items-end">
          <button class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 w-full" @click="fetchReport">
            Refresh
          </button>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div class="bg-white shadow rounded p-4">
        <p class="text-sm text-gray-500">Income</p>
        <p class="text-2xl font-semibold text-green-600">${{ totals.income.toFixed(2) }}</p>
      </div>
      <div class="bg-white shadow rounded p-4">
        <p class="text-sm text-gray-500">Expenses</p>
        <p class="text-2xl font-semibold text-red-600">${{ totals.expense.toFixed(2) }}</p>
      </div>
      <div class="bg-white shadow rounded p-4">
        <p class="text-sm text-gray-500">Purchases</p>
        <p class="text-2xl font-semibold text-orange-500">${{ totals.purchase.toFixed(2) }}</p>
      </div>
    </div>

    <!-- Chart -->
    <div v-if="chartData.labels.length" class="bg-white shadow rounded p-6 mb-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Monthly Financial Trends</h3>
      <div class="h-80">
        <BarChart :data="chartData" :options="chartOptions" />
      </div>
    </div>

    <div class="bg-white shadow rounded overflow-hidden">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Month</th>
            <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Income</th>
            <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Expenses</th>
            <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Purchases</th>
            <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Net</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <tr v-for="row in report.monthly" :key="row.month" class="hover:bg-gray-50">
            <td class="px-4 py-2 text-sm text-gray-900">{{ row.month }}</td>
            <td class="px-4 py-2 text-sm text-right">${{ row.summary.income.toFixed(2) }}</td>
            <td class="px-4 py-2 text-sm text-right">${{ row.summary.expense.toFixed(2) }}</td>
            <td class="px-4 py-2 text-sm text-right">${{ row.summary.purchase.toFixed(2) }}</td>
            <td
              class="px-4 py-2 text-sm text-right"
              :class="row.net >= 0 ? 'text-green-600' : 'text-red-600'"
            >
              ${{ row.net.toFixed(2) }}
            </td>
          </tr>
          <tr v-if="!report.monthly.length && !loading">
            <td class="px-4 py-6 text-center text-sm text-gray-500" colspan="5">No data found.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref, onMounted, computed } from 'vue'
import BarChart from '@/components/charts/BarChart.vue'
import financialService from '@/services/financial.service'
import { useToast } from '@/stores/toast'

const toast = useToast()
const loading = ref(false)
const report = reactive({
  summary: { income: 0, expense: 0, purchase: 0 },
  net: 0,
  monthly: [],
})
const totals = reactive({ income: 0, expense: 0, purchase: 0 })
const filters = reactive({
  start_date: '',
  end_date: '',
  category: '',
})

onMounted(() => {
  const today = new Date()
  filters.end_date = today.toISOString().slice(0, 10)
  const monthAgo = new Date()
  monthAgo.setMonth(monthAgo.getMonth() - 5)
  filters.start_date = monthAgo.toISOString().slice(0, 10)
  fetchReport()
})

function fetchReport() {
  if (!filters.start_date || !filters.end_date) {
    toast.error('Start and end date are required')
    return
  }
  loading.value = true
  financialService
    .report(filters)
    .then((res) => {
      report.summary = res.summary
      report.net = res.net
      report.monthly = res.monthly || []
      totals.income = res.summary.income || 0
      totals.expense = res.summary.expense || 0
      totals.purchase = res.summary.purchase || 0
    })
    .catch(() => toast.error('Failed to load report'))
    .finally(() => {
      loading.value = false
    })
}

function exportReport() {
  financialService
    .exportReport({ ...filters })
    .then((res) => {
      const blob = new Blob([res.data], { type: 'text/csv;charset=utf-8;' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.setAttribute('download', res.filename || 'financial-report.csv')
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    })
    .catch(() => toast.error('Failed to export report'))
}

// Chart data
const chartData = computed(() => {
  if (!report.monthly || report.monthly.length === 0) {
    return { labels: [], datasets: [] }
  }

  return {
    labels: report.monthly.map(row => row.month),
    datasets: [
      {
        label: 'Income',
        data: report.monthly.map(row => row.summary.income),
        backgroundColor: 'rgba(16, 185, 129, 0.8)',
      },
      {
        label: 'Expenses',
        data: report.monthly.map(row => row.summary.expense),
        backgroundColor: 'rgba(239, 68, 68, 0.8)',
      },
      {
        label: 'Purchases',
        data: report.monthly.map(row => row.summary.purchase),
        backgroundColor: 'rgba(249, 115, 22, 0.8)',
      }
    ]
  }
})

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: 'top',
    },
    tooltip: {
      callbacks: {
        label: function(context) {
          return context.dataset.label + ': $' + context.parsed.y.toLocaleString()
        }
      }
    }
  },
  scales: {
    y: {
      beginAtZero: true,
      ticks: {
        callback: function(value) {
          return '$' + value.toLocaleString()
        }
      }
    }
  }
}
</script>
