// src/react/views/invoices/InvoiceCreate.jsx
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'

import Alert from '../../components/ui/Alert'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import Loading from '../../components/ui/Loading'
import Select from '../../components/ui/Select'
import Textarea from '../../components/ui/Textarea'
import customerService from '../../../services/customer.service'
import invoiceService from '../../../services/invoice.service'
import { useToast } from '../../stores/toast.jsx'

const emptyLineItem = { description: '', quantity: 1, unit_price: 0 }

export default function InvoiceCreate() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const { success, error } = useToast()

  const [customers, setCustomers] = useState([])
  const [loadingCustomers, setLoadingCustomers] = useState(true)
  const [saving, setSaving] = useState(false)
  const [apiError, setApiError] = useState(null)

  const [formData, setFormData] = useState({
    customer_id: searchParams.get('customer') || '',
    issue_date: new Date().toISOString().split('T')[0],
    due_date: '',
    notes: '',
  })
  const [lineItems, setLineItems] = useState([{ ...emptyLineItem }])
  const [formErrors, setFormErrors] = useState({})

  const loadCustomers = useCallback(async () => {
    setLoadingCustomers(true)
    try {
      const data = await customerService.listCustomers({ limit: 100 })
      const customerList = Array.isArray(data) ? data : data?.data || []
      setCustomers(customerList)
    } catch {
      error('Failed to load customers')
    } finally {
      setLoadingCustomers(false)
    }
  }, [error])

  useEffect(() => {
    loadCustomers()
  }, [loadCustomers])

  const updateField = (field) => (value) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
    if (formErrors[field]) {
      setFormErrors((prev) => ({ ...prev, [field]: null }))
    }
  }

  const updateLineItem = (index, field, value) => {
    setLineItems((prev) => {
      const updated = [...prev]
      updated[index] = { ...updated[index], [field]: value }
      return updated
    })
  }

  const addLineItem = () => {
    setLineItems((prev) => [...prev, { ...emptyLineItem }])
  }

  const removeLineItem = (index) => {
    if (lineItems.length === 1) return
    setLineItems((prev) => prev.filter((_, i) => i !== index))
  }

  const calculateSubtotal = () => {
    return lineItems.reduce((sum, item) => {
      return sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.unit_price) || 0)
    }, 0)
  }

  const validate = () => {
    const errors = {}
    if (!formData.customer_id) {
      errors.customer_id = 'Please select a customer'
    }
    if (!formData.issue_date) {
      errors.issue_date = 'Issue date is required'
    }
    if (lineItems.length === 0 || lineItems.every((item) => !item.description.trim())) {
      errors.lineItems = 'At least one line item is required'
    }
    setFormErrors(errors)
    return Object.keys(errors).length === 0
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!validate()) return

    setSaving(true)
    setApiError(null)

    try {
      const validItems = lineItems.filter((item) => item.description.trim())
      await invoiceService.create({
        ...formData,
        items: validItems.map((item) => ({
          description: item.description,
          quantity: parseFloat(item.quantity) || 1,
          unit_price: parseFloat(item.unit_price) || 0,
        })),
      })
      success('Invoice created successfully')
      navigate('/cp/invoices')
    } catch (err) {
      setApiError(err.response?.data?.message || 'Failed to create invoice')
    } finally {
      setSaving(false)
    }
  }

  const customerOptions = customers.map((c) => ({
    value: c.id.toString(),
    label: c.name,
  }))

  if (loadingCustomers) {
    return (
      <div className="flex justify-center items-center min-h-96">
        <Loading text="Loading..." />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Link to="/cp/invoices" className="text-gray-500 hover:text-gray-700">
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Create Invoice</h1>
          <p className="mt-1 text-sm text-gray-500">Create a new invoice for a customer</p>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card className="lg:col-span-2">
            {apiError ? (
              <Alert variant="danger" className="mb-6" closable onClose={() => setApiError(null)}>
                {apiError}
              </Alert>
            ) : null}

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Customer *</label>
                <Select
                  value={formData.customer_id}
                  onChange={(e) => updateField('customer_id')(e.target.value)}
                  options={customerOptions}
                  placeholder="Select a customer..."
                />
                {formErrors.customer_id ? (
                  <p className="mt-1 text-sm text-red-600">{formErrors.customer_id}</p>
                ) : null}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <Input
                  label="Issue Date"
                  type="date"
                  value={formData.issue_date}
                  onUpdateModelValue={updateField('issue_date')}
                  error={formErrors.issue_date}
                  required
                />

                <Input
                  label="Due Date"
                  type="date"
                  value={formData.due_date}
                  onUpdateModelValue={updateField('due_date')}
                />
              </div>
            </div>

            <div className="mb-6">
              <div className="flex justify-between items-center mb-3">
                <h3 className="text-sm font-medium text-gray-900">Line Items</h3>
                <Button type="button" size="sm" variant="ghost" onClick={addLineItem}>
                  + Add Item
                </Button>
              </div>

              {formErrors.lineItems ? (
                <p className="mb-2 text-sm text-red-600">{formErrors.lineItems}</p>
              ) : null}

              <div className="space-y-3">
                {lineItems.map((item, index) => (
                  <div key={index} className="flex gap-3 items-start">
                    <div className="flex-1">
                      <Input
                        placeholder="Description"
                        value={item.description}
                        onUpdateModelValue={(value) => updateLineItem(index, 'description', value)}
                      />
                    </div>
                    <div className="w-20">
                      <Input
                        type="number"
                        placeholder="Qty"
                        value={item.quantity}
                        onUpdateModelValue={(value) => updateLineItem(index, 'quantity', value)}
                        min="1"
                      />
                    </div>
                    <div className="w-28">
                      <Input
                        type="number"
                        placeholder="Price"
                        value={item.unit_price}
                        onUpdateModelValue={(value) => updateLineItem(index, 'unit_price', value)}
                        min="0"
                        step="0.01"
                      />
                    </div>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="text-red-600 hover:text-red-700 mt-1"
                      onClick={() => removeLineItem(index)}
                      disabled={lineItems.length === 1}
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                    </Button>
                  </div>
                ))}
              </div>
            </div>

            <Textarea
              label="Notes"
              value={formData.notes}
              onUpdateModelValue={updateField('notes')}
              placeholder="Additional notes for the invoice..."
              rows={3}
            />
          </Card>

          <Card>
            <h3 className="text-lg font-medium text-gray-900 mb-4">Summary</h3>
            <dl className="space-y-3">
              <div className="flex justify-between">
                <dt className="text-sm text-gray-500">Subtotal</dt>
                <dd className="text-sm text-gray-900">
                  ${calculateSubtotal().toFixed(2)}
                </dd>
              </div>
              <div className="flex justify-between pt-3 border-t">
                <dt className="text-base font-medium text-gray-900">Total</dt>
                <dd className="text-base font-medium text-gray-900">
                  ${calculateSubtotal().toFixed(2)}
                </dd>
              </div>
            </dl>

            <div className="mt-6 space-y-3">
              <Button type="submit" fullWidth loading={saving}>
                Create Invoice
              </Button>
              <Button type="button" variant="ghost" fullWidth onClick={() => navigate('/cp/invoices')}>
                Cancel
              </Button>
            </div>
          </Card>
        </div>
      </form>
    </div>
  )
}

// src/views/invoices/InvoiceCreate.vue
<template>
  <div>
    <!-- Page Header -->
    <div class="mb-6">
      <div class="flex items-center gap-4 mb-2">
        <Button variant="ghost" @click="$router.push('/invoices')">
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
        </Button>
        <div>
          <h1 class="text-2xl font-bold text-gray-900">Create Invoice</h1>
          <p class="mt-1 text-sm text-gray-500">Create a new invoice for a customer</p>
        </div>
      </div>
    </div>

    <!-- Alert Messages -->
    <Alert v-if="successMessage" variant="success" class="mb-6">
      {{ successMessage }}
    </Alert>

    <Alert v-if="errorMessage" variant="danger" class="mb-6">
      {{ errorMessage }}
    </Alert>

    <!-- Invoice Form -->
    <form @submit.prevent="saveInvoice">
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Main Form -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Customer & Vehicle Info -->
          <Card title="Customer Information">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Select
                v-model="form.customer_id"
                :options="customers"
                label="Customer *"
                placeholder="Select customer"
                value-key="id"
                label-key="name"
                required
                @change="loadCustomerVehicles"
              />

              <Select
                v-model="form.vehicle_id"
                :options="vehicles"
                label="Vehicle"
                placeholder="Select vehicle"
                value-key="id"
                label-key="display_name"
                :disabled="!form.customer_id"
              />

              <Input
                v-model="form.invoice_date"
                type="date"
                label="Invoice Date *"
                required
              />

              <Input
                v-model="form.due_date"
                type="date"
                label="Due Date *"
                required
              />
            </div>
          </Card>

          <!-- Line Items -->
          <Card title="Line Items">
            <div class="space-y-4">
              <div
                v-for="(item, index) in form.line_items"
                :key="index"
                class="border border-gray-200 rounded-lg p-4"
              >
                <div class="grid grid-cols-12 gap-3">
                  <div class="col-span-12 md:col-span-5">
                    <Input
                      v-model="item.description"
                      label="Description"
                      placeholder="Service or part description"
                      required
                    />
                  </div>

                  <div class="col-span-4 md:col-span-2">
                    <Input
                      v-model.number="item.quantity"
                      type="number"
                      label="Quantity"
                      min="1"
                      step="1"
                      required
                      @input="calculateTotals"
                    />
                  </div>

                  <div class="col-span-4 md:col-span-2">
                    <Input
                      v-model.number="item.unit_price"
                      type="number"
                      label="Unit Price"
                      min="0"
                      step="0.01"
                      required
                      @input="calculateTotals"
                    />
                  </div>

                  <div class="col-span-3 md:col-span-2">
                    <label class="block text-sm font-medium text-gray-700 mb-1">
                      Amount
                    </label>
                    <div class="mt-1 text-sm font-semibold text-gray-900 py-2">
                      {{ formatCurrency(item.quantity * item.unit_price) }}
                    </div>
                  </div>

                  <div class="col-span-1 flex items-end">
                    <Button
                      variant="danger"
                      size="sm"
                      @click="removeLineItem(index)"
                      :disabled="form.line_items.length === 1"
                    >
                      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                      </svg>
                    </Button>
                  </div>
                </div>

                <div class="mt-3">
                  <Textarea
                    v-model="item.notes"
                    placeholder="Additional notes (optional)"
                    rows="2"
                  />
                </div>
              </div>

              <Button variant="outline" @click="addLineItem" class="w-full">
                <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
                </svg>
                Add Line Item
              </Button>
            </div>
          </Card>

          <!-- Additional Information -->
          <Card title="Additional Information">
            <div class="space-y-4">
              <Textarea
                v-model="form.notes"
                label="Notes"
                placeholder="Additional notes for the invoice..."
                rows="4"
              />

              <Textarea
                v-model="form.terms"
                label="Terms & Conditions"
                placeholder="Payment terms and conditions..."
                rows="3"
              />
            </div>
          </Card>
        </div>

        <!-- Summary Sidebar -->
        <div class="space-y-6">
          <!-- Calculations -->
          <Card title="Summary">
            <dl class="space-y-3">
              <div class="flex justify-between text-sm">
                <dt class="text-gray-600">Subtotal</dt>
                <dd class="font-medium text-gray-900">{{ formatCurrency(calculations.subtotal) }}</dd>
              </div>

              <div>
                <div class="flex justify-between text-sm mb-2">
                  <dt class="text-gray-600">Tax</dt>
                  <dd class="font-medium text-gray-900">{{ formatCurrency(calculations.tax) }}</dd>
                </div>
                <Input
                  v-model.number="form.tax_rate"
                  type="number"
                  placeholder="Tax rate %"
                  step="0.01"
                  min="0"
                  max="100"
                  @input="calculateTotals"
                />
              </div>

              <div>
                <div class="flex justify-between text-sm mb-2">
                  <dt class="text-gray-600">Discount</dt>
                  <dd class="font-medium text-gray-900">-{{ formatCurrency(calculations.discount) }}</dd>
                </div>
                <Input
                  v-model.number="form.discount_amount"
                  type="number"
                  placeholder="Discount amount"
                  step="0.01"
                  min="0"
                  @input="calculateTotals"
                />
              </div>

              <div class="pt-3 border-t border-gray-200 flex justify-between">
                <dt class="text-base font-semibold text-gray-900">Total</dt>
                <dd class="text-base font-semibold text-gray-900">
                  {{ formatCurrency(calculations.total) }}
                </dd>
              </div>
            </dl>
          </Card>

          <!-- Actions -->
          <Card title="Actions">
            <div class="space-y-3">
              <Select
                v-model="form.status"
                :options="statusOptions"
                label="Status"
              />

              <Button type="submit" class="w-full" :loading="saving">
                <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
                Create Invoice
              </Button>

              <Button
                variant="outline"
                class="w-full"
                @click="saveDraft"
                :loading="saving"
              >
                Save as Draft
              </Button>

              <Button
                variant="ghost"
                class="w-full"
                @click="$router.push('/invoices')"
              >
                Cancel
              </Button>
            </div>
          </Card>
        </div>
      </div>
    </form>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Select from '@/components/ui/Select.vue'
import Textarea from '@/components/ui/Textarea.vue'
import Alert from '@/components/ui/Alert.vue'
import invoiceService from '@/services/invoice.service'

const router = useRouter()

const saving = ref(false)
const successMessage = ref('')
const errorMessage = ref('')

const customers = ref([])
const vehicles = ref([])

const form = reactive({
  customer_id: '',
  vehicle_id: '',
  invoice_date: new Date().toISOString().split('T')[0],
  due_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  status: 'draft',
  tax_rate: 8.75,
  discount_amount: 0,
  notes: '',
  terms: '',
  line_items: [
    {
      description: '',
      quantity: 1,
      unit_price: 0,
      notes: '',
    },
  ],
})

const statusOptions = [
  { value: 'draft', label: 'Draft' },
  { value: 'pending', label: 'Pending' },
]

const calculations = computed(() => {
  const subtotal = form.line_items.reduce((sum, item) => {
    return sum + (item.quantity * item.unit_price)
  }, 0)

  const tax = subtotal * (form.tax_rate / 100)
  const discount = form.discount_amount || 0
  const total = subtotal + tax - discount

  return {
    subtotal,
    tax,
    discount,
    total,
  }
})

onMounted(async () => {
  await loadCustomers()
})

async function loadCustomers() {
  try {
    // In a real app, this would load from the API
    customers.value = []
  } catch (error) {
    console.error('Failed to load customers:', error)
  }
}

async function loadCustomerVehicles() {
  if (!form.customer_id) {
    vehicles.value = []
    form.vehicle_id = ''
    return
  }

  try {
    // In a real app, this would load vehicles for the selected customer
    vehicles.value = []
  } catch (error) {
    console.error('Failed to load vehicles:', error)
  }
}

function addLineItem() {
  form.line_items.push({
    description: '',
    quantity: 1,
    unit_price: 0,
    notes: '',
  })
}

function removeLineItem(index) {
  if (form.line_items.length > 1) {
    form.line_items.splice(index, 1)
    calculateTotals()
  }
}

function calculateTotals() {
  // Trigger reactivity
}

async function saveInvoice() {
  try {
    saving.value = true
    errorMessage.value = ''

    const invoiceData = {
      ...form,
      subtotal: calculations.value.subtotal,
      tax_amount: calculations.value.tax,
      discount_amount: calculations.value.discount,
      total_amount: calculations.value.total,
    }

    const response = await invoiceService.create(invoiceData)

    successMessage.value = 'Invoice created successfully!'

    // Redirect to invoice detail page after a short delay
    setTimeout(() => {
      router.push(`/invoices/${response.id}`)
    }, 1500)
  } catch (error) {
    console.error('Failed to create invoice:', error)
    errorMessage.value = error.response?.data?.message || 'Failed to create invoice. Please try again.'
  } finally {
    saving.value = false
  }
}

async function saveDraft() {
  form.status = 'draft'
  await saveInvoice()
}

function formatCurrency(amount) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount || 0)
}
</script>
