// old-views/src/views/estimates/EstimateDetail.vue
<template>
  <div>
    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center py-12">
      <Loading size="xl" text="Loading estimate..." />
    </div>

    <!-- Error State -->
    <Alert v-else-if="error" variant="danger" class="mb-6">
      {{ error }}
    </Alert>

    <!-- Estimate Details -->
    <div v-else-if="estimate">
      <!-- Header -->
      <div class="mb-6">
        <div class="flex items-center justify-between mb-2">
          <div class="flex items-center gap-4">
            <Button variant="ghost" @click="$router.back()">
              <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            </Button>
            <div>
              <h1 class="text-2xl font-bold text-gray-900">Estimate {{ estimate.number }}</h1>
              <p class="text-sm text-gray-500">Created {{ formatDate(estimate.created_at) }}</p>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <Badge v-if="estimate.is_mobile" variant="warning" size="lg">Mobile repair</Badge>
            <Badge :variant="getStatusVariant(estimate.status)" size="lg">
              {{ formatStatus(estimate.status) }}
            </Badge>
          </div>
        </div>

        <!-- Actions -->
        <div class="flex gap-2 mt-4">
          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="primary"
            @click="approveEstimate"
          >
            Approve
          </Button>
          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="danger"
            @click="declineEstimate"
          >
            Reject
          </Button>
          <Button
            v-if="estimate.status === 'approved'"
            @click="showConvertModal = true"
          >
            Convert to Invoice
          </Button>
          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="outline"
            @click="expireEstimate"
          >
            Mark as Expired
          </Button>
          <Button
            variant="outline"
            @click="$router.push(`/estimates/${estimate.id}/edit`)"
          >
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            Edit
          </Button>
        </div>
      </div>

      <!-- Main Content Grid -->
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Left Column - Estimate Details -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Customer & Vehicle Info -->
          <Card>
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Customer & Vehicle</h3>
            </template>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="text-sm font-medium text-gray-500">Customer</label>
                <p class="mt-1 text-sm text-gray-900">
                  <router-link
                    :to="`/customers/${estimate.customer_id}`"
                    class="text-primary-600 hover:text-primary-800"
                  >
                    Customer #{{ estimate.customer_id }}
                  </router-link>
                </p>
              </div>
              <div>
                <label class="text-sm font-medium text-gray-500">Vehicle</label>
                <p class="mt-1 text-sm text-gray-900">
                  <router-link
                    :to="`/vehicles/${estimate.vehicle_id}`"
                    class="text-primary-600 hover:text-primary-800"
                  >
                    Vehicle #{{ estimate.vehicle_id }}
                  </router-link>
                </p>
              </div>
              <div v-if="estimate.technician_id">
                <label class="text-sm font-medium text-gray-500">Technician</label>
                <p class="mt-1 text-sm text-gray-900">Technician #{{ estimate.technician_id }}</p>
              </div>
              <div v-if="estimate.expiration_date">
                <label class="text-sm font-medium text-gray-500">Expiration Date</label>
                <p
                  class="mt-1 text-sm"
                  :class="isExpired(estimate.expiration_date) ? 'text-red-600 font-medium' : 'text-gray-900'"
                >
                  {{ formatDate(estimate.expiration_date) }}
                  <span v-if="isExpired(estimate.expiration_date)" class="text-xs">(Expired)</span>
                  <span v-else-if="isExpiringSoon(estimate.expiration_date)" class="text-xs text-amber-600">(Expiring soon)</span>
                </p>
              </div>
            </div>
          </Card>

          <!-- Notes -->
          <Card v-if="estimate.customer_notes || estimate.internal_notes">
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Notes</h3>
            </template>
            <div class="space-y-4">
              <div v-if="estimate.customer_notes">
                <label class="text-sm font-medium text-gray-500">Customer Notes</label>
                <p class="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{{ estimate.customer_notes }}</p>
              </div>
              <div v-if="estimate.internal_notes">
                <label class="text-sm font-medium text-gray-500">Internal Notes</label>
                <p class="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{{ estimate.internal_notes }}</p>
              </div>
            </div>
          </Card>
        </div>

        <!-- Right Column - Financial Summary -->
        <div>
          <Card>
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Summary</h3>
            </template>
            <div class="space-y-3">
              <div class="flex justify-between">
                <span class="text-sm text-gray-600">Subtotal</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.subtotal) }}</span>
              </div>
              <div v-if="estimate.call_out_fee > 0" class="flex justify-between">
                <span class="text-sm text-gray-600">Call-out Fee</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.call_out_fee) }}</span>
              </div>
              <div v-if="estimate.mileage_total > 0" class="flex justify-between">
                <span class="text-sm text-gray-600">Mileage</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.mileage_total) }}</span>
              </div>
              <div v-if="estimate.discounts > 0" class="flex justify-between text-green-600">
                <span class="text-sm">Discounts</span>
                <span class="text-sm font-medium">-{{ formatCurrency(estimate.discounts) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-sm text-gray-600">Tax</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.tax) }}</span>
              </div>
              <div class="border-t border-gray-200 pt-3 flex justify-between">
                <span class="text-base font-medium text-gray-900">Grand Total</span>
                <span class="text-base font-bold text-gray-900">{{ formatCurrency(estimate.grand_total) }}</span>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>

    <!-- Convert to Invoice Modal -->
    <Modal v-if="showConvertModal" @close="showConvertModal = false">
      <template #title>Convert to Invoice</template>
      <template #content>
        <div class="space-y-4">
          <p class="text-sm text-gray-600">
            Convert estimate #{{ estimate?.number }} to an invoice?
          </p>
          <div>
            <label class="block text-sm font-medium text-gray-700">Issue Date *</label>
            <Input
              v-model="convertForm.issue_date"
              type="date"
              class="mt-1"
              required
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Due Date (Optional)</label>
            <Input
              v-model="convertForm.due_date"
              type="date"
              class="mt-1"
            />
          </div>
        </div>
      </template>
      <template #actions>
        <Button variant="outline" @click="showConvertModal = false">Cancel</Button>
        <Button @click="confirmConvert" :disabled="!convertForm.issue_date || converting">
          {{ converting ? 'Converting...' : 'Convert to Invoice' }}
        </Button>
      </template>
    </Modal>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import Badge from '@/components/ui/Badge.vue'
import Input from '@/components/ui/Input.vue'
import Alert from '@/components/ui/Alert.vue'
import Loading from '@/components/ui/Loading.vue'
import Modal from '@/components/ui/Modal.vue'
import estimateService from '@/services/estimate.service'
import { useToast } from '@/stores/toast'

const router = useRouter()
const route = useRoute()
const toast = useToast()

const loading = ref(true)
const converting = ref(false)
const error = ref(null)
const estimate = ref(null)
const showConvertModal = ref(false)

const convertForm = reactive({
  issue_date: new Date().toISOString().split('T')[0],
  due_date: ''
})

onMounted(() => {
  loadEstimate()
})

async function loadEstimate() {
  try {
    loading.value = true
    error.value = null
    const response = await estimateService.getEstimate(route.params.id)
    estimate.value = response.data
  } catch (err) {
    console.error('Failed to load estimate:', err)
    error.value = err.response?.data?.message || 'Failed to load estimate'
  } finally {
    loading.value = false
  }
}

async function approveEstimate() {
  try {
    await estimateService.approveEstimate(estimate.value.id)
    toast.success('Estimate approved successfully')
    loadEstimate()
  } catch (err) {
    console.error('Failed to approve estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to approve estimate')
  }
}

async function declineEstimate() {
  if (!confirm('Are you sure you want to reject this estimate?')) return

  try {
    await estimateService.declineEstimate(estimate.value.id)
    toast.success('Estimate rejected')
    loadEstimate()
  } catch (err) {
    console.error('Failed to reject estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to reject estimate')
  }
}

async function requestReapproval() {
  try {
    await estimateService.requestReapproval(estimate.value.id)
    toast.success('Reapproval requested')
    loadEstimate()
  } catch (err) {
    console.error('Failed to request reapproval:', err)
    toast.error(err.response?.data?.message || 'Failed to request reapproval')
  }
}

async function expireEstimate() {
  if (!confirm('Mark this estimate as expired?')) return

  try {
    await estimateService.expireEstimate(estimate.value.id)
    toast.success('Estimate marked as expired')
    loadEstimate()
  } catch (err) {
    console.error('Failed to expire estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to expire estimate')
  }
}

async function confirmConvert() {
  try {
    converting.value = true
    const response = await estimateService.convertToInvoice(estimate.value.id, {
      issue_date: convertForm.issue_date,
      due_date: convertForm.due_date || null
    })

    toast.success('Estimate converted to invoice successfully')
    showConvertModal.value = false

    // Redirect to the new invoice
    if (response.data?.id) {
      router.push(`/invoices/${response.data.id}`)
    }
  } catch (err) {
    console.error('Failed to convert estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to convert estimate')
  } finally {
    converting.value = false
  }
}

function getStatusVariant(status) {
  const variants = {
    sent: 'info',
    pending: 'default',
    approved: 'success',
    rejected: 'danger',
    expired: 'warning',
    converted: 'success'
  }
  return variants[status?.toLowerCase()] || 'default'
}

function formatStatus(status) {
  return status
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function formatCurrency(amount) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  }).format(amount || 0)
}

function formatDate(date) {
  if (!date) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  }).format(new Date(date))
}

function isExpired(expirationDate) {
  if (!expirationDate) return false
  return new Date(expirationDate) < new Date()
}

function isExpiringSoon(expirationDate) {
  if (!expirationDate) return false
  const expiry = new Date(expirationDate)
  const now = new Date()
  const daysUntilExpiry = (expiry - now) / (1000 * 60 * 60 * 24)
  return daysUntilExpiry > 0 && daysUntilExpiry <= 7
}
</script>

// src/react/views/estimates/EstimateDetail.jsx
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import Alert from '../../components/ui/Alert'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import Loading from '../../components/ui/Loading'
import Modal from '../../components/ui/Modal'
import estimateService from '../../../services/estimate.service'
import { useToast } from '../../stores/toast'

const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount || 0)
}

const formatDate = (date) => {
  if (!date) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date(date))
}

const formatStatus = (status) => {
  if (!status) return ''
  return status
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const getStatusVariant = (status) => {
  const variants = {
    sent: 'info',
    pending: 'default',
    approved: 'success',
    rejected: 'danger',
    expired: 'warning',
    converted: 'success',
  }
  return variants[status?.toLowerCase()] || 'default'
}

const isExpired = (expirationDate) => {
  if (!expirationDate) return false
  return new Date(expirationDate) < new Date()
}

const isExpiringSoon = (expirationDate) => {
  if (!expirationDate) return false
  const expiry = new Date(expirationDate)
  const now = new Date()
  const daysUntilExpiry = (expiry - now) / (1000 * 60 * 60 * 24)
  return daysUntilExpiry > 0 && daysUntilExpiry <= 7
}

export default function EstimateDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { success, error } = useToast()

  const [loading, setLoading] = useState(true)
  const [converting, setConverting] = useState(false)
  const [estimate, setEstimate] = useState(null)
  const [loadError, setLoadError] = useState(null)
  const [showConvertModal, setShowConvertModal] = useState(false)
  const [convertForm, setConvertForm] = useState({
    issue_date: new Date().toISOString().split('T')[0],
    due_date: '',
  })

  const loadEstimate = useCallback(async () => {
    if (!id) return
    setLoading(true)
    setLoadError(null)
    try {
      const response = await estimateService.getEstimate(id)
      setEstimate(response.data)
    } catch (fetchError) {
      console.error('Failed to load estimate:', fetchError)
      setLoadError(fetchError.response?.data?.message || 'Failed to load estimate')
    } finally {
      setLoading(false)
    }
  }, [id])

  useEffect(() => {
    loadEstimate()
  }, [loadEstimate])

  const approveEstimate = async () => {
    if (!estimate) return
    try {
      await estimateService.approveEstimate(estimate.id)
      success('Estimate approved successfully')
      loadEstimate()
    } catch (approveError) {
      console.error('Failed to approve estimate:', approveError)
      error(approveError.response?.data?.message || 'Failed to approve estimate')
    }
  }

  const declineEstimate = async () => {
    if (!estimate) return
    if (!window.confirm('Are you sure you want to reject this estimate?')) return

    try {
      await estimateService.declineEstimate(estimate.id)
      success('Estimate rejected')
      loadEstimate()
    } catch (declineError) {
      console.error('Failed to reject estimate:', declineError)
      error(declineError.response?.data?.message || 'Failed to reject estimate')
    }
  }

  const expireEstimate = async () => {
    if (!estimate) return
    if (!window.confirm('Mark this estimate as expired?')) return

    try {
      await estimateService.expireEstimate(estimate.id)
      success('Estimate marked as expired')
      loadEstimate()
    } catch (expireError) {
      console.error('Failed to expire estimate:', expireError)
      error(expireError.response?.data?.message || 'Failed to expire estimate')
    }
  }

  const confirmConvert = async () => {
    if (!estimate) return
    setConverting(true)
    try {
      const response = await estimateService.convertToInvoice(estimate.id, {
        issue_date: convertForm.issue_date,
        due_date: convertForm.due_date || null,
      })

      success('Estimate converted to invoice successfully')
      setShowConvertModal(false)

      if (response.data?.id) {
        navigate(`/cp/invoices/${response.data.id}`)
      }
    } catch (convertError) {
      console.error('Failed to convert estimate:', convertError)
      error(convertError.response?.data?.message || 'Failed to convert estimate')
    } finally {
      setConverting(false)
    }
  }

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Loading size="xl" text="Loading estimate..." />
      </div>
    )
  }

  if (loadError) {
    return (
      <Alert variant="danger" className="mb-6">
        {loadError}
      </Alert>
    )
  }

  if (!estimate) {
    return (
      <div className="text-center py-12">
        <h3 className="text-lg font-medium text-gray-900">Estimate not found</h3>
        <p className="mt-2 text-gray-500">The estimate you&apos;re looking for doesn&apos;t exist.</p>
        <div className="mt-4">
          <Link to="/cp/estimates">
            <Button>Back to Estimates</Button>
          </Link>
        </div>
      </div>
    )
  }

  const isPendingOrSent = ['pending', 'sent'].includes(estimate.status)

  return (
    <div>
      <div className="mb-6">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-4">
            <Button variant="ghost" onClick={() => navigate(-1)}>
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
              </svg>
            </Button>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Estimate {estimate.number}</h1>
              <p className="text-sm text-gray-500">Created {formatDate(estimate.created_at)}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {estimate.is_mobile ? (
              <Badge variant="warning" size="lg">Mobile repair</Badge>
            ) : null}
            <Badge variant={getStatusVariant(estimate.status)} size="lg">
              {formatStatus(estimate.status)}
            </Badge>
          </div>
        </div>

        <div className="flex flex-wrap gap-2 mt-4">
          {isPendingOrSent ? (
            <Button variant="primary" onClick={approveEstimate}>Approve</Button>
          ) : null}
          {isPendingOrSent ? (
            <Button variant="danger" onClick={declineEstimate}>Reject</Button>
          ) : null}
          {estimate.status === 'approved' ? (
            <Button onClick={() => setShowConvertModal(true)}>Convert to Invoice</Button>
          ) : null}
          {isPendingOrSent ? (
            <Button variant="outline" onClick={expireEstimate}>Mark as Expired</Button>
          ) : null}
          <Button
            variant="outline"
            onClick={() => navigate(`/cp/estimates/${estimate.id}/edit`)}
          >
            <svg className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            Edit
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-900">Customer & Vehicle</h3>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium text-gray-500">Customer</label>
                <p className="mt-1 text-sm text-gray-900">
                  <Link
                    to={`/cp/customers/${estimate.customer_id}`}
                    className="text-primary-600 hover:text-primary-800"
                  >
                    Customer #{estimate.customer_id}
                  </Link>
                </p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-500">Vehicle</label>
                <p className="mt-1 text-sm text-gray-900">
                  <Link
                    to={`/cp/vehicles/${estimate.vehicle_id}`}
                    className="text-primary-600 hover:text-primary-800"
                  >
                    Vehicle #{estimate.vehicle_id}
                  </Link>
                </p>
              </div>
              {estimate.technician_id ? (
                <div>
                  <label className="text-sm font-medium text-gray-500">Technician</label>
                  <p className="mt-1 text-sm text-gray-900">Technician #{estimate.technician_id}</p>
                </div>
              ) : null}
              {estimate.expiration_date ? (
                <div>
                  <label className="text-sm font-medium text-gray-500">Expiration Date</label>
                  <p
                    className={`mt-1 text-sm ${isExpired(estimate.expiration_date) ? 'text-red-600 font-medium' : 'text-gray-900'}`}
                  >
                    {formatDate(estimate.expiration_date)}
                    {isExpired(estimate.expiration_date) ? (
                      <span className="text-xs"> (Expired)</span>
                    ) : null}
                    {!isExpired(estimate.expiration_date) && isExpiringSoon(estimate.expiration_date) ? (
                      <span className="text-xs text-amber-600"> (Expiring soon)</span>
                    ) : null}
                  </p>
                </div>
              ) : null}
            </div>
          </Card>

          {(estimate.customer_notes || estimate.internal_notes) ? (
            <Card>
              <div className="mb-4">
                <h3 className="text-lg font-medium text-gray-900">Notes</h3>
              </div>
              <div className="space-y-4">
                {estimate.customer_notes ? (
                  <div>
                    <label className="text-sm font-medium text-gray-500">Customer Notes</label>
                    <p className="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{estimate.customer_notes}</p>
                  </div>
                ) : null}
                {estimate.internal_notes ? (
                  <div>
                    <label className="text-sm font-medium text-gray-500">Internal Notes</label>
                    <p className="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{estimate.internal_notes}</p>
                  </div>
                ) : null}
              </div>
            </Card>
          ) : null}
        </div>

        <div>
          <Card>
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-900">Summary</h3>
            </div>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Subtotal</span>
                <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.subtotal)}</span>
              </div>
              {estimate.call_out_fee > 0 ? (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Call-out Fee</span>
                  <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.call_out_fee)}</span>
                </div>
              ) : null}
              {estimate.mileage_total > 0 ? (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Mileage</span>
                  <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.mileage_total)}</span>
                </div>
              ) : null}
              {estimate.discounts > 0 ? (
                <div className="flex justify-between text-green-600">
                  <span className="text-sm">Discounts</span>
                  <span className="text-sm font-medium">-{formatCurrency(estimate.discounts)}</span>
                </div>
              ) : null}
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Tax</span>
                <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.tax)}</span>
              </div>
              <div className="border-t border-gray-200 pt-3 flex justify-between">
                <span className="text-base font-medium text-gray-900">Grand Total</span>
                <span className="text-base font-bold text-gray-900">{formatCurrency(estimate.grand_total)}</span>
              </div>
            </div>
          </Card>
        </div>
      </div>

      <Modal
        open={showConvertModal}
        onClose={() => setShowConvertModal(false)}
        title="Convert to Invoice"
        content={(
          <div className="space-y-4">
            <p className="text-sm text-gray-600">
              Convert estimate #{estimate?.number} to an invoice?
            </p>
            <div>
              <label className="block text-sm font-medium text-gray-700">Issue Date *</label>
              <Input
                value={convertForm.issue_date}
                type="date"
                className="mt-1"
                required
                onUpdateModelValue={(value) => setConvertForm((prev) => ({ ...prev, issue_date: value }))}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Due Date (Optional)</label>
              <Input
                value={convertForm.due_date}
                type="date"
                className="mt-1"
                onUpdateModelValue={(value) => setConvertForm((prev) => ({ ...prev, due_date: value }))}
              />
            </div>
          </div>
        )}
        footer={(
          <div className="flex gap-3 justify-end">
            <Button variant="outline" onClick={() => setShowConvertModal(false)}>Cancel</Button>
            <Button
              onClick={confirmConvert}
              disabled={!convertForm.issue_date || converting}
              loading={converting}
            >
              {converting ? 'Converting...' : 'Convert to Invoice'}
            </Button>
          </div>
        )}
      />
    </div>
  )
}
