// old-views/src/views/customer-portal/Inspections.vue
<template>
  <div class="p-6 space-y-4">
    <h1 class="text-2xl font-semibold">My Inspections</h1>
    <p class="text-sm text-gray-600">View inspections shared with your account.</p>

    <div class="bg-white rounded shadow">
      <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
          <tr>
            <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">ID</th>
            <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Template</th>
            <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Status</th>
            <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Completed</th>
            <th class="px-4 py-2 text-left text-sm font-semibold text-gray-700">Actions</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <tr v-for="inspection in inspections" :key="inspection.id">
            <td class="px-4 py-2">{{ inspection.id }}</td>
            <td class="px-4 py-2">{{ inspection.template_id }}</td>
            <td class="px-4 py-2">{{ inspection.status }}</td>
            <td class="px-4 py-2">{{ inspection.completed_at || 'Pending' }}</td>
            <td class="px-4 py-2">
              <button class="text-indigo-600" @click="openDetail(inspection.id)">View</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="activeReport" class="p-4 bg-white rounded shadow">
      <div class="flex items-center justify-between">
        <h2 class="text-lg font-semibold">Inspection #{{ activeReport.report.id }}</h2>
        <button class="text-sm text-gray-600" @click="activeReport = null">Close</button>
      </div>
      <p class="text-sm text-gray-600">Status: {{ activeReport.report.status }}</p>
      <div class="mt-2 space-y-2">
        <div v-for="item in activeReport.items" :key="item.id" class="p-2 border rounded">
          <p class="font-semibold">{{ item.label }}</p>
          <p class="text-sm">Response: {{ item.response }}</p>
          <p class="text-sm text-gray-600" v-if="item.note">Note: {{ item.note }}</p>
        </div>
      </div>
      <div class="mt-3">
        <p class="font-semibold">Media</p>
        <ul class="list-disc pl-5 text-sm">
          <li v-for="media in activeReport.media" :key="media.id">
            <a :href="media.path" class="text-indigo-600" target="_blank">{{ media.type }} - {{ media.path }}</a>
          </li>
        </ul>
      </div>
    </div>

    <p v-if="error" class="text-sm text-red-600">{{ error }}</p>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import inspectionService from '@/services/inspection.service'

const inspections = ref([])
const activeReport = ref(null)
const error = ref('')

const loadInspections = async () => {
  try {
    inspections.value = await inspectionService.customerList()
  } catch (err) {
    console.error(err)
    error.value = 'Unable to load inspections'
  }
}

const openDetail = async (id) => {
  try {
    activeReport.value = await inspectionService.customerShow(id)
  } catch (err) {
    console.error(err)
    error.value = err.response?.data?.message || 'Unable to load inspection'
  }
}

onMounted(loadInspections)
</script>

// src/react/views/customer-portal/Inspections.jsx
import { useCallback, useEffect, useState } from 'react'

import inspectionService from '../../../services/inspection.service'

export default function Inspections() {
  const [inspections, setInspections] = useState([])
  const [activeReport, setActiveReport] = useState(null)
  const [error, setError] = useState('')

  const loadInspections = useCallback(async () => {
    try {
      const response = await inspectionService.customerList()
      setInspections(response || [])
    } catch (err) {
      console.error(err)
      setError('Unable to load inspections')
    }
  }, [])

  const openDetail = useCallback(async (id) => {
    try {
      const response = await inspectionService.customerShow(id)
      setActiveReport(response)
    } catch (err) {
      console.error(err)
      setError(err.response?.data?.message || 'Unable to load inspection')
    }
  }, [])

  useEffect(() => {
    loadInspections()
  }, [loadInspections])

  return (
    <div className="p-6 space-y-4">
      <h1 className="text-2xl font-semibold">My Inspections</h1>
      <p className="text-sm text-gray-600">View inspections shared with your account.</p>

      <div className="bg-white rounded shadow">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">ID</th>
              <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Template</th>
              <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Status</th>
              <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Completed</th>
              <th className="px-4 py-2 text-left text-sm font-semibold text-gray-700">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {inspections.map((inspection) => (
              <tr key={inspection.id}>
                <td className="px-4 py-2">{inspection.id}</td>
                <td className="px-4 py-2">{inspection.template_id}</td>
                <td className="px-4 py-2">{inspection.status}</td>
                <td className="px-4 py-2">{inspection.completed_at || 'Pending'}</td>
                <td className="px-4 py-2">
                  <button className="text-indigo-600" type="button" onClick={() => openDetail(inspection.id)}>
                    View
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {activeReport ? (
        <div className="p-4 bg-white rounded shadow">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold">Inspection #{activeReport.report.id}</h2>
            <button className="text-sm text-gray-600" type="button" onClick={() => setActiveReport(null)}>
              Close
            </button>
          </div>
          <p className="text-sm text-gray-600">Status: {activeReport.report.status}</p>
          <div className="mt-2 space-y-2">
            {activeReport.items.map((item) => (
              <div key={item.id} className="p-2 border rounded">
                <p className="font-semibold">{item.label}</p>
                <p className="text-sm">Response: {item.response}</p>
                {item.note ? <p className="text-sm text-gray-600">Note: {item.note}</p> : null}
              </div>
            ))}
          </div>
          <div className="mt-3">
            <p className="font-semibold">Media</p>
            <ul className="list-disc pl-5 text-sm">
              {activeReport.media.map((media) => (
                <li key={media.id}>
                  <a href={media.path} className="text-indigo-600" target="_blank" rel="noreferrer">
                    {media.type} - {media.path}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      ) : null}

      {error ? <p className="text-sm text-red-600">{error}</p> : null}
    </div>
  )
}
