// src/react/components/ui/Card.jsx
export default function Card({
  title = '',
  padding = true,
  shadow = 'md',
  hover = false,
  header = null,
  footer = null,
  className = '',
  children,
  ...rest
}) {
  const shadowClasses = {
    none: '',
    sm: 'shadow-sm',
    md: 'shadow-md',
    lg: 'shadow-lg',
    xl: 'shadow-xl',
  }

  const cardClasses = [
    'bg-white rounded-lg overflow-hidden',
    shadowClasses[shadow],
    hover ? 'transition-shadow hover:shadow-lg cursor-pointer' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  const bodyClasses = padding ? 'p-6' : ''

  const shouldRenderHeader = Boolean(title || header)

  return (
    <div className={cardClasses} {...rest}>
      {shouldRenderHeader ? (
        <div className="px-6 py-4 border-b border-gray-200">
          {header ?? <h3 className="text-lg font-medium text-gray-900">{title}</h3>}
        </div>
      ) : null}

      <div className={bodyClasses}>{children}</div>

      {footer ? (
        <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">{footer}</div>
      ) : null}
    </div>
  )
}

// old-views/src/components/ui/Card.vue
<template>
  <div :class="cardClasses">
    <!-- Header -->
    <div v-if="title || $slots.header" class="px-6 py-4 border-b border-gray-200">
      <slot name="header">
        <h3 class="text-lg font-medium text-gray-900">{{ title }}</h3>
      </slot>
    </div>

    <!-- Body -->
    <div :class="bodyClasses">
      <slot />
    </div>

    <!-- Footer -->
    <div v-if="$slots.footer" class="px-6 py-4 bg-gray-50 border-t border-gray-200">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  title: {
    type: String,
    default: '',
  },
  padding: {
    type: Boolean,
    default: true,
  },
  shadow: {
    type: String,
    default: 'md',
    validator: (value) => ['none', 'sm', 'md', 'lg', 'xl'].includes(value),
  },
  hover: {
    type: Boolean,
    default: false,
  },
})

const cardClasses = computed(() => {
  const classes = ['bg-white rounded-lg overflow-hidden']

  // Shadow
  const shadowClasses = {
    none: '',
    sm: 'shadow-sm',
    md: 'shadow-md',
    lg: 'shadow-lg',
    xl: 'shadow-xl',
  }
  classes.push(shadowClasses[props.shadow])

  // Hover effect
  if (props.hover) {
    classes.push('transition-shadow hover:shadow-lg cursor-pointer')
  }

  return classes.join(' ')
})

const bodyClasses = computed(() => {
  return props.padding ? 'p-6' : ''
})
</script>
