// src/views/invoices/InvoiceDetail.vue
<template>
  <div>
    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center py-12">
      <Loading size="xl" text="Loading invoice..." />
    </div>

    <!-- Error State -->
    <Alert v-else-if="error" variant="danger" class="mb-6">
      {{ error }}
      <div class="mt-4">
        <Button variant="outline" @click="$router.push('/cp/invoices')">
          Back to Invoices
        </Button>
      </div>
    </Alert>

    <!-- Invoice Detail -->
    <div v-else>
      <!-- Header -->
      <div class="mb-6 flex items-center justify-between">
        <div class="flex items-center gap-4">
          <Button variant="ghost" @click="$router.push('/cp/invoices')">
            <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </Button>
          <div>
            <h1 class="text-2xl font-bold text-gray-900">Invoice #{{ invoice.invoice_number }}</h1>
            <div class="mt-1 flex items-center gap-2">
              <Badge v-if="invoice.is_mobile" variant="warning">Mobile repair</Badge>
              <Badge :variant="getStatusVariant(invoice.status)">
                {{ invoice.status }}
              </Badge>
              <span class="text-sm text-gray-500">
                Created {{ formatDate(invoice.created_at) }}
              </span>
            </div>
          </div>
        </div>

        <div class="flex items-center gap-2">
          <Button variant="outline" @click="downloadPdf">
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </Button>

          <Button v-if="invoice.status === 'draft'" @click="sendInvoice">
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            Send Invoice
          </Button>

          <Button v-if="invoice.status === 'pending'" variant="primary" @click="recordPayment">
            Record Payment
          </Button>

          <Button variant="outline" @click="editInvoice">
            Edit
          </Button>
        </div>
      </div>

      <!-- Success/Error Messages -->
      <Alert v-if="successMessage" variant="success" class="mb-6" @close="successMessage = ''">
        {{ successMessage }}
      </Alert>

      <Alert v-if="errorMessage" variant="danger" class="mb-6" @close="errorMessage = ''">
        {{ errorMessage }}
      </Alert>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Main Content -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Invoice Details -->
          <Card title="Invoice Information">
            <div class="grid grid-cols-2 gap-6">
              <!-- Customer Info -->
              <div>
                <h3 class="text-sm font-medium text-gray-500 mb-2">Bill To</h3>
                <div class="text-sm">
                  <p class="font-medium text-gray-900">{{ invoice.customer?.name }}</p>
                  <p class="text-gray-600">{{ invoice.customer?.email }}</p>
                  <p class="text-gray-600">{{ invoice.customer?.phone }}</p>
                  <p class="text-gray-600 mt-1">
                    {{ invoice.customer?.address }}<br>
                    {{ invoice.customer?.city }}, {{ invoice.customer?.state }} {{ invoice.customer?.zip_code }}
                  </p>
                </div>
              </div>

              <!-- Invoice Info -->
              <div>
                <div class="space-y-3">
                  <div>
                    <div class="text-sm font-medium text-gray-500">Invoice Number</div>
                    <div class="text-sm text-gray-900">#{{ invoice.invoice_number }}</div>
                  </div>
                  <div>
                    <div class="text-sm font-medium text-gray-500">Invoice Date</div>
                    <div class="text-sm text-gray-900">{{ formatDate(invoice.invoice_date) }}</div>
                  </div>
                  <div>
                    <div class="text-sm font-medium text-gray-500">Due Date</div>
                    <div class="text-sm" :class="{ 'text-red-600 font-medium': isOverdue }">
                      {{ formatDate(invoice.due_date) }}
                      <span v-if="isOverdue" class="text-xs">(Overdue)</span>
                    </div>
                  </div>
                  <div v-if="invoice.vehicle">
                    <div class="text-sm font-medium text-gray-500">Vehicle</div>
                    <div class="text-sm text-gray-900">
                      {{ invoice.vehicle.year }} {{ invoice.vehicle.make }} {{ invoice.vehicle.model }}
                    </div>
                    <div class="text-xs text-gray-500">{{ invoice.vehicle.vin }}</div>
                  </div>
                </div>
              </div>
            </div>
          </Card>

          <!-- Line Items -->
          <Card title="Line Items">
            <div class="overflow-hidden">
              <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="py-3 pl-4 pr-3 text-left text-sm font-semibold text-gray-900">Description</th>
                    <th scope="col" class="px-3 py-3 text-right text-sm font-semibold text-gray-900">Qty</th>
                    <th scope="col" class="px-3 py-3 text-right text-sm font-semibold text-gray-900">Rate</th>
                    <th scope="col" class="px-3 py-3 text-right text-sm font-semibold text-gray-900">Amount</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                  <tr v-for="item in invoice.line_items" :key="item.id">
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm">
                      <div class="font-medium text-gray-900">{{ item.description }}</div>
                      <div v-if="item.notes" class="text-gray-500 text-xs mt-1">{{ item.notes }}</div>
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900 text-right">{{ item.quantity }}</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-900 text-right">{{ formatCurrency(item.unit_price) }}</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-900 text-right">
                      {{ formatCurrency(item.quantity * item.unit_price) }}
                    </td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="3" class="py-3 pl-4 pr-3 text-right text-sm font-medium text-gray-900">Subtotal</td>
                    <td class="px-3 py-3 text-sm font-medium text-gray-900 text-right">{{ formatCurrency(invoice.subtotal) }}</td>
                  </tr>
                  <tr v-if="invoice.tax_amount > 0">
                    <td colspan="3" class="py-3 pl-4 pr-3 text-right text-sm font-medium text-gray-900">Tax</td>
                    <td class="px-3 py-3 text-sm font-medium text-gray-900 text-right">{{ formatCurrency(invoice.tax_amount) }}</td>
                  </tr>
                  <tr v-if="invoice.discount_amount > 0">
                    <td colspan="3" class="py-3 pl-4 pr-3 text-right text-sm font-medium text-gray-900">Discount</td>
                    <td class="px-3 py-3 text-sm font-medium text-gray-900 text-right">-{{ formatCurrency(invoice.discount_amount) }}</td>
                  </tr>
                  <tr class="bg-gray-50">
                    <td colspan="3" class="py-3 pl-4 pr-3 text-right text-base font-semibold text-gray-900">Total</td>
                    <td class="px-3 py-3 text-base font-semibold text-gray-900 text-right">{{ formatCurrency(invoice.total_amount) }}</td>
                  </tr>
                </tfoot>
              </table>
            </div>

            <div v-if="invoice.notes" class="mt-4 pt-4 border-t border-gray-200">
              <h4 class="text-sm font-medium text-gray-900 mb-2">Notes</h4>
              <p class="text-sm text-gray-600 whitespace-pre-wrap">{{ invoice.notes }}</p>
            </div>
          </Card>

          <!-- Payment History -->
          <Card v-if="invoice.payments && invoice.payments.length > 0" title="Payment History">
            <div class="divide-y divide-gray-200">
              <div
                v-for="payment in invoice.payments"
                :key="payment.id"
                class="py-4 flex items-center justify-between"
              >
                <div>
                  <div class="flex items-center gap-3">
                    <Badge :variant="payment.status === 'completed' ? 'success' : 'warning'">
                      {{ payment.status }}
                    </Badge>
                    <span class="text-sm font-medium text-gray-900">
                      {{ payment.payment_method }}
                    </span>
                  </div>
                  <p class="mt-1 text-sm text-gray-500">
                    {{ formatDate(payment.payment_date) }}
                    <span v-if="payment.transaction_id" class="ml-2">
                      Transaction: {{ payment.transaction_id }}
                    </span>
                  </p>
                </div>
                <div class="text-right">
                  <div class="text-sm font-semibold text-gray-900">
                    {{ formatCurrency(payment.amount) }}
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- Payment Summary -->
          <Card title="Payment Summary">
            <dl class="space-y-3">
              <div class="flex justify-between text-sm">
                <dt class="text-gray-500">Total Amount</dt>
                <dd class="font-medium text-gray-900">{{ formatCurrency(invoice.total_amount) }}</dd>
              </div>
              <div class="flex justify-between text-sm">
                <dt class="text-gray-500">Amount Paid</dt>
                <dd class="font-medium text-green-600">{{ formatCurrency(invoice.paid_amount || 0) }}</dd>
              </div>
              <div class="pt-3 border-t border-gray-200 flex justify-between">
                <dt class="text-base font-semibold text-gray-900">Balance Due</dt>
                <dd class="text-base font-semibold text-gray-900">
                  {{ formatCurrency((invoice.total_amount || 0) - (invoice.paid_amount || 0)) }}
                </dd>
              </div>
            </dl>

            <div v-if="invoice.status === 'pending'" class="mt-4 pt-4 border-t border-gray-200">
              <Button class="w-full" @click="processPayment">
                Process Payment
              </Button>
            </div>
          </Card>

          <!-- Activity Log -->
          <Card v-if="invoice.activity_log && invoice.activity_log.length > 0" title="Activity Log">
            <div class="flow-root">
              <ul class="-mb-8">
                <li v-for="(activity, idx) in invoice.activity_log" :key="activity.id">
                  <div class="relative pb-8">
                    <span
                      v-if="idx !== invoice.activity_log.length - 1"
                      class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200"
                      aria-hidden="true"
                    ></span>
                    <div class="relative flex space-x-3">
                      <div>
                        <span class="h-8 w-8 rounded-full bg-gray-100 flex items-center justify-center ring-8 ring-white">
                          <svg class="h-5 w-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd" />
                          </svg>
                        </span>
                      </div>
                      <div class="flex min-w-0 flex-1 justify-between space-x-4 pt-1.5">
                        <div>
                          <p class="text-sm text-gray-900">{{ activity.description }}</p>
                          <p class="text-xs text-gray-500">{{ activity.user }}</p>
                        </div>
                        <div class="whitespace-nowrap text-right text-xs text-gray-500">
                          {{ formatDate(activity.created_at) }}
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </Card>
        </div>
      </div>
    </div>

    <!-- Payment Modal -->
    <Modal
      v-model="showPaymentModal"
      title="Record Payment"
      size="md"
    >
      <div class="space-y-4">
        <Input
          v-model="paymentForm.amount"
          type="number"
          label="Amount"
          placeholder="0.00"
          step="0.01"
          required
        />

        <Select
          v-model="paymentForm.payment_method"
          :options="paymentMethods"
          label="Payment Method"
          required
        />

        <Input
          v-model="paymentForm.transaction_id"
          label="Transaction ID"
          placeholder="Optional"
        />

        <Input
          v-model="paymentForm.payment_date"
          type="date"
          label="Payment Date"
          required
        />

        <Textarea
          v-model="paymentForm.notes"
          label="Notes"
          placeholder="Optional notes..."
          rows="3"
        />
      </div>

      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="outline" @click="showPaymentModal = false">
            Cancel
          </Button>
          <Button @click="submitPayment" :loading="processingPayment">
            Record Payment
          </Button>
        </div>
      </template>
    </Modal>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Select from '@/components/ui/Select.vue'
import Textarea from '@/components/ui/Textarea.vue'
import Badge from '@/components/ui/Badge.vue'
import Alert from '@/components/ui/Alert.vue'
import Loading from '@/components/ui/Loading.vue'
import Modal from '@/components/ui/Modal.vue'
import invoiceService from '@/services/invoice.service'

const route = useRoute()
const router = useRouter()

const loading = ref(true)
const error = ref(null)
const invoice = ref({})
const successMessage = ref('')
const errorMessage = ref('')

const showPaymentModal = ref(false)
const processingPayment = ref(false)
const paymentForm = ref({
  amount: '',
  payment_method: 'cash',
  transaction_id: '',
  payment_date: new Date().toISOString().split('T')[0],
  notes: '',
})

const paymentMethods = [
  { value: 'cash', label: 'Cash' },
  { value: 'check', label: 'Check' },
  { value: 'card', label: 'Credit/Debit Card' },
  { value: 'stripe', label: 'Stripe' },
  { value: 'square', label: 'Square' },
  { value: 'paypal', label: 'PayPal' },
]

const isOverdue = computed(() => {
  if (invoice.value.status === 'paid' || !invoice.value.due_date) return false
  return new Date(invoice.value.due_date) < new Date()
})

onMounted(async () => {
  await loadInvoice()
})

async function loadInvoice() {
  try {
    loading.value = true
    error.value = null

    const id = route.params.id
    const response = await invoiceService.getById(id)
    invoice.value = response.data || response
  } catch (err) {
    console.error('Failed to load invoice:', err)
    error.value = 'Failed to load invoice. Please try again.'
  } finally {
    loading.value = false
  }
}

async function downloadPdf() {
  try {
    const blob = await invoiceService.generatePdf(invoice.value.id)
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `invoice-${invoice.value.invoice_number}.pdf`
    link.click()
    window.URL.revokeObjectURL(url)
  } catch (err) {
    console.error('Failed to download PDF:', err)
    errorMessage.value = 'Failed to download PDF. Please try again.'
  }
}

async function sendInvoice() {
  try {
    await invoiceService.send(invoice.value.id)
    successMessage.value = 'Invoice sent successfully.'
    await loadInvoice()
  } catch (err) {
    console.error('Failed to send invoice:', err)
    errorMessage.value = 'Failed to send invoice. Please try again.'
  }
}

function editInvoice() {
  router.push(`/invoices/${invoice.value.id}/edit`)
}

function recordPayment() {
  paymentForm.value.amount = (invoice.value.total_amount || 0) - (invoice.value.paid_amount || 0)
  showPaymentModal.value = true
}

function processPayment() {
  // This would open a payment processing modal
  router.push(`/invoices/${invoice.value.id}/pay`)
}

async function submitPayment() {
  try {
    processingPayment.value = true
    await invoiceService.processPayment(invoice.value.id, paymentForm.value)
    successMessage.value = 'Payment recorded successfully.'
    showPaymentModal.value = false
    await loadInvoice()
  } catch (err) {
    console.error('Failed to record payment:', err)
    errorMessage.value = 'Failed to record payment. Please try again.'
  } finally {
    processingPayment.value = false
  }
}

function formatCurrency(amount) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount || 0)
}

function formatDate(date) {
  if (!date) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date(date))
}

function getStatusVariant(status) {
  const variants = {
    'paid': 'success',
    'pending': 'warning',
    'overdue': 'danger',
    'draft': 'default',
    'cancelled': 'default',
  }
  return variants[status?.toLowerCase()] || 'default'
}
</script>

// src/react/views/invoices/InvoiceDetail.jsx
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Loading from '../../components/ui/Loading'
import Modal from '../../components/ui/Modal'
import invoiceService from '../../../services/invoice.service'
import { useToast } from '../../stores/toast.jsx'

const formatCurrency = (value) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(value || 0)
}

const formatDate = (date) => {
  if (!date) return '—'
  return new Date(date).toLocaleDateString()
}

const formatDateTime = (date) => {
  if (!date) return '—'
  return new Date(date).toLocaleString()
}

const formatAddress = (customer) => {
  if (!customer) return '—'
  const line1 = customer.street
  const cityState = [customer.city, customer.state].filter(Boolean).join(', ')
  const line2 = [cityState, customer.postal_code].filter(Boolean).join(' ')
  const parts = [line1, line2, customer.country].filter(Boolean)
  return parts.length ? parts.join('\n') : '—'
}

const formatVehicle = (vehicle) => {
  if (!vehicle) return '—'
  const parts = [vehicle.year, vehicle.make, vehicle.model, vehicle.trim].filter(Boolean)
  return parts.length ? parts.join(' ') : '—'
}

const statusVariant = (status) => {
  switch (status) {
    case 'paid':
      return 'success'
    case 'sent':
      return 'info'
    case 'pending':
    case 'draft':
      return 'warning'
    case 'overdue':
    case 'cancelled':
      return 'danger'
    default:
      return 'default'
  }
}

export default function InvoiceDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { success, error } = useToast()

  const [invoice, setInvoice] = useState(null)
  const [loading, setLoading] = useState(true)
  const [sendModal, setSendModal] = useState(false)
  const [sending, setSending] = useState(false)
  const [deleteModal, setDeleteModal] = useState(false)
  const [deleting, setDeleting] = useState(false)

  const loadInvoice = useCallback(async () => {
    setLoading(true)
    try {
      const data = await invoiceService.getById(id)
      setInvoice(data)
    } catch {
      error('Failed to load invoice')
      navigate('/cp/invoices')
    } finally {
      setLoading(false)
    }
  }, [id, error, navigate])

  useEffect(() => {
    loadInvoice()
  }, [loadInvoice])

  const handleSend = async () => {
    setSending(true)
    try {
      await invoiceService.send(id)
      success('Invoice sent successfully')
      setSendModal(false)
      loadInvoice()
    } catch {
      error('Failed to send invoice')
    } finally {
      setSending(false)
    }
  }

  const handleDownloadPdf = async () => {
    try {
      const blob = await invoiceService.generatePdf(id)
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `invoice-${invoice.number}.pdf`
      link.click()
      window.URL.revokeObjectURL(url)
    } catch {
      error('Failed to download PDF')
    }
  }

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await invoiceService.delete(id)
      success('Invoice deleted successfully')
      navigate('/cp/invoices')
    } catch {
      error('Failed to delete invoice')
    } finally {
      setDeleting(false)
    }
  }

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-96">
        <Loading text="Loading invoice..." />
      </div>
    )
  }

  if (!invoice) {
    return (
      <div className="text-center py-12">
        <h3 className="text-lg font-medium text-gray-900">Invoice not found</h3>
        <p className="mt-2 text-gray-500">The invoice you&apos;re looking for doesn&apos;t exist.</p>
        <div className="mt-4">
          <Link to="/cp/invoices">
            <Button>Back to Invoices</Button>
          </Link>
        </div>
      </div>
    )
  }

  const lineItems = invoice.items || invoice.line_items || []
  const payments = invoice.payments || []
  const customer = invoice.customer || null
  const vehicle = invoice.vehicle || null
  const serviceType = invoice.service_type || null

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-4">
          <Link to="/cp/invoices" className="text-gray-500 hover:text-gray-700">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Invoice {invoice.number}</h1>
            <p className="mt-1 text-sm text-gray-500">
              {invoice.customer?.name || 'Unknown Customer'}
            </p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button variant="secondary" onClick={handleDownloadPdf}>
            <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download PDF
          </Button>
          {invoice.status !== 'paid' && invoice.status !== 'sent' ? (
            <Button variant="secondary" onClick={() => setSendModal(true)}>
              <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              Send Invoice
            </Button>
          ) : null}
          <Button onClick={() => navigate(`/cp/invoices/${id}/edit`)}>Edit</Button>
          <Button variant="danger" onClick={() => setDeleteModal(true)}>Delete</Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className="lg:col-span-2">
          <div className="flex justify-between items-start mb-6">
            <div>
              <h3 className="text-lg font-medium text-gray-900">Invoice Details</h3>
            </div>
            <Badge variant={statusVariant(invoice.status)} size="lg">
              {invoice.status}
            </Badge>
          </div>

          <div className="grid grid-cols-2 gap-4 mb-6">
            <div>
              <dt className="text-sm font-medium text-gray-500">Invoice Number</dt>
              <dd className="mt-1 text-sm text-gray-900">{invoice.number}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Issue Date</dt>
              <dd className="mt-1 text-sm text-gray-900">{formatDate(invoice.issue_date)}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Due Date</dt>
              <dd className="mt-1 text-sm text-gray-900">{formatDate(invoice.due_date)}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Customer</dt>
              <dd className="mt-1 text-sm text-gray-900">
                {customer ? (
                  <Link to={`/cp/customers/${customer.id}`} className="text-primary-600 hover:text-primary-500">
                    {customer.name}
                  </Link>
                ) : '—'}
              </dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Service Type</dt>
              <dd className="mt-1 text-sm text-gray-900">{serviceType?.name || '—'}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Vehicle</dt>
              <dd className="mt-1 text-sm text-gray-900">{formatVehicle(vehicle)}</dd>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div>
              <h4 className="text-sm font-medium text-gray-900 mb-2">Customer Contact</h4>
              <div className="space-y-1 text-sm text-gray-600">
                <p>{customer?.email || '—'}</p>
                <p>{customer?.phone || '—'}</p>
              </div>
            </div>
            <div>
              <h4 className="text-sm font-medium text-gray-900 mb-2">Customer Address</h4>
              <p className="text-sm text-gray-600 whitespace-pre-line">
                {formatAddress(customer)}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div>
              <h4 className="text-sm font-medium text-gray-900 mb-2">Vehicle Details</h4>
              <div className="space-y-1 text-sm text-gray-600">
                <p>{formatVehicle(vehicle)}</p>
                <p>VIN: {vehicle?.vin || '—'}</p>
                <p>License Plate: {vehicle?.license_plate || '—'}</p>
              </div>
            </div>
            <div>
              <h4 className="text-sm font-medium text-gray-900 mb-2">Service Info</h4>
              <div className="space-y-1 text-sm text-gray-600">
                <p>Service Type: {serviceType?.name || '—'}</p>
                <p>Mobile Service: {invoice.is_mobile ? 'Yes' : 'No'}</p>
              </div>
            </div>
          </div>

          <h4 className="text-sm font-medium text-gray-900 mb-3">Line Items</h4>
          {lineItems.length === 0 ? (
            <p className="text-gray-500 text-sm py-4">No line items</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Description</th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Qty</th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Price</th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Total</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {lineItems.map((item, index) => (
                    <tr key={item.id || index}>
                      <td className="px-4 py-2 text-sm text-gray-900">{item.description || item.name}</td>
                      <td className="px-4 py-2 text-sm text-gray-500 text-right">{item.quantity}</td>
                      <td className="px-4 py-2 text-sm text-gray-500 text-right">{formatCurrency(item.unit_price || item.price)}</td>
                      <td className="px-4 py-2 text-sm text-gray-900 text-right font-medium">
                        {formatCurrency((item.quantity || 1) * (item.unit_price || item.price || 0))}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <h4 className="text-sm font-medium text-gray-900 mb-3 mt-8">Payment History</h4>
          {payments.length === 0 ? (
            <p className="text-gray-500 text-sm py-4">No payments recorded</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Method</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Reference</th>
                    <th className="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase">Amount</th>
                    <th className="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {payments.map((payment) => (
                    <tr key={payment.id || payment.reference}>
                      <td className="px-4 py-2 text-sm text-gray-900">{formatDateTime(payment.created_at || payment.paid_at)}</td>
                      <td className="px-4 py-2 text-sm text-gray-500">{payment.method || payment.gateway || '—'}</td>
                      <td className="px-4 py-2 text-sm text-gray-500">{payment.reference || payment.transaction_id || '—'}</td>
                      <td className="px-4 py-2 text-sm text-gray-900 text-right font-medium">
                        {formatCurrency(payment.amount)}
                      </td>
                      <td className="px-4 py-2 text-sm text-gray-500">{payment.status || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>

        <Card>
          <h3 className="text-lg font-medium text-gray-900 mb-4">Summary</h3>
          <dl className="space-y-3">
            <div className="flex justify-between">
              <dt className="text-sm text-gray-500">Subtotal</dt>
              <dd className="text-sm text-gray-900">{formatCurrency(invoice.subtotal)}</dd>
            </div>
            {invoice.tax ? (
              <div className="flex justify-between">
                <dt className="text-sm text-gray-500">Tax</dt>
                <dd className="text-sm text-gray-900">{formatCurrency(invoice.tax)}</dd>
              </div>
            ) : null}
            {invoice.shop_fee ? (
              <div className="flex justify-between">
                <dt className="text-sm text-gray-500">Shop Fee</dt>
                <dd className="text-sm text-gray-900">{formatCurrency(invoice.shop_fee)}</dd>
              </div>
            ) : null}
            {invoice.hazmat_disposal_fee ? (
              <div className="flex justify-between">
                <dt className="text-sm text-gray-500">Hazmat Disposal Fee</dt>
                <dd className="text-sm text-gray-900">{formatCurrency(invoice.hazmat_disposal_fee)}</dd>
              </div>
            ) : null}
            <div className="flex justify-between pt-3 border-t">
              <dt className="text-base font-medium text-gray-900">Total</dt>
              <dd className="text-base font-medium text-gray-900">{formatCurrency(invoice.total)}</dd>
            </div>
            {invoice.amount_paid ? (
              <>
                <div className="flex justify-between">
                  <dt className="text-sm text-gray-500">Amount Paid</dt>
                  <dd className="text-sm text-green-600">{formatCurrency(invoice.amount_paid)}</dd>
                </div>
                <div className="flex justify-between pt-3 border-t">
                  <dt className="text-base font-medium text-gray-900">Balance Due</dt>
                  <dd className="text-base font-medium text-gray-900">
                    {formatCurrency(invoice.balance_due ?? (invoice.total || 0) - (invoice.amount_paid || 0))}
                  </dd>
                </div>
              </>
            ) : null}
          </dl>

          {invoice.notes ? (
            <div className="mt-6 pt-6 border-t">
              <h4 className="text-sm font-medium text-gray-900 mb-2">Notes</h4>
              <p className="text-sm text-gray-500 whitespace-pre-wrap">{invoice.notes}</p>
            </div>
          ) : null}
        </Card>
      </div>

      <Modal open={sendModal} title="Send Invoice" onClose={() => setSendModal(false)}>
        <p className="text-sm text-gray-600 mb-4">
          This will send the invoice to <strong>{invoice.customer?.email || 'the customer'}</strong>.
        </p>
        <div className="flex justify-end gap-2">
          <Button variant="ghost" onClick={() => setSendModal(false)}>Cancel</Button>
          <Button loading={sending} onClick={handleSend}>Send Invoice</Button>
        </div>
      </Modal>

      <Modal open={deleteModal} title="Delete Invoice" onClose={() => setDeleteModal(false)}>
        <p className="text-sm text-gray-600 mb-4">
          Are you sure you want to delete invoice <strong>{invoice.number}</strong>? This action cannot be undone.
        </p>
        <div className="flex justify-end gap-2">
          <Button variant="ghost" onClick={() => setDeleteModal(false)}>Cancel</Button>
          <Button variant="danger" loading={deleting} onClick={handleDelete}>Delete</Button>
        </div>
      </Modal>
    </div>
  )
}
