// src/react/views/vehicles/VehicleList.jsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import Table from '../../components/ui/Table'
import { decodeVin, listVehicles, validateVin } from '../../../services/vehicle.service'
import { normalizeVinData } from '../../../utils/vin'

const columns = [
  { key: 'customer_id', label: 'Customer' },
  { key: 'year', label: 'Year' },
  { key: 'make', label: 'Make' },
  { key: 'model', label: 'Model' },
  { key: 'vin', label: 'VIN' },
  { key: 'license_plate', label: 'License Plate' },
  { key: 'mileage_in', label: 'Mileage In' },
  { key: 'mileage_out', label: 'Mileage Out' },
]

export default function VehicleList() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [vehicles, setVehicles] = useState([])
  const [filters, setFilters] = useState({ year: '', make: '', model: '', term: '' })
  const [vin, setVin] = useState('')
  const [vinResult, setVinResult] = useState(null)
  const [vinLoading, setVinLoading] = useState(false)

  const loadVehicles = useCallback(async () => {
    setLoading(true)
    const params = {}
    Object.entries(filters).forEach(([key, value]) => {
      if (value) params[key] = value
    })

    try {
      const data = await listVehicles(params)
      setVehicles(Array.isArray(data) ? data : [])
    } finally {
      setLoading(false)
    }
  }, [filters])

  useEffect(() => {
    loadVehicles()
  }, [loadVehicles])

  const goToDetail = (row) => {
    if (!row?.id) return
    navigate(`/cp/vehicles/${row.id}`)
  }

  const decode = async () => {
    setVinLoading(true)
    try {
      const result = await decodeVin(vin)
      setVinResult(result)
    } finally {
      setVinLoading(false)
    }
  }

  const validate = async () => {
    setVinLoading(true)
    try {
      const result = await validateVin(vin)
      setVinResult(result)
    } finally {
      setVinLoading(false)
    }
  }

  const vinDetails = useMemo(() => {
    if (!vinResult) return []

    const data = normalizeVinData(vinResult)

    const fields = [
      { key: 'vin', label: 'VIN' },
      { key: 'year', label: 'Year' },
      { key: 'make', label: 'Make' },
      { key: 'model', label: 'Model' },
      { key: 'trim', label: 'Trim' },
      { key: 'engine', label: 'Engine' },
      { key: 'transmission', label: 'Transmission' },
      { key: 'drive', label: 'Drive' },
      { key: 'fuel', label: 'Fuel' },
      { key: 'bodyStyle', label: 'Body Style' },
      { key: 'vehicleType', label: 'Vehicle Type' },
      { key: 'plantCountry', label: 'Assembly' },
      { key: 'manufacturer', label: 'Manufacturer' },
    ]

    return fields
      .map(({ key, label }) => ({ label, value: data[key] }))
      .filter((entry) => Boolean(entry.value))
  }, [vinResult])

  const vinMessage = useMemo(() => {
    if (!vinResult) return ''
    if (vinResult.message) return vinResult.message
    if (vinResult.valid === true) return 'VIN is valid'
    if (vinResult.valid === false) return 'VIN is invalid'
    return 'VIN details'
  }, [vinResult])

  const vinSummary = useMemo(() => {
    if (!vinResult) return ''
    const data = normalizeVinData(vinResult)
    const summaryParts = [data.year, data.make, data.model].filter(Boolean)
    const detailParts = [data.trim, data.bodyStyle, data.vehicleType].filter(Boolean)

    return [summaryParts.join(' • '), detailParts.join(' · ')].filter(Boolean).join(' — ')
  }, [vinResult])

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Customer Vehicles</h1>
          <p className="mt-1 text-sm text-gray-500">Manage vehicles in customer garages</p>
        </div>
        <div className="flex gap-3">
          <Button variant="secondary" onClick={() => navigate('/cp/vehicle-master')}>
            <svg className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
            </svg>
            Vehicle Database
          </Button>
          <Button onClick={() => navigate('/cp/vehicles/create')}>
            <svg className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4" />
            </svg>
            Add to Customer Garage
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-2">
          <div className="flex flex-col gap-4">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">Year</label>
                <Input
                  value={filters.year}
                  type="number"
                  placeholder="2024"
                  onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, year: value }))}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Make</label>
                <Input
                  value={filters.make}
                  placeholder="Ford"
                  onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, make: value }))}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Model</label>
                <Input
                  value={filters.model}
                  placeholder="F-150"
                  onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, model: value }))}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Search term</label>
                <Input
                  value={filters.term}
                  placeholder="Engine, transmission..."
                  onUpdateModelValue={(value) => setFilters((prev) => ({ ...prev, term: value }))}
                />
              </div>
            </div>

            <Table
              columns={columns}
              data={vehicles}
              loading={loading}
              hoverable
              onRowClick={goToDetail}
              cellRenderers={{
                year: ({ value }) => <span className="font-semibold">{value}</span>,
                engine: ({ value }) => <span className="text-sm text-gray-700">{value || 'N/A'}</span>,
                transmission: ({ value }) => <Badge variant="secondary">{value || 'Unknown'}</Badge>,
                drive: ({ value }) => <span className="text-sm">{value || '—'}</span>,
              }}
              renderActions={(row) => (
                <div className="flex gap-2 justify-end">
                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={(event) => {
                      event.stopPropagation()
                      goToDetail(row)
                    }}
                  >
                    View
                  </Button>
                </div>
              )}
              renderEmpty={<p className="text-sm text-gray-500">No vehicles found for the current filters.</p>}
            />
          </div>
        </Card>

        <Card>
          <h3 className="text-lg font-semibold text-gray-900 mb-3">VIN decoder</h3>
          <div className="space-y-3">
            <div>
              <label className="block text-sm font-medium text-gray-700">VIN</label>
              <Input
                value={vin}
                maxlength={17}
                placeholder="Enter 17-character VIN"
                onUpdateModelValue={(value) => setVin(value)}
              />
            </div>
            <div className="flex gap-2">
              <Button className="flex-1" loading={vinLoading} onClick={decode}>
                Decode
              </Button>
              <Button className="flex-1" variant="secondary" loading={vinLoading} onClick={validate}>
                Validate
              </Button>
            </div>
            {vinResult ? (
              <div className="rounded-md bg-gray-50 p-3 text-sm text-gray-800">
                <p className="font-semibold">{vinMessage}</p>
                {vinSummary ? (
                  <p className="mt-1 text-xs text-gray-600">{vinSummary}</p>
                ) : null}
                <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-2">
                  {vinDetails.map((field) => (
                    <div key={field.label}>
                      <p className="text-xs text-gray-500">{field.label}</p>
                      <p className="text-sm font-medium text-gray-900">{field.value}</p>
                    </div>
                  ))}
                </div>
              </div>
            ) : null}
          </div>
        </Card>
      </div>
    </div>
  )
}

// src/views/vehicles/VehicleList.vue
<template>
  <div>
    <div class="mb-6 flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Customer Vehicles</h1>
        <p class="mt-1 text-sm text-gray-500">Manage vehicles in customer garages</p>
      </div>
      <div class="flex gap-3">
        <Button variant="secondary" @click="$router.push('/cp/vehicle-master')">
          <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
          </svg>
          Vehicle Database
        </Button>
        <Button @click="$router.push('/cp/vehicles/create')">
          <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
          Add to Customer Garage
        </Button>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <Card class="lg:col-span-2">
        <div class="flex flex-col gap-4">
          <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Year</label>
              <Input v-model="filters.year" type="number" placeholder="2024" @input="loadVehicles" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Make</label>
              <Input v-model="filters.make" placeholder="Ford" @input="loadVehicles" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Model</label>
              <Input v-model="filters.model" placeholder="F-150" @input="loadVehicles" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Search term</label>
              <Input v-model="filters.term" placeholder="Engine, transmission..." @input="loadVehicles" />
            </div>
          </div>

          <Table :columns="columns" :data="vehicles" :loading="loading" hoverable @row-click="goToDetail">
            <template #cell(year)="{ value }">
              <span class="font-semibold">{{ value }}</span>
            </template>
            <template #cell(engine)="{ value }">
              <span class="text-sm text-gray-700">{{ value || 'N/A' }}</span>
            </template>
            <template #cell(transmission)="{ value }">
              <Badge variant="secondary">{{ value || 'Unknown' }}</Badge>
            </template>
            <template #cell(drive)="{ value }">
              <span class="text-sm">{{ value || '—' }}</span>
            </template>
            <template #actions="{ row }">
              <div class="flex gap-2">
                <Button size="sm" variant="secondary" @click.stop="goToDetail(row)">View</Button>
              </div>
            </template>
            <template #empty>
              <p class="text-sm text-gray-500">No vehicles found for the current filters.</p>
            </template>
          </Table>
        </div>
      </Card>

      <Card>
        <h3 class="text-lg font-semibold text-gray-900 mb-3">VIN decoder</h3>
        <div class="space-y-3">
          <div>
            <label class="block text-sm font-medium text-gray-700">VIN</label>
            <Input v-model="vin" maxlength="17" placeholder="Enter 17-character VIN" />
          </div>
          <div class="flex gap-2">
            <Button class="flex-1" :loading="vinLoading" @click="decode">Decode</Button>
            <Button class="flex-1" variant="secondary" :loading="vinLoading" @click="validate">Validate</Button>
          </div>
          <div v-if="vinResult" class="rounded-md bg-gray-50 p-3 text-sm text-gray-800">
            <p class="font-semibold">{{ vinMessage }}</p>
            <div class="mt-3 grid grid-cols-2 gap-x-4 gap-y-2">
              <div v-for="field in vinDetails" :key="field.label">
                <p class="text-xs text-gray-500">{{ field.label }}</p>
                <p class="text-sm font-medium text-gray-900">{{ field.value || '—' }}</p>
              </div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import Badge from '@/components/ui/Badge.vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import Table from '@/components/ui/Table.vue'
import { decodeVin, listVehicles, validateVin } from '@/services/vehicle.service'

const loading = ref(false)
const vehicles = ref([])
const filters = reactive({ year: '', make: '', model: '', term: '' })
const vin = ref('')
const vinResult = ref(null)
const vinLoading = ref(false)
const router = useRouter()

const columns = [
  { key: 'customer_id', label: 'Customer' },
  { key: 'year', label: 'Year' },
  { key: 'make', label: 'Make' },
  { key: 'model', label: 'Model' },
  { key: 'vin', label: 'VIN' },
  { key: 'license_plate', label: 'License Plate' },
  { key: 'mileage_in', label: 'Mileage In' },
  { key: 'mileage_out', label: 'Mileage Out' }
]

const loadVehicles = async () => {
  loading.value = true
  const params = {}
  Object.entries(filters).forEach(([key, value]) => {
    if (value) params[key] = value
  })
  try {
    vehicles.value = await listVehicles(params)
  } finally {
    loading.value = false
  }
}

const goToDetail = (row) => {
  if (!row?.id) return
  router.push(`/vehicles/${row.id}`)
}

const decode = async () => {
  vinLoading.value = true
  try {
    vinResult.value = await decodeVin(vin.value)
  } finally {
    vinLoading.value = false
  }
}

const validate = async () => {
  vinLoading.value = true
  try {
    vinResult.value = await validateVin(vin.value)
  } finally {
    vinLoading.value = false
  }
}

const vinDetails = computed(() => {
  if (!vinResult.value) return []

  const data =
    vinResult.value.decoded ||
    vinResult.value.basic_info ||
    vinResult.value.vehicle ||
    vinResult.value

  return [
    { label: 'Year', value: data.year },
    { label: 'Make', value: data.make },
    { label: 'Model', value: data.model },
    { label: 'Engine', value: data.engine },
    { label: 'Transmission', value: data.transmission },
    { label: 'Drive', value: data.drive },
    { label: 'Trim', value: data.trim },
    { label: 'Fuel', value: data.fuel_type || data.fuel || data.fuelType }
  ]
})

const vinMessage = computed(() => {
  if (!vinResult.value) return ''
  if (vinResult.value.message) return vinResult.value.message
  if (vinResult.value.valid === true) return 'VIN is valid'
  if (vinResult.value.valid === false) return 'VIN is invalid'
  return 'VIN details'
})

onMounted(loadVehicles)
</script>
