// src/react/views/vehicles/VehicleForm.jsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'

import Autocomplete from '../../components/ui/Autocomplete'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import Textarea from '../../components/ui/Textarea'
import {
  decodeVin,
  getDrives,
  getEngines,
  getMakes,
  getModels,
  getTransmissions,
  getTrims,
  getYears,
} from '../../../services/vehicle-master.service'
import { createCustomerVehicle, updateCustomerVehicle } from '../../../services/customer-vehicle.service'
import { getVehicle } from '../../../services/vehicle.service'
import { getCustomer, listCustomers } from '../../../services/customer.service'
import { useToast } from '../../stores/toast'
import { normalizeVinData } from '../../../utils/vin'

export default function VehicleForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const { success: toastSuccess, error: toastError } = useToast()

  const [saving, setSaving] = useState(false)
  const [decoding, setDecoding] = useState(false)
  const [success, setSuccess] = useState('')
  const [error, setError] = useState('')
  const [vinError, setVinError] = useState('')
  const [vinSuccess, setVinSuccess] = useState('')

  const [years, setYears] = useState([])
  const [makes, setMakes] = useState([])
  const [models, setModels] = useState([])
  const [engines, setEngines] = useState([])
  const [transmissions, setTransmissions] = useState([])
  const [drives, setDrives] = useState([])
  const [trims, setTrims] = useState([])

  const [form, setForm] = useState({
    customer_id: null,
    year: '',
    make: '',
    model: '',
    engine: '',
    transmission: '',
    drive: '',
    trim: '',
    vin: '',
    license_plate: '',
    mileage_in: null,
    mileage_out: null,
    notes: '',
  })

  const isEditing = Boolean(id)

  const loadYears = useCallback(async () => {
    try {
      const data = await getYears()
      setYears(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load years:', err)
    }
  }, [])

  const loadMakes = useCallback(async (year) => {
    if (!year) {
      setMakes([])
      return
    }
    try {
      const data = await getMakes(year)
      setMakes(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load makes:', err)
    }
  }, [])

  const loadModels = useCallback(async (year, make) => {
    if (!year || !make) {
      setModels([])
      return
    }
    try {
      const data = await getModels(year, make)
      setModels(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load models:', err)
    }
  }, [])

  const loadEngines = useCallback(async (year, make, model) => {
    if (!year || !make || !model) {
      setEngines([])
      return
    }
    try {
      const data = await getEngines(year, make, model)
      setEngines(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load engines:', err)
    }
  }, [])

  const loadTransmissions = useCallback(async (year, make, model, engine) => {
    if (!year || !make || !model || !engine) {
      setTransmissions([])
      return
    }
    try {
      const data = await getTransmissions(year, make, model, engine)
      setTransmissions(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load transmissions:', err)
      setTransmissions([])
      setDrives([])
      setTrims([])
      toastError('Unable to load transmissions for the selected engine. Please try again.')
    }
  }, [toastError])

  const loadDrives = useCallback(async (year, make, model, engine, transmission) => {
    if (!year || !make || !model || !engine || !transmission) {
      setDrives([])
      return
    }
    try {
      const data = await getDrives(year, make, model, engine, transmission)
      setDrives(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load drives:', err)
    }
  }, [])

  const loadTrims = useCallback(async (year, make, model, engine, transmission, drive) => {
    if (!year || !make || !model || !engine || !transmission || !drive) {
      setTrims([])
      return
    }
    try {
      const data = await getTrims(year, make, model, engine, transmission, drive)
      setTrims(Array.isArray(data) ? data : [])
    } catch (err) {
      console.error('Failed to load trims:', err)
    }
  }, [])

  useEffect(() => {
    loadYears()
  }, [loadYears])

  const onYearChange = async (value) => {
    setForm((prev) => ({
      ...prev,
      year: value ? Number(value) : '',
      make: '',
      model: '',
      engine: '',
      transmission: '',
      drive: '',
      trim: '',
    }))
    setModels([])
    setEngines([])
    setTransmissions([])
    setDrives([])
    setTrims([])
    await loadMakes(value)
  }

  const onMakeChange = async (value, yearOverride) => {
    const yearValue = yearOverride ?? form.year
    setForm((prev) => ({
      ...prev,
      make: value,
      model: '',
      engine: '',
      transmission: '',
      drive: '',
      trim: '',
    }))
    setEngines([])
    setTransmissions([])
    setDrives([])
    setTrims([])
    await loadModels(yearValue, value)
  }

  const onModelChange = async (value, yearOverride, makeOverride) => {
    const yearValue = yearOverride ?? form.year
    const makeValue = makeOverride ?? form.make
    setForm((prev) => ({
      ...prev,
      model: value,
      engine: '',
      transmission: '',
      drive: '',
      trim: '',
    }))
    setTransmissions([])
    setDrives([])
    setTrims([])
    await loadEngines(yearValue, makeValue, value)
  }

  const onEngineChange = async (value, yearOverride, makeOverride, modelOverride) => {
    const yearValue = yearOverride ?? form.year
    const makeValue = makeOverride ?? form.make
    const modelValue = modelOverride ?? form.model
    setForm((prev) => ({
      ...prev,
      engine: value,
      transmission: '',
      drive: '',
      trim: '',
    }))
    setDrives([])
    setTrims([])
    await loadTransmissions(yearValue, makeValue, modelValue, value)
  }

  const onTransmissionChange = async (value, yearOverride, makeOverride, modelOverride, engineOverride) => {
    const yearValue = yearOverride ?? form.year
    const makeValue = makeOverride ?? form.make
    const modelValue = modelOverride ?? form.model
    const engineValue = engineOverride ?? form.engine
    setForm((prev) => ({
      ...prev,
      transmission: value,
      drive: '',
      trim: '',
    }))
    setTrims([])
    await loadDrives(yearValue, makeValue, modelValue, engineValue, value)
  }

  const onDriveChange = async (value, yearOverride, makeOverride, modelOverride, engineOverride, transmissionOverride) => {
    const yearValue = yearOverride ?? form.year
    const makeValue = makeOverride ?? form.make
    const modelValue = modelOverride ?? form.model
    const engineValue = engineOverride ?? form.engine
    const transmissionValue = transmissionOverride ?? form.transmission
    setForm((prev) => ({
      ...prev,
      drive: value,
      trim: '',
    }))
    await loadTrims(yearValue, makeValue, modelValue, engineValue, transmissionValue, value)
  }

  const loadVehicle = useCallback(async () => {
    if (!id) return
    try {
      const vehicle = await getVehicle(id)
      setForm({
        customer_id: vehicle.customer_id,
        year: vehicle.year,
        make: vehicle.make,
        model: vehicle.model,
        engine: vehicle.engine || '',
        transmission: vehicle.transmission || '',
        drive: vehicle.drive || '',
        trim: vehicle.trim || '',
        vin: vehicle.vin || '',
        license_plate: vehicle.license_plate || '',
        mileage_in: vehicle.mileage_in || null,
        mileage_out: vehicle.mileage_out || null,
        notes: vehicle.notes || '',
      })

      if (vehicle.year) await loadMakes(vehicle.year)
      if (vehicle.make) await loadModels(vehicle.year, vehicle.make)
      if (vehicle.model) await loadEngines(vehicle.year, vehicle.make, vehicle.model)
      if (vehicle.engine) await loadTransmissions(vehicle.year, vehicle.make, vehicle.model, vehicle.engine)
      if (vehicle.transmission) await loadDrives(vehicle.year, vehicle.make, vehicle.model, vehicle.engine, vehicle.transmission)
      if (vehicle.drive) await loadTrims(vehicle.year, vehicle.make, vehicle.model, vehicle.engine, vehicle.transmission, vehicle.drive)
    } catch (err) {
      setError('Failed to load vehicle')
      console.error(err)
    }
  }, [id, loadDrives, loadEngines, loadMakes, loadModels, loadTransmissions, loadTrims])

  useEffect(() => {
    if (isEditing) {
      loadVehicle()
    }
  }, [isEditing, loadVehicle])

  const decodeVinNumber = async () => {
    if (!form.vin || form.vin.length < 17) {
      setVinError('VIN must be at least 17 characters')
      return
    }

    setDecoding(true)
    setVinError('')
    setVinSuccess('')

    try {
      const decoded = normalizeVinData(await decodeVin(form.vin))

      if (decoded.year) {
        await onYearChange(decoded.year)
      }
      if (decoded.make) {
        await onMakeChange(decoded.make, decoded.year ?? form.year)
      }
      if (decoded.model) {
        await onModelChange(decoded.model, decoded.year ?? form.year, decoded.make ?? form.make)
      }
      if (decoded.engine) {
        await onEngineChange(decoded.engine, decoded.year ?? form.year, decoded.make ?? form.make, decoded.model ?? form.model)
      }
      if (decoded.transmission) {
        await onTransmissionChange(
          decoded.transmission,
          decoded.year ?? form.year,
          decoded.make ?? form.make,
          decoded.model ?? form.model,
          decoded.engine ?? form.engine
        )
      }
      if (decoded.drive) {
        await onDriveChange(
          decoded.drive,
          decoded.year ?? form.year,
          decoded.make ?? form.make,
          decoded.model ?? form.model,
          decoded.engine ?? form.engine,
          decoded.transmission ?? form.transmission
        )
      }
      if (decoded.trim) {
        setForm((prev) => ({
          ...prev,
          trim: decoded.trim,
        }))
      }

      setVinSuccess('VIN decoded successfully!')
      toastSuccess('VIN decoded successfully!')
    } catch (err) {
      setVinError(err.response?.data?.message || 'Failed to decode VIN')
      toastError('Failed to decode VIN')
      console.error(err)
    } finally {
      setDecoding(false)
    }
  }

  const save = async (event) => {
    event.preventDefault()
    setSaving(true)
    setError('')
    setSuccess('')

    if (!form.customer_id) {
      setError('Please select a customer before saving.')
      setSaving(false)
      return
    }

    try {
      if (isEditing) {
        await updateCustomerVehicle(form.customer_id, id, form)
        setSuccess('Vehicle updated successfully!')
        toastSuccess('Vehicle updated successfully!')
      } else {
        await createCustomerVehicle(form.customer_id, form)
        setSuccess('Vehicle added to customer garage successfully!')
        toastSuccess('Vehicle added to customer garage successfully!')
      }

      setTimeout(() => {
        navigate('/cp/vehicles')
      }, 1500)
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to save vehicle')
      toastError('Failed to save vehicle')
      console.error(err)
    } finally {
      setSaving(false)
    }
  }

  const searchCustomers = useCallback(async (query) => {
    if (!query) return []
    try {
      const results = await listCustomers({ query })
      const list = Array.isArray(results) ? results : results?.data || []
      if (list.length === 0 && /^\d+$/.test(query)) {
        const customer = await getCustomer(query)
        return customer ? [customer] : []
      }
      return list
    } catch (err) {
      console.error('Failed to search customers:', err)
      return []
    }
  }, [])

  const customerLabel = useMemo(() => {
    if (!form.customer_id) return ''
    return `Customer #${form.customer_id}`
  }, [form.customer_id])

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">{isEditing ? 'Edit Customer Vehicle' : 'Add Vehicle to Customer Garage'}</h1>
          <p className="mt-1 text-sm text-gray-500">
            {isEditing ? 'Update vehicle information' : 'Add a vehicle to a customer\'s garage'}
          </p>
        </div>
        <Button variant="secondary" onClick={() => navigate('/cp/vehicles')}>Back to list</Button>
      </div>

      <Card className="max-w-5xl">
        <form className="space-y-6" onSubmit={save}>
          <div>
            <Autocomplete
              modelValue={form.customer_id}
              label="Customer"
              placeholder="Search by name, email, phone, or ID"
              searchFn={searchCustomers}
              itemValue={(item) => item.id}
              itemLabel={(item) => item.name || `Customer #${item.id}`}
              itemSubtext={(item) => `${item.email || 'No email'} • ${item.phone || 'No phone'}`}
              required
              helperText="Search for a customer by name, email, phone, or ID"
              onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, customer_id: value }))}
            />
            {customerLabel ? (
              <input type="hidden" value={customerLabel} readOnly />
            ) : null}
          </div>

          <div className="border-t border-gray-200 pt-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">VIN Information</h3>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <div className="md:col-span-2">
                <label className="block text-sm font-medium text-gray-700">VIN</label>
                <Input
                  value={form.vin}
                  placeholder="1HGBH41JXMN109186"
                  maxlength={30}
                  onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, vin: value }))}
                />
                <p className="mt-1 text-xs text-gray-500">Optional - Enter vehicle identification number</p>
              </div>
              <div className="flex items-end gap-2">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={decodeVinNumber}
                  loading={decoding}
                  disabled={!form.vin || form.vin.length < 17}
                  className="flex-1"
                >
                  <svg className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                  Decode
                </Button>
              </div>
            </div>
            {vinError ? <p className="mt-2 text-sm text-red-600">{vinError}</p> : null}
            {vinSuccess ? <p className="mt-2 text-sm text-green-600">{vinSuccess}</p> : null}
          </div>

          <div className="border-t border-gray-200 pt-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">Vehicle Specifications</h3>
            <p className="text-sm text-gray-600 mb-4">Select vehicle from database or VIN decoder will populate these fields</p>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <div>
                <label className="block text-sm font-medium text-gray-700">Year *</label>
                <select
                  value={form.year || ''}
                  required
                  onChange={(event) => onYearChange(event.target.value)}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Year</option>
                  {years.map((year) => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Make *</label>
                <select
                  value={form.make}
                  required
                  onChange={(event) => onMakeChange(event.target.value)}
                  disabled={!form.year}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Make</option>
                  {makes.map((make) => (
                    <option key={make} value={make}>{make}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Model *</label>
                <select
                  value={form.model}
                  required
                  onChange={(event) => onModelChange(event.target.value)}
                  disabled={!form.make}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Model</option>
                  {models.map((model) => (
                    <option key={model} value={model}>{model}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-4 mt-4">
              <div>
                <label className="block text-sm font-medium text-gray-700">Engine *</label>
                <select
                  value={form.engine}
                  required
                  onChange={(event) => onEngineChange(event.target.value)}
                  disabled={!form.model}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Engine</option>
                  {engines.map((engine) => (
                    <option key={engine} value={engine}>{engine}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Transmission *</label>
                <select
                  value={form.transmission}
                  required
                  onChange={(event) => onTransmissionChange(event.target.value)}
                  disabled={!form.engine}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Transmission</option>
                  {transmissions.map((transmission) => (
                    <option key={transmission} value={transmission}>{transmission}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Drive *</label>
                <select
                  value={form.drive}
                  required
                  onChange={(event) => onDriveChange(event.target.value)}
                  disabled={!form.transmission}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Drive</option>
                  {drives.map((drive) => (
                    <option key={drive} value={drive}>{drive}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Trim</label>
                <select
                  value={form.trim}
                  onChange={(event) => setForm((prev) => ({ ...prev, trim: event.target.value }))}
                  disabled={!form.drive}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="">Select Trim (Optional)</option>
                  {trims.map((trim) => (
                    <option key={trim} value={trim}>{trim}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          <div className="border-t border-gray-200 pt-6">
            <h3 className="text-lg font-medium text-gray-900 mb-4">Additional Information</h3>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
              <div>
                <label className="block text-sm font-medium text-gray-700">License Plate</label>
                <Input
                  value={form.license_plate}
                  placeholder="ABC-1234"
                  maxlength={30}
                  onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, license_plate: value }))}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Mileage In</label>
                <Input
                  value={form.mileage_in ?? ''}
                  type="number"
                  placeholder="50000"
                  min="0"
                  onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, mileage_in: value }))}
                />
                <p className="mt-1 text-xs text-gray-500">Mileage when vehicle arrives</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700">Mileage Out</label>
                <Input
                  value={form.mileage_out ?? ''}
                  type="number"
                  placeholder="50100"
                  min="0"
                  onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, mileage_out: value }))}
                />
                <p className="mt-1 text-xs text-gray-500">Mileage when vehicle leaves</p>
              </div>
            </div>

            <div className="mt-4">
              <label className="block text-sm font-medium text-gray-700">Notes</label>
              <Textarea
                value={form.notes}
                rows={3}
                className="mt-1"
                placeholder="Additional notes about this vehicle"
                onUpdateModelValue={(value) => setForm((prev) => ({ ...prev, notes: value }))}
              />
            </div>
          </div>

          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between border-t border-gray-200 pt-6">
            <div>
              <p className="text-sm text-gray-600">Fields marked with * are required.</p>
              {error ? <p className="text-sm text-red-600">{error}</p> : null}
              {success ? <p className="text-sm text-green-600">{success}</p> : null}
            </div>
            <div className="flex gap-3">
              <Button type="button" variant="secondary" onClick={() => navigate('/cp/vehicles')}>Cancel</Button>
              <Button type="submit" loading={saving}>{isEditing ? 'Update Vehicle' : 'Add to Garage'}</Button>
            </div>
          </div>
        </form>
      </Card>
    </div>
  )
}

// src/views/vehicles/VehicleForm.vue
<template>
  <div>
    <div class="mb-6 flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">{{ isEditing ? 'Edit Customer Vehicle' : 'Add Vehicle to Customer Garage' }}</h1>
        <p class="mt-1 text-sm text-gray-500">{{ isEditing ? 'Update vehicle information' : 'Add a vehicle to a customer\'s garage' }}</p>
      </div>
      <Button variant="secondary" @click="goBack">Back to list</Button>
    </div>

    <Card class="max-w-5xl">
      <form class="space-y-6" @submit.prevent="save">
        <!-- Customer Selection -->
        <div>
          <label class="block text-sm font-medium text-gray-700">Customer *</label>
          <div class="relative mt-1">
            <Input
              v-model="customerQuery"
              required
              placeholder="Search by name, email, phone, or ID"
              @focus="customerDropdownOpen = true"
              @blur="closeCustomerDropdown"
            />
            <input v-model="form.customer_id" type="hidden" required />

            <div
              v-if="customerDropdownOpen"
              class="absolute z-10 mt-1 w-full rounded-md border border-gray-200 bg-white shadow-lg"
            >
              <div v-if="searchingCustomers" class="px-3 py-2 text-sm text-gray-500">Searching...</div>
              <button
                v-for="customer in customerResults"
                :key="customer.id"
                type="button"
                class="w-full px-3 py-2 text-left hover:bg-gray-50"
                @mousedown.prevent="selectCustomer(customer)"
              >
                <p class="text-sm font-medium text-gray-900">
                  {{ customer.name || `Customer #${customer.id}` }}
                </p>
                <p class="text-xs text-gray-600">
                  {{ customer.email || 'No email' }} • {{ customer.phone || 'No phone' }}
                </p>
              </button>
              <div
                v-if="!searchingCustomers && customerResults.length === 0 && customerQuery"
                class="px-3 py-2 text-sm text-gray-500"
              >
                No customers found
              </div>
            </div>
          </div>
          <p class="mt-1 text-xs text-gray-500">Search for a customer by name, email, phone, or ID</p>
        </div>

        <!-- VIN Section -->
        <div class="border-t border-gray-200 pt-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">VIN Information</h3>
          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div class="md:col-span-2">
              <label class="block text-sm font-medium text-gray-700">VIN</label>
              <Input v-model="form.vin" placeholder="1HGBH41JXMN109186" maxlength="30" />
              <p class="mt-1 text-xs text-gray-500">Optional - Enter vehicle identification number</p>
            </div>
            <div class="flex items-end gap-2">
              <Button
                type="button"
                variant="secondary"
                @click="decodeVinNumber"
                :loading="decoding"
                :disabled="!form.vin || form.vin.length < 17"
                class="flex-1"
              >
                <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                Decode
              </Button>
            </div>
          </div>
          <p v-if="vinError" class="mt-2 text-sm text-red-600">{{ vinError }}</p>
          <p v-if="vinSuccess" class="mt-2 text-sm text-green-600">{{ vinSuccess }}</p>
        </div>

        <!-- Vehicle Selection from Database -->
        <div class="border-t border-gray-200 pt-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Vehicle Specifications</h3>
          <p class="text-sm text-gray-600 mb-4">Select vehicle from database or VIN decoder will populate these fields</p>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div>
              <label class="block text-sm font-medium text-gray-700">Year *</label>
              <select
                v-model.number="form.year"
                required
                @change="onYearChange"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Year</option>
                <option v-for="year in years" :key="year" :value="year">{{ year }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Make *</label>
              <select
                v-model="form.make"
                required
                @change="onMakeChange"
                :disabled="!form.year"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Make</option>
                <option v-for="make in makes" :key="make" :value="make">{{ make }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Model *</label>
              <select
                v-model="form.model"
                required
                @change="onModelChange"
                :disabled="!form.make"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Model</option>
                <option v-for="model in models" :key="model" :value="model">{{ model }}</option>
              </select>
            </div>
          </div>

          <div class="grid grid-cols-1 gap-4 md:grid-cols-4 mt-4">
            <div>
              <label class="block text-sm font-medium text-gray-700">Engine *</label>
              <select
                v-model="form.engine"
                required
                @change="onEngineChange"
                :disabled="!form.model"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Engine</option>
                <option v-for="engine in engines" :key="engine" :value="engine">{{ engine }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Transmission *</label>
              <select
                v-model="form.transmission"
                required
                @change="onTransmissionChange"
                :disabled="!form.engine"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Transmission</option>
                <option v-for="transmission in transmissions" :key="transmission" :value="transmission">{{ transmission }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Drive *</label>
              <select
                v-model="form.drive"
                required
                @change="onDriveChange"
                :disabled="!form.transmission"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Drive</option>
                <option v-for="drive in drives" :key="drive" :value="drive">{{ drive }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Trim</label>
              <select
                v-model="form.trim"
                :disabled="!form.drive"
                class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              >
                <option value="">Select Trim (Optional)</option>
                <option v-for="trim in trims" :key="trim" :value="trim">{{ trim }}</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Additional Information -->
        <div class="border-t border-gray-200 pt-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Additional Information</h3>
          <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div>
              <label class="block text-sm font-medium text-gray-700">License Plate</label>
              <Input v-model="form.license_plate" placeholder="ABC-1234" maxlength="30" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Mileage In</label>
              <Input v-model.number="form.mileage_in" type="number" placeholder="50000" min="0" />
              <p class="mt-1 text-xs text-gray-500">Mileage when vehicle arrives</p>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">Mileage Out</label>
              <Input v-model.number="form.mileage_out" type="number" placeholder="50100" min="0" />
              <p class="mt-1 text-xs text-gray-500">Mileage when vehicle leaves</p>
            </div>
          </div>

          <div class="mt-4">
            <label class="block text-sm font-medium text-gray-700">Notes</label>
            <textarea
              v-model="form.notes"
              :rows="3"
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
              placeholder="Additional notes about this vehicle"
            ></textarea>
          </div>
        </div>

        <!-- Form Actions -->
        <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between border-t border-gray-200 pt-6">
          <div>
            <p class="text-sm text-gray-600">Fields marked with * are required.</p>
            <p v-if="error" class="text-sm text-red-600">{{ error }}</p>
            <p v-if="success" class="text-sm text-green-600">{{ success }}</p>
          </div>
          <div class="flex gap-3">
            <Button type="button" variant="secondary" @click="goBack">Cancel</Button>
            <Button type="submit" :loading="saving">{{ isEditing ? 'Update Vehicle' : 'Add to Garage' }}</Button>
          </div>
        </div>
      </form>
    </Card>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref, computed, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import {
  getYears,
  getMakes,
  getModels,
  getEngines,
  getTransmissions,
  getDrives,
  getTrims,
  decodeVin
} from '@/services/vehicle-master.service'
import { createCustomerVehicle, updateCustomerVehicle, getCustomerVehicle } from '@/services/customer-vehicle.service'
import { getCustomer, listCustomers } from '@/services/customer.service'
import { useToast } from '@/stores/toast'

const router = useRouter()
const route = useRoute()
const toast = useToast()

const saving = ref(false)
const decoding = ref(false)
const success = ref('')
const error = ref('')
const vinError = ref('')
const vinSuccess = ref('')

const years = ref([])
const makes = ref([])
const models = ref([])
const engines = ref([])
const transmissions = ref([])
const drives = ref([])
const trims = ref([])
const customerQuery = ref('')
const customerResults = ref([])
const customerDropdownOpen = ref(false)
const searchingCustomers = ref(false)
const selectedCustomer = ref(null)
const suppressCustomerSearch = ref(false)

const form = reactive({
  customer_id: null,
  year: null,
  make: '',
  model: '',
  engine: '',
  transmission: '',
  drive: '',
  trim: '',
  vin: '',
  license_plate: '',
  mileage_in: null,
  mileage_out: null,
  notes: '',
})

const isEditing = computed(() => !!route.params.id)

let customerSearchTimeout

onMounted(async () => {
  await loadYears()
  if (isEditing.value) {
    await loadVehicle()
  }
})

watch(customerQuery, (value) => {
  if (suppressCustomerSearch.value) {
    suppressCustomerSearch.value = false
    return
  }

  if (customerSearchTimeout) clearTimeout(customerSearchTimeout)

  if (!value) {
    customerResults.value = []
    return
  }

  customerDropdownOpen.value = true
  customerSearchTimeout = setTimeout(() => searchCustomers(value), 300)
})

watch(
  () => form.customer_id,
  (id) => {
    if (!id) {
      selectedCustomer.value = null
      return
    }

    if (!selectedCustomer.value || selectedCustomer.value.id !== id) {
      loadSelectedCustomer(id)
    }
  }
)

async function loadYears() {
  try {
    years.value = await getYears()
  } catch (err) {
    console.error('Failed to load years:', err)
  }
}

async function searchCustomers(query) {
  searchingCustomers.value = true

  try {
    const results = await listCustomers({ query })
    customerResults.value = Array.isArray(results) ? results : results?.data || []
  } catch (err) {
    console.error('Failed to search customers:', err)
  } finally {
    searchingCustomers.value = false
  }
}

function closeCustomerDropdown() {
  setTimeout(() => {
    customerDropdownOpen.value = false
  }, 150)
}

function formatCustomerLabel(customer) {
  const name = customer.name || `Customer #${customer.id}`
  const contact = [customer.email, customer.phone].filter(Boolean).join(' • ')
  return contact ? `${name} (${contact})` : name
}

function selectCustomer(customer) {
  selectedCustomer.value = customer
  form.customer_id = customer.id
  suppressCustomerSearch.value = true
  customerQuery.value = formatCustomerLabel(customer)
  customerResults.value = []
  customerDropdownOpen.value = false
}

async function loadSelectedCustomer(customerId) {
  if (!customerId) {
    customerQuery.value = ''
    selectedCustomer.value = null
    return
  }

  try {
    const customer = await getCustomer(customerId)
    selectedCustomer.value = customer
    suppressCustomerSearch.value = true
    customerQuery.value = formatCustomerLabel(customer)
  } catch (err) {
    console.error('Failed to load customer:', err)
  }
}

async function onYearChange() {
  form.make = ''
  form.model = ''
  form.engine = ''
  form.transmission = ''
  form.drive = ''
  form.trim = ''
  makes.value = []
  models.value = []
  engines.value = []
  transmissions.value = []
  drives.value = []
  trims.value = []

  if (form.year) {
    try {
      makes.value = await getMakes(form.year)
    } catch (err) {
      console.error('Failed to load makes:', err)
    }
  }
}

async function onMakeChange() {
  form.model = ''
  form.engine = ''
  form.transmission = ''
  form.drive = ''
  form.trim = ''
  models.value = []
  engines.value = []
  transmissions.value = []
  drives.value = []
  trims.value = []

  if (form.year && form.make) {
    try {
      models.value = await getModels(form.year, form.make)
    } catch (err) {
      console.error('Failed to load models:', err)
    }
  }
}

async function onModelChange() {
  form.engine = ''
  form.transmission = ''
  form.drive = ''
  form.trim = ''
  engines.value = []
  transmissions.value = []
  drives.value = []
  trims.value = []

  if (form.year && form.make && form.model) {
    try {
      engines.value = await getEngines(form.year, form.make, form.model)
    } catch (err) {
      console.error('Failed to load engines:', err)
    }
  }
}

async function onEngineChange() {
  form.transmission = ''
  form.drive = ''
  form.trim = ''
  transmissions.value = []
  drives.value = []
  trims.value = []

  if (form.year && form.make && form.model && form.engine) {
    try {
      transmissions.value = await getTransmissions(form.year, form.make, form.model, form.engine)
    } catch (err) {
      console.error('Failed to load transmissions:', err)
      transmissions.value = []
      drives.value = []
      trims.value = []
      toast.error('Unable to load transmissions for the selected engine. Please try again.')
    }
  }
}

async function onTransmissionChange() {
  form.drive = ''
  form.trim = ''
  drives.value = []
  trims.value = []

  if (form.year && form.make && form.model && form.engine && form.transmission) {
    try {
      drives.value = await getDrives(form.year, form.make, form.model, form.engine, form.transmission)
    } catch (err) {
      console.error('Failed to load drives:', err)
    }
  }
}

async function onDriveChange() {
  form.trim = ''
  trims.value = []

  if (form.year && form.make && form.model && form.engine && form.transmission && form.drive) {
    try {
      trims.value = await getTrims(form.year, form.make, form.model, form.engine, form.transmission, form.drive)
    } catch (err) {
      console.error('Failed to load trims:', err)
    }
  }
}

async function loadVehicle() {
  try {
    const vehicle = await getCustomerVehicle(route.params.customerId, route.params.id)
    Object.assign(form, {
      customer_id: vehicle.customer_id,
      year: vehicle.year,
      make: vehicle.make,
      model: vehicle.model,
      engine: vehicle.engine || '',
      transmission: vehicle.transmission || '',
      drive: vehicle.drive || '',
      trim: vehicle.trim || '',
      vin: vehicle.vin || '',
      license_plate: vehicle.license_plate || '',
      mileage_in: vehicle.mileage_in || null,
      mileage_out: vehicle.mileage_out || null,
      notes: vehicle.notes || '',
    })

    await loadSelectedCustomer(vehicle.customer_id)

    // Load cascade dropdowns based on loaded values
    if (form.year) await onYearChange()
    if (form.make) {
      form.make = vehicle.make
      await onMakeChange()
    }
    if (form.model) {
      form.model = vehicle.model
      await onModelChange()
    }
    if (form.engine) {
      form.engine = vehicle.engine
      await onEngineChange()
    }
    if (form.transmission) {
      form.transmission = vehicle.transmission
      await onTransmissionChange()
    }
    if (form.drive) {
      form.drive = vehicle.drive
      await onDriveChange()
    }
    if (form.trim) {
      form.trim = vehicle.trim
    }
  } catch (err) {
    error.value = 'Failed to load vehicle'
    console.error(err)
  }
}

async function decodeVinNumber() {
  if (!form.vin || form.vin.length < 17) {
    vinError.value = 'VIN must be at least 17 characters'
    return
  }

  decoding.value = true
  vinError.value = ''
  vinSuccess.value = ''

  try {
    const decoded = await decodeVin(form.vin)

    if (decoded.year) {
      form.year = decoded.year
      await onYearChange()
    }
    if (decoded.make) {
      form.make = decoded.make
      await onMakeChange()
    }
    if (decoded.model) {
      form.model = decoded.model
      await onModelChange()
    }
    if (decoded.engine) {
      form.engine = decoded.engine
      await onEngineChange()
    }
    if (decoded.transmission) {
      form.transmission = decoded.transmission
      await onTransmissionChange()
    }
    if (decoded.drive) {
      form.drive = decoded.drive
      await onDriveChange()
    }
    if (decoded.trim) form.trim = decoded.trim

    vinSuccess.value = 'VIN decoded successfully!'
    toast.success('VIN decoded successfully!')
  } catch (err) {
    vinError.value = err.response?.data?.message || 'Failed to decode VIN'
    toast.error('Failed to decode VIN')
    console.error(err)
  } finally {
    decoding.value = false
  }
}

async function save() {
  saving.value = true
  error.value = ''
  success.value = ''

  if (!form.customer_id) {
    error.value = 'Please select a customer before saving.'
    saving.value = false
    return
  }

  try {
    if (isEditing.value) {
      await updateCustomerVehicle(form.customer_id, route.params.id, form)
      success.value = 'Vehicle updated successfully!'
      toast.success('Vehicle updated successfully!')
    } else {
      await createCustomerVehicle(form.customer_id, form)
      success.value = 'Vehicle added to customer garage successfully!'
      toast.success('Vehicle added to customer garage successfully!')
    }

    setTimeout(() => {
      router.push('/cp/vehicles')
    }, 1500)
  } catch (err) {
    error.value = err.response?.data?.message || 'Failed to save vehicle'
    toast.error('Failed to save vehicle')
    console.error(err)
  } finally {
    saving.value = false
  }
}

function goBack() {
  router.push('/cp/vehicles')
}
</script>
