// src/react/views/estimates/EstimateDetail.jsx
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import Alert from '../../components/ui/Alert'
import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import Input from '../../components/ui/Input'
import Loading from '../../components/ui/Loading'
import Modal from '../../components/ui/Modal'
import estimateService from '../../../services/estimate.service'
import { useToast } from '../../stores/toast'

const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount || 0)
}

const formatDate = (date) => {
  if (!date) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  }).format(new Date(date))
}

const formatStatus = (status) => {
  if (!status) return ''
  return status
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const getStatusVariant = (status) => {
  const variants = {
    sent: 'info',
    pending: 'default',
    approved: 'success',
    rejected: 'danger',
    expired: 'warning',
    converted: 'success',
  }
  return variants[status?.toLowerCase()] || 'default'
}

const isExpired = (expirationDate) => {
  if (!expirationDate) return false
  return new Date(expirationDate) < new Date()
}

const isExpiringSoon = (expirationDate) => {
  if (!expirationDate) return false
  const expiry = new Date(expirationDate)
  const now = new Date()
  const daysUntilExpiry = (expiry - now) / (1000 * 60 * 60 * 24)
  return daysUntilExpiry > 0 && daysUntilExpiry <= 7
}

export default function EstimateDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { success, error } = useToast()

  const [loading, setLoading] = useState(true)
  const [converting, setConverting] = useState(false)
  const [estimate, setEstimate] = useState(null)
  const [loadError, setLoadError] = useState(null)
  const [showConvertModal, setShowConvertModal] = useState(false)
  const [convertForm, setConvertForm] = useState({
    issue_date: new Date().toISOString().split('T')[0],
    due_date: '',
  })

  const loadEstimate = useCallback(async () => {
    if (!id) return
    setLoading(true)
    setLoadError(null)
    try {
      const response = await estimateService.getEstimate(id)
      setEstimate(response.data)
    } catch (fetchError) {
      console.error('Failed to load estimate:', fetchError)
      setLoadError(fetchError.response?.data?.message || 'Failed to load estimate')
    } finally {
      setLoading(false)
    }
  }, [id])

  useEffect(() => {
    loadEstimate()
  }, [loadEstimate])

  const approveEstimate = async () => {
    if (!estimate) return
    try {
      await estimateService.approveEstimate(estimate.id)
      success('Estimate approved successfully')
      loadEstimate()
    } catch (approveError) {
      console.error('Failed to approve estimate:', approveError)
      error(approveError.response?.data?.message || 'Failed to approve estimate')
    }
  }

  const declineEstimate = async () => {
    if (!estimate) return
    if (!window.confirm('Are you sure you want to reject this estimate?')) return

    try {
      await estimateService.declineEstimate(estimate.id)
      success('Estimate rejected')
      loadEstimate()
    } catch (declineError) {
      console.error('Failed to reject estimate:', declineError)
      error(declineError.response?.data?.message || 'Failed to reject estimate')
    }
  }

  const expireEstimate = async () => {
    if (!estimate) return
    if (!window.confirm('Mark this estimate as expired?')) return

    try {
      await estimateService.expireEstimate(estimate.id)
      success('Estimate marked as expired')
      loadEstimate()
    } catch (expireError) {
      console.error('Failed to expire estimate:', expireError)
      error(expireError.response?.data?.message || 'Failed to expire estimate')
    }
  }

  const confirmConvert = async () => {
    if (!estimate) return
    setConverting(true)
    try {
      const response = await estimateService.convertToInvoice(estimate.id, {
        issue_date: convertForm.issue_date,
        due_date: convertForm.due_date || null,
      })

      success('Estimate converted to invoice successfully')
      setShowConvertModal(false)

      if (response.data?.id) {
        navigate(`/cp/invoices/${response.data.id}`)
      }
    } catch (convertError) {
      console.error('Failed to convert estimate:', convertError)
      error(convertError.response?.data?.message || 'Failed to convert estimate')
    } finally {
      setConverting(false)
    }
  }

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Loading size="xl" text="Loading estimate..." />
      </div>
    )
  }

  if (loadError) {
    return (
      <Alert variant="danger" className="mb-6">
        {loadError}
      </Alert>
    )
  }

  if (!estimate) {
    return (
      <div className="text-center py-12">
        <h3 className="text-lg font-medium text-gray-900">Estimate not found</h3>
        <p className="mt-2 text-gray-500">The estimate you&apos;re looking for doesn&apos;t exist.</p>
        <div className="mt-4">
          <Link to="/cp/estimates">
            <Button>Back to Estimates</Button>
          </Link>
        </div>
      </div>
    )
  }

  const isPendingOrSent = ['pending', 'sent'].includes(estimate.status)

  return (
    <div>
      <div className="mb-6">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-4">
            <Button variant="ghost" onClick={() => navigate(-1)}>
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
              </svg>
            </Button>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Estimate {estimate.number}</h1>
              <p className="text-sm text-gray-500">Created {formatDate(estimate.created_at)}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {estimate.is_mobile ? (
              <Badge variant="warning" size="lg">Mobile repair</Badge>
            ) : null}
            <Badge variant={getStatusVariant(estimate.status)} size="lg">
              {formatStatus(estimate.status)}
            </Badge>
          </div>
        </div>

        <div className="flex flex-wrap gap-2 mt-4">
          {isPendingOrSent ? (
            <Button variant="primary" onClick={approveEstimate}>Approve</Button>
          ) : null}
          {isPendingOrSent ? (
            <Button variant="danger" onClick={declineEstimate}>Reject</Button>
          ) : null}
          {estimate.status === 'approved' ? (
            <Button onClick={() => setShowConvertModal(true)}>Convert to Invoice</Button>
          ) : null}
          {isPendingOrSent ? (
            <Button variant="outline" onClick={expireEstimate}>Mark as Expired</Button>
          ) : null}
          <Button
            variant="outline"
            onClick={() => navigate(`/cp/estimates/${estimate.id}/edit`)}
          >
            <svg className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            Edit
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-900">Customer & Vehicle</h3>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium text-gray-500">Customer</label>
                <p className="mt-1 text-sm text-gray-900">
                  <Link
                    to={`/cp/customers/${estimate.customer_id}`}
                    className="text-primary-600 hover:text-primary-800"
                  >
                    Customer #{estimate.customer_id}
                  </Link>
                </p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-500">Vehicle</label>
                <p className="mt-1 text-sm text-gray-900">
                  <Link
                    to={`/cp/vehicles/${estimate.vehicle_id}`}
                    className="text-primary-600 hover:text-primary-800"
                  >
                    Vehicle #{estimate.vehicle_id}
                  </Link>
                </p>
              </div>
              {estimate.technician_id ? (
                <div>
                  <label className="text-sm font-medium text-gray-500">Technician</label>
                  <p className="mt-1 text-sm text-gray-900">Technician #{estimate.technician_id}</p>
                </div>
              ) : null}
              {estimate.expiration_date ? (
                <div>
                  <label className="text-sm font-medium text-gray-500">Expiration Date</label>
                  <p
                    className={`mt-1 text-sm ${isExpired(estimate.expiration_date) ? 'text-red-600 font-medium' : 'text-gray-900'}`}
                  >
                    {formatDate(estimate.expiration_date)}
                    {isExpired(estimate.expiration_date) ? (
                      <span className="text-xs"> (Expired)</span>
                    ) : null}
                    {!isExpired(estimate.expiration_date) && isExpiringSoon(estimate.expiration_date) ? (
                      <span className="text-xs text-amber-600"> (Expiring soon)</span>
                    ) : null}
                  </p>
                </div>
              ) : null}
            </div>
          </Card>

          {(estimate.customer_notes || estimate.internal_notes) ? (
            <Card>
              <div className="mb-4">
                <h3 className="text-lg font-medium text-gray-900">Notes</h3>
              </div>
              <div className="space-y-4">
                {estimate.customer_notes ? (
                  <div>
                    <label className="text-sm font-medium text-gray-500">Customer Notes</label>
                    <p className="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{estimate.customer_notes}</p>
                  </div>
                ) : null}
                {estimate.internal_notes ? (
                  <div>
                    <label className="text-sm font-medium text-gray-500">Internal Notes</label>
                    <p className="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{estimate.internal_notes}</p>
                  </div>
                ) : null}
              </div>
            </Card>
          ) : null}
        </div>

        <div>
          <Card>
            <div className="mb-4">
              <h3 className="text-lg font-medium text-gray-900">Summary</h3>
            </div>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Subtotal</span>
                <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.subtotal)}</span>
              </div>
              {estimate.call_out_fee > 0 ? (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Call-out Fee</span>
                  <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.call_out_fee)}</span>
                </div>
              ) : null}
              {estimate.mileage_total > 0 ? (
                <div className="flex justify-between">
                  <span className="text-sm text-gray-600">Mileage</span>
                  <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.mileage_total)}</span>
                </div>
              ) : null}
              {estimate.discounts > 0 ? (
                <div className="flex justify-between text-green-600">
                  <span className="text-sm">Discounts</span>
                  <span className="text-sm font-medium">-{formatCurrency(estimate.discounts)}</span>
                </div>
              ) : null}
              <div className="flex justify-between">
                <span className="text-sm text-gray-600">Tax</span>
                <span className="text-sm font-medium text-gray-900">{formatCurrency(estimate.tax)}</span>
              </div>
              <div className="border-t border-gray-200 pt-3 flex justify-between">
                <span className="text-base font-medium text-gray-900">Grand Total</span>
                <span className="text-base font-bold text-gray-900">{formatCurrency(estimate.grand_total)}</span>
              </div>
            </div>
          </Card>
        </div>
      </div>

      <Modal
        open={showConvertModal}
        onClose={() => setShowConvertModal(false)}
        title="Convert to Invoice"
        content={(
          <div className="space-y-4">
            <p className="text-sm text-gray-600">
              Convert estimate #{estimate?.number} to an invoice?
            </p>
            <div>
              <label className="block text-sm font-medium text-gray-700">Issue Date *</label>
              <Input
                value={convertForm.issue_date}
                type="date"
                className="mt-1"
                required
                onUpdateModelValue={(value) => setConvertForm((prev) => ({ ...prev, issue_date: value }))}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Due Date (Optional)</label>
              <Input
                value={convertForm.due_date}
                type="date"
                className="mt-1"
                onUpdateModelValue={(value) => setConvertForm((prev) => ({ ...prev, due_date: value }))}
              />
            </div>
          </div>
        )}
        footer={(
          <div className="flex gap-3 justify-end">
            <Button variant="outline" onClick={() => setShowConvertModal(false)}>Cancel</Button>
            <Button
              onClick={confirmConvert}
              disabled={!convertForm.issue_date || converting}
              loading={converting}
            >
              {converting ? 'Converting...' : 'Convert to Invoice'}
            </Button>
          </div>
        )}
      />
    </div>
  )
}

// old-views/estimates/EstimateDetail.vue
<template>
  <div>
    <div v-if="loading" class="flex justify-center py-12">
      <Loading size="xl" text="Loading estimate..." />
    </div>

    <Alert v-else-if="error" variant="danger" class="mb-6">
      {{ error }}
    </Alert>

    <div v-else-if="estimate">
      <div class="mb-6">
        <div class="flex items-center justify-between mb-2">
          <div class="flex items-center gap-4">
            <Button variant="ghost" @click="$router.back()">
              <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            </Button>
            <div>
              <h1 class="text-2xl font-bold text-gray-900">Estimate {{ estimate.number }}</h1>
              <p class="text-sm text-gray-500">Created {{ formatDate(estimate.created_at) }}</p>
            </div>
          </div>
          <div class="flex items-center gap-2">
            <Badge v-if="estimate.is_mobile" variant="warning" size="lg">Mobile repair</Badge>
            <Badge :variant="getStatusVariant(estimate.status)" size="lg">
              {{ formatStatus(estimate.status) }}
            </Badge>
          </div>
        </div>

        <div class="flex flex-wrap gap-2 mt-4">
          <Button
            variant="outline"
            @click="openShareEmailModal"
          >
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            Share via Email
          </Button>
          <Button
            variant="outline"
            @click="openShareSmsModal"
          >
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
            Share via SMS
          </Button>

          <div class="w-px bg-gray-300 mx-1"></div>

          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="primary"
            @click="approveEstimate"
          >
            Approve
          </Button>
          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="danger"
            @click="declineEstimate"
          >
            Reject
          </Button>
          <Button
            v-if="estimate.status === 'approved' || estimate.status === 'partial'"
            variant="primary"
            @click="showWorkorderModal = true"
          >
            Create Workorder
          </Button>
          <Button
            v-if="estimate.status === 'approved' || estimate.status === 'partial'"
            @click="showConvertModal = true"
          >
            Convert to Invoice
          </Button>
          <Button
            v-if="['pending', 'sent'].includes(estimate.status)"
            variant="outline"
            @click="expireEstimate"
          >
            Mark as Expired
          </Button>
          <Button
            variant="outline"
            @click="$router.push(`/cp/estimates/${estimate.id}/edit`)"
          >
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
            </svg>
            Edit
          </Button>
          <Button
            variant="danger"
            @click="deleteEstimate"
          >
            <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          </Button>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2 space-y-6">
          <Card>
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Customer & Vehicle</h3>
            </template>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="text-sm font-medium text-gray-500">Customer</label>
                <div class="mt-1 text-sm">
                  <router-link
                    :to="`/cp/customers/${estimate.customer_id}`"
                    class="text-primary-600 hover:text-primary-800 font-medium"
                  >
                    {{ estimate.customer?.name || `Customer #${estimate.customer_id}` }}
                  </router-link>
                  <p v-if="estimate.customer?.phone" class="text-gray-600">{{ estimate.customer.phone }}</p>
                  <p v-if="estimate.customer?.email" class="text-gray-600">{{ estimate.customer.email }}</p>
                </div>
              </div>
              <div>
                <label class="text-sm font-medium text-gray-500">Vehicle</label>
                <div class="mt-1 text-sm">
                  <router-link
                    :to="`/cp/vehicles/${estimate.vehicle_id}`"
                    class="text-primary-600 hover:text-primary-800 font-medium"
                  >
                    <span v-if="estimate.vehicle?.year || estimate.vehicle?.make || estimate.vehicle?.model">
                      {{ estimate.vehicle.year }} {{ estimate.vehicle.make }} {{ estimate.vehicle.model }}
                    </span>
                    <span v-else>Vehicle #{{ estimate.vehicle_id }}</span>
                  </router-link>
                  <p v-if="estimate.vehicle?.vin" class="text-gray-600">VIN: {{ estimate.vehicle.vin }}</p>
                  <p v-if="estimate.vehicle?.license_plate" class="text-gray-600">Plate: {{ estimate.vehicle.license_plate }}</p>
                </div>
              </div>
              <div v-if="estimate.technician_id">
                <label class="text-sm font-medium text-gray-500">Technician</label>
                <p class="mt-1 text-sm text-gray-900">Technician #{{ estimate.technician_id }}</p>
              </div>
              <div v-if="estimate.expiration_date">
                <label class="text-sm font-medium text-gray-500">Expiration Date</label>
                <p
                  class="mt-1 text-sm"
                  :class="isExpired(estimate.expiration_date) ? 'text-red-600 font-medium' : 'text-gray-900'"
                >
                  {{ formatDate(estimate.expiration_date) }}
                  <span v-if="isExpired(estimate.expiration_date)" class="text-xs">(Expired)</span>
                  <span v-else-if="isExpiringSoon(estimate.expiration_date)" class="text-xs text-amber-600">(Expiring soon)</span>
                </p>
              </div>
            </div>
          </Card>

          <!-- Jobs Breakdown -->
          <Card v-if="estimate.jobs && estimate.jobs.length > 0">
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Jobs & Line Items</h3>
            </template>
            <div class="space-y-6">
              <div
                v-for="(job, jobIndex) in estimate.jobs"
                :key="job.id || jobIndex"
                class="border border-gray-200 rounded-lg overflow-hidden"
              >
                <!-- Job Header -->
                <div class="bg-gray-50 px-4 py-3 border-b border-gray-200 flex justify-between items-start">
                  <div>
                    <h4 class="font-medium text-gray-900">{{ job.title || `Job ${jobIndex + 1}` }}</h4>
                    <p v-if="job.notes" class="mt-1 text-sm text-gray-600">{{ job.notes }}</p>
                  </div>
                  <Badge
                    v-if="job.customer_status"
                    :variant="job.customer_status === 'approved' ? 'success' : job.customer_status === 'rejected' ? 'danger' : 'default'"
                    size="sm"
                  >
                    {{ job.customer_status === 'approved' ? 'Approved' : job.customer_status === 'rejected' ? 'Rejected' : 'Pending' }}
                  </Badge>
                </div>

                <!-- Line Items Table -->
                <div class="overflow-x-auto">
                  <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                      <tr>
                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                        <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Qty</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Unit Price</th>
                        <th class="px-4 py-2 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Total</th>
                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                      <tr v-for="(item, itemIndex) in job.items" :key="item.id || itemIndex">
                        <td class="px-4 py-2 whitespace-nowrap">
                          <Badge :variant="item.type === 'LABOR' ? 'info' : 'default'" size="sm">
                            {{ item.type === 'LABOR' ? 'Labor' : 'Part' }}
                          </Badge>
                        </td>
                        <td class="px-4 py-2">
                          <div class="text-sm text-gray-900">{{ item.description }}</div>
                          <div v-if="item.sku" class="text-xs text-gray-500">SKU: {{ item.sku }}</div>
                        </td>
                        <td class="px-4 py-2 text-right text-sm text-gray-900 whitespace-nowrap">
                          {{ item.quantity }}
                        </td>
                        <td class="px-4 py-2 text-right text-sm text-gray-900 whitespace-nowrap">
                          {{ formatCurrency(item.unit_price) }}
                        </td>
                        <td class="px-4 py-2 text-right text-sm font-medium text-gray-900 whitespace-nowrap">
                          {{ formatCurrency(item.quantity * item.unit_price) }}
                        </td>
                      </tr>
                    </tbody>
                    <tfoot class="bg-gray-50">
                      <tr>
                        <td colspan="4" class="px-4 py-2 text-right text-sm font-medium text-gray-700">
                          Job Subtotal
                        </td>
                        <td class="px-4 py-2 text-right text-sm font-bold text-gray-900">
                          {{ formatCurrency(calculateJobSubtotal(job)) }}
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
            </div>
          </Card>

          <Card v-if="estimate.customer_notes || estimate.internal_notes">
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Notes</h3>
            </template>
            <div class="space-y-4">
              <div v-if="estimate.customer_notes">
                <label class="text-sm font-medium text-gray-500">Customer Notes</label>
                <p class="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{{ estimate.customer_notes }}</p>
              </div>
              <div v-if="estimate.internal_notes">
                <label class="text-sm font-medium text-gray-500">Internal Notes</label>
                <p class="mt-1 text-sm text-gray-900 whitespace-pre-wrap">{{ estimate.internal_notes }}</p>
              </div>
            </div>
          </Card>
        </div>

        <div>
          <Card>
            <template #header>
              <h3 class="text-lg font-medium text-gray-900">Summary</h3>
            </template>
            <div class="space-y-3">
              <div class="flex justify-between">
                <span class="text-sm text-gray-600">Subtotal</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.subtotal) }}</span>
              </div>
              <div v-if="estimate.call_out_fee > 0" class="flex justify-between">
                <span class="text-sm text-gray-600">Call-out Fee</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.call_out_fee) }}</span>
              </div>
              <div v-if="estimate.mileage_total > 0" class="flex justify-between">
                <span class="text-sm text-gray-600">Mileage</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.mileage_total) }}</span>
              </div>
              <div v-if="estimate.discounts > 0" class="flex justify-between text-green-600">
                <span class="text-sm">Discounts</span>
                <span class="text-sm font-medium">-{{ formatCurrency(estimate.discounts) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-sm text-gray-600">Tax</span>
                <span class="text-sm font-medium text-gray-900">{{ formatCurrency(estimate.tax) }}</span>
              </div>
              <div class="border-t border-gray-200 pt-3 flex justify-between">
                <span class="text-base font-medium text-gray-900">Grand Total</span>
                <span class="text-base font-bold text-gray-900">{{ formatCurrency(estimate.grand_total) }}</span>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>

    <Modal v-model="showConvertModal" @close="showConvertModal = false">
      <template #title>Convert to Invoice</template>
      <template #content>
        <div class="space-y-4">
          <p class="text-sm text-gray-600">
            Convert estimate #{{ estimate?.number }} to an invoice?
          </p>
          <div>
            <label class="block text-sm font-medium text-gray-700">Issue Date *</label>
            <Input
              v-model="convertForm.issue_date"
              type="date"
              class="mt-1"
              required
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Due Date (Optional)</label>
            <Input
              v-model="convertForm.due_date"
              type="date"
              class="mt-1"
            />
          </div>
        </div>
      </template>
      <template #footer>
        <Button variant="outline" @click="showConvertModal = false">Cancel</Button>
        <Button @click="confirmConvert" :disabled="!convertForm.issue_date || converting">
          {{ converting ? 'Converting...' : 'Convert to Invoice' }}
        </Button>
      </template>
    </Modal>

    <Modal v-model="showWorkorderModal" @close="showWorkorderModal = false">
      <template #title>Create Workorder</template>
      <template #content>
        <div class="space-y-4">
          <p class="text-sm text-gray-600">
            Create a workorder from estimate #{{ estimate?.number }}?
          </p>
          <Alert variant="info">
            A workorder will be created with all approved jobs from this estimate.
            You can then track work progress and assign technicians.
          </Alert>
          <div>
            <label class="block text-sm font-medium text-gray-700">Assign Technician (Optional)</label>
            <Select
              v-model="workorderForm.technician_id"
              :options="technicianOptions"
              placeholder="Select technician"
              class="mt-1"
            />
          </div>
        </div>
      </template>
      <template #footer>
        <Button variant="outline" @click="showWorkorderModal = false">Cancel</Button>
        <Button @click="confirmCreateWorkorder" :disabled="creatingWorkorder">
          {{ creatingWorkorder ? 'Creating...' : 'Create Workorder' }}
        </Button>
      </template>
    </Modal>

    <Modal v-model="showShareEmailModal" @close="showShareEmailModal = false">
      <template #title>Share Estimate via Email</template>
      <template #content>
        <div class="space-y-4">
          <p class="text-sm text-gray-600">
            Send estimate #{{ estimate?.number }} to the customer via email.
          </p>
          <div>
            <label class="block text-sm font-medium text-gray-700">Email Address *</label>
            <Input
              v-model="shareEmailForm.email"
              type="email"
              placeholder="customer@example.com"
              class="mt-1"
              required
            />
          </div>
          <Alert variant="info" class="text-xs">
            The customer will receive a secure link to view and approve/reject this estimate.
          </Alert>
        </div>
      </template>
      <template #footer>
        <Button variant="outline" @click="showShareEmailModal = false">Cancel</Button>
        <Button @click="sendShareEmail" :disabled="!shareEmailForm.email || sendingEmail">
          <svg v-if="sendingEmail" class="animate-spin h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          {{ sendingEmail ? 'Sending...' : 'Send Email' }}
        </Button>
      </template>
    </Modal>

    <Modal v-model="showShareSmsModal" @close="showShareSmsModal = false">
      <template #title>Share Estimate via SMS</template>
      <template #content>
        <div class="space-y-4">
          <p class="text-sm text-gray-600">
            Send estimate #{{ estimate?.number }} to the customer via SMS.
          </p>
          <div>
            <label class="block text-sm font-medium text-gray-700">Phone Number *</label>
            <Input
              v-model="sharesSmsForm.phone"
              type="tel"
              placeholder="+1 (555) 123-4567"
              class="mt-1"
              required
            />
          </div>
          <Alert variant="info" class="text-xs">
            The customer will receive a text message with a secure link to view this estimate.
          </Alert>
        </div>
      </template>
      <template #footer>
        <Button variant="outline" @click="showShareSmsModal = false">Cancel</Button>
        <Button @click="sendShareSms" :disabled="!sharesSmsForm.phone || sendingSms">
          <svg v-if="sendingSms" class="animate-spin h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
          {{ sendingSms ? 'Sending...' : 'Send SMS' }}
        </Button>
      </template>
    </Modal>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import Card from '@/components/ui/Card.vue'
import Button from '@/components/ui/Button.vue'
import Badge from '@/components/ui/Badge.vue'
import Input from '@/components/ui/Input.vue'
import Select from '@/components/ui/Select.vue'
import Alert from '@/components/ui/Alert.vue'
import Loading from '@/components/ui/Loading.vue'
import Modal from '@/components/ui/Modal.vue'
import estimateService from '@/services/estimate.service'
import workorderService from '@/services/workorder.service'
import userService from '@/services/user.service'
import { useToast } from '@/stores/toast'

const router = useRouter()
const route = useRoute()
const toast = useToast()

const loading = ref(true)
const converting = ref(false)
const creatingWorkorder = ref(false)
const error = ref(null)
const estimate = ref(null)
const technicians = ref([])

// Calculate job approval stats for partial status display
const jobApprovalStats = computed(() => {
  if (!estimate.value?.jobs || estimate.value.jobs.length === 0) return null
  const jobs = estimate.value.jobs
  const total = jobs.length
  const approved = jobs.filter(j => j.customer_status === 'approved').length
  const rejected = jobs.filter(j => j.customer_status === 'rejected').length
  const pending = total - approved - rejected
  return { total, approved, rejected, pending }
})
const showConvertModal = ref(false)
const showWorkorderModal = ref(false)
const showShareEmailModal = ref(false)
const showShareSmsModal = ref(false)
const sendingEmail = ref(false)
const sendingSms = ref(false)

const convertForm = reactive({
  issue_date: new Date().toISOString().split('T')[0],
  due_date: ''
})

const workorderForm = reactive({
  technician_id: ''
})

const shareEmailForm = reactive({
  email: ''
})

const sharesSmsForm = reactive({
  phone: ''
})

const technicianOptions = ref([{ value: '', label: 'Unassigned' }])

onMounted(() => {
  loadEstimate()
  loadTechnicians()
})

async function loadEstimate() {
  try {
    loading.value = true
    error.value = null
    const response = await estimateService.getEstimate(route.params.id)
    estimate.value = response.data
  } catch (err) {
    console.error('Failed to load estimate:', err)
    error.value = err.response?.data?.message || 'Failed to load estimate'
  } finally {
    loading.value = false
  }
}

async function loadTechnicians() {
  try {
    const users = await userService.listUsers({ role: 'technician' }) || []
    technicians.value = users
    technicianOptions.value = [
      { value: '', label: 'Unassigned' },
      ...technicians.value.map(u => ({ value: u.id, label: u.name }))
    ]
  } catch (err) {
    console.error('Failed to load technicians:', err)
  }
}

async function confirmCreateWorkorder() {
  try {
    creatingWorkorder.value = true
    const response = await workorderService.createFromEstimate(
      estimate.value.id,
      workorderForm.technician_id || null
    )

    toast.success('Workorder created successfully')
    showWorkorderModal.value = false

    // Redirect to the new workorder
    if (response.data?.id) {
      router.push(`/cp/workorders/${response.data.id}`)
    }
  } catch (err) {
    console.error('Failed to create workorder:', err)
    toast.error(err.response?.data?.error || 'Failed to create workorder')
  } finally {
    creatingWorkorder.value = false
  }
}

async function approveEstimate() {
  try {
    await estimateService.approveEstimate(estimate.value.id)
    toast.success('Estimate approved successfully')
    loadEstimate()
  } catch (err) {
    console.error('Failed to approve estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to approve estimate')
  }
}

async function declineEstimate() {
  if (!confirm('Are you sure you want to reject this estimate?')) return

  try {
    await estimateService.declineEstimate(estimate.value.id)
    toast.success('Estimate rejected')
    loadEstimate()
  } catch (err) {
    console.error('Failed to reject estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to reject estimate')
  }
}

async function requestReapproval() {
  try {
    await estimateService.requestReapproval(estimate.value.id)
    toast.success('Reapproval requested')
    loadEstimate()
  } catch (err) {
    console.error('Failed to request reapproval:', err)
    toast.error(err.response?.data?.message || 'Failed to request reapproval')
  }
}

async function expireEstimate() {
  if (!confirm('Mark this estimate as expired?')) return

  try {
    await estimateService.expireEstimate(estimate.value.id)
    toast.success('Estimate marked as expired')
    loadEstimate()
  } catch (err) {
    console.error('Failed to expire estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to expire estimate')
  }
}

async function confirmConvert() {
  try {
    converting.value = true
    const response = await estimateService.convertToInvoice(estimate.value.id, {
      issue_date: convertForm.issue_date,
      due_date: convertForm.due_date || null
    })

    toast.success('Estimate converted to invoice successfully')
    showConvertModal.value = false

    // Redirect to the new invoice
    if (response.data?.id) {
      router.push(`/cp/invoices/${response.data.id}`)
    }
  } catch (err) {
    console.error('Failed to convert estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to convert estimate')
  } finally {
    converting.value = false
  }
}

async function deleteEstimate() {
  if (!confirm('Are you sure you want to delete this estimate? This action cannot be undone.')) return

  try {
    await estimateService.deleteEstimate(estimate.value.id)
    toast.success('Estimate deleted successfully')
    router.push('/cp/estimates')
  } catch (err) {
    console.error('Failed to delete estimate:', err)
    toast.error(err.response?.data?.message || 'Failed to delete estimate')
  }
}

function openShareEmailModal() {
  // Pre-fill with customer email if available
  shareEmailForm.email = estimate.value?.customer?.email
    || estimate.value?.customer_email
    || estimate.value?.customerEmail
    || ''
  showShareEmailModal.value = true
}

function openShareSmsModal() {
  // Pre-fill with customer phone if available
  sharesSmsForm.phone = estimate.value?.customer?.phone || ''
  showShareSmsModal.value = true
}

async function sendShareEmail() {
  if (!shareEmailForm.email) return

  try {
    sendingEmail.value = true
    await estimateService.shareViaEmail(estimate.value.id, shareEmailForm.email)
    toast.success('Estimate sent via email successfully')
    showShareEmailModal.value = false
    shareEmailForm.email = ''
  } catch (err) {
    console.error('Failed to send estimate via email:', err)
    toast.error(err.response?.data?.message || 'Failed to send email')
  } finally {
    sendingEmail.value = false
  }
}

async function sendShareSms() {
  if (!sharesSmsForm.phone) return

  try {
    sendingSms.value = true
    await estimateService.shareViaSms(estimate.value.id, sharesSmsForm.phone)
    toast.success('Estimate sent via SMS successfully')
    showShareSmsModal.value = false
    sharesSmsForm.phone = ''
  } catch (err) {
    console.error('Failed to send estimate via SMS:', err)
    toast.error(err.response?.data?.message || 'Failed to send SMS')
  } finally {
    sendingSms.value = false
  }
}

function getStatusVariant(status) {
  const variants = {
    sent: 'info',
    pending: 'default',
    approved: 'success',
    rejected: 'danger',
    declined: 'danger',
    partial: 'warning',
    expired: 'warning',
    converted: 'success'
  }
  return variants[status?.toLowerCase()] || 'default'
}

function formatStatus(status) {
  if (status === 'partial' && jobApprovalStats.value) {
    const stats = jobApprovalStats.value
    return `${stats.approved}/${stats.total} Jobs Approved`
  }
  if (status === 'declined') {
    return 'Declined'
  }
  return status
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function formatCurrency(amount) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  }).format(amount || 0)
}

function formatDate(date) {
  if (!date) return ''
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  }).format(new Date(date))
}

function isExpired(expirationDate) {
  if (!expirationDate) return false
  return new Date(expirationDate) < new Date()
}

function isExpiringSoon(expirationDate) {
  if (!expirationDate) return false
  const expiry = new Date(expirationDate)
  const now = new Date()
  const daysUntilExpiry = (expiry - now) / (1000 * 60 * 60 * 24)
  return daysUntilExpiry > 0 && daysUntilExpiry <= 7
}

function calculateJobSubtotal(job) {
  if (!job.items || !job.items.length) return 0
  return job.items.reduce((sum, item) => {
    const quantity = Number(item.quantity) || 0
    const unitPrice = Number(item.unit_price) || 0
    return sum + (quantity * unitPrice)
  }, 0)
}
</script>
