// src/react/views/time/TechnicianPortal.jsx
// TODO: Add clock-in/clock-out timer controls. v1 is read-only; the supporting
// endpoints (/api/time-tracking/start, /api/time-tracking/:id/stop) already
// exist on the backend and on timeTrackingService — wire them up in a follow-up.

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

import Badge from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import timeTrackingService from '../../../services/time-tracking.service'
import { useAuthStore } from '../../stores/auth'

const HISTORY_LIMIT = 10
const ACTIVE_TIMER_TICK_MS = 1000 * 30

const formatMinutesAsHM = (value) => {
  const total = Math.max(0, Math.round(Number(value || 0)))
  const hours = Math.floor(total / 60)
  const minutes = total % 60
  if (hours === 0) return `${minutes}m`
  return `${hours}h ${minutes}m`
}

const formatDateTime = (value) => {
  if (!value) return '—'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleString()
}

const formatDate = (value) => {
  if (!value) return '—'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleDateString()
}

const elapsedMinutesSince = (startedAt) => {
  if (!startedAt) return 0
  const start = new Date(startedAt).getTime()
  if (Number.isNaN(start)) return 0
  return Math.max(0, (Date.now() - start) / 1000 / 60)
}

const customerStatusVariant = (status) => {
  const value = (status || '').toLowerCase()
  if (value === 'approved') return 'success'
  if (value === 'rejected' || value === 'declined') return 'danger'
  if (value === 'pending') return 'warning'
  return 'secondary'
}

const entryStatusVariant = (status) => {
  const value = (status || '').toLowerCase()
  if (value === 'approved') return 'success'
  if (value === 'rejected') return 'danger'
  if (value === 'pending') return 'warning'
  return 'secondary'
}

const formatStatusLabel = (value) => {
  if (!value) return 'Unknown'
  return value.charAt(0).toUpperCase() + value.slice(1)
}

export default function TechnicianPortal() {
  const { user } = useAuthStore()
  const role = (user?.role || '').toLowerCase()
  const isTechnician = role === 'technician'

  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [data, setData] = useState(null)
  const [now, setNow] = useState(() => Date.now())

  const fetchPortal = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const response = await timeTrackingService.technicianPortal()
      setData(response || null)
    } catch (fetchError) {
      setError(fetchError.response?.data?.message || 'Unable to load your time summary. Please try again.')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (!isTechnician) return
    fetchPortal()
  }, [fetchPortal, isTechnician])

  // Tick once every 30s so the active timer's "elapsed" stays roughly fresh
  // without burning a re-render every second.
  useEffect(() => {
    if (!data?.active_entry) return undefined
    const handle = window.setInterval(() => setNow(Date.now()), ACTIVE_TIMER_TICK_MS)
    return () => window.clearInterval(handle)
  }, [data?.active_entry])

  const jobs = useMemo(() => Array.isArray(data?.jobs) ? data.jobs : [], [data])
  const history = useMemo(() => {
    const all = Array.isArray(data?.history) ? data.history : []
    // entriesForTechnician on the backend returns entries newest-first by default,
    // but we sort defensively in case ordering changes.
    return [...all]
      .sort((a, b) => new Date(b.started_at || 0).getTime() - new Date(a.started_at || 0).getTime())
      .slice(0, HISTORY_LIMIT)
  }, [data])

  const activeEntry = data?.active_entry || null
  const activeElapsedMinutes = activeEntry ? elapsedMinutesSince(activeEntry.started_at) : 0
  // `now` participates in the calculation indirectly via Date.now() above; the
  // dependency below silences exhaustive-deps without changing behavior.
  void now

  const totals = data?.totals || { today_minutes: 0, week_minutes: 0 }

  if (!isTechnician) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">My Time</h1>
        </div>
        <Card>
          <p className="text-sm text-gray-600">
            This view is only available for technicians. If you believe you should have access,
            contact an administrator.
          </p>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">My Time</h1>
          <p className="text-sm text-gray-600">
            Your assigned jobs, active timer, and recent time entries.
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={fetchPortal} loading={loading}>
            Refresh
          </Button>
        </div>
      </div>

      {error ? (
        <Card>
          <p className="text-sm text-red-600">{error}</p>
        </Card>
      ) : null}

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <Card>
          <p className="text-xs font-medium uppercase tracking-wide text-gray-500">Today</p>
          <p className="mt-2 text-3xl font-semibold text-gray-900">
            {formatMinutesAsHM(totals.today_minutes)}
          </p>
          <p className="mt-1 text-xs text-gray-500">Approved time logged today</p>
        </Card>
        <Card>
          <p className="text-xs font-medium uppercase tracking-wide text-gray-500">This Week</p>
          <p className="mt-2 text-3xl font-semibold text-gray-900">
            {formatMinutesAsHM(totals.week_minutes)}
          </p>
          <p className="mt-1 text-xs text-gray-500">Approved time logged since Monday</p>
        </Card>
      </div>

      <Card title="Active timer">
        {activeEntry ? (
          <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div className="flex items-center gap-2">
                <Badge variant="success" size="sm" dot>
                  Running
                </Badge>
                {activeEntry.task_name ? (
                  <span className="text-sm font-medium text-gray-900">{activeEntry.task_name}</span>
                ) : null}
              </div>
              <p className="mt-2 text-sm text-gray-700">
                Started {formatDateTime(activeEntry.started_at)}
              </p>
              {activeEntry.estimate_job_id ? (
                <p className="text-xs text-gray-500">Job #{activeEntry.estimate_job_id}</p>
              ) : null}
            </div>
            <div className="text-left sm:text-right">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-500">Elapsed</p>
              <p className="mt-1 text-2xl font-semibold text-gray-900">
                {formatMinutesAsHM(activeElapsedMinutes)}
              </p>
            </div>
          </div>
        ) : (
          <p className="text-sm text-gray-600">No active timer.</p>
        )}
      </Card>

      <Card title="Assigned jobs">
        {loading && jobs.length === 0 ? (
          <p className="text-sm text-gray-500">Loading...</p>
        ) : jobs.length === 0 ? (
          <p className="text-sm text-gray-500">No jobs assigned to you right now.</p>
        ) : (
          <ul className="divide-y divide-gray-100">
            {jobs.map((job) => {
              const row = (
                <div className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between">
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-sm font-semibold text-gray-900">
                        {job.title || 'Untitled job'}
                      </span>
                      {job.estimate_number ? (
                        <span className="text-xs text-gray-500">#{job.estimate_number}</span>
                      ) : null}
                      {job.is_mobile ? (
                        <Badge variant="info" size="sm">Mobile</Badge>
                      ) : null}
                    </div>
                    <p className="mt-1 text-xs text-gray-600">
                      {job.customer_name || 'Unknown customer'}
                      {job.vehicle_vin ? <span className="text-gray-400"> · VIN {job.vehicle_vin}</span> : null}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant={customerStatusVariant(job.customer_status)} size="sm">
                      {formatStatusLabel(job.customer_status)}
                    </Badge>
                  </div>
                </div>
              )

              return (
                <li key={job.id}>
                  {job.estimate_number ? (
                    <Link
                      to={`/cp/estimates/${job.id}`}
                      className="-mx-2 block rounded px-2 hover:bg-gray-50"
                    >
                      {row}
                    </Link>
                  ) : (
                    <div className="-mx-2 px-2">{row}</div>
                  )}
                </li>
              )
            })}
          </ul>
        )}
      </Card>

      <Card title="Recent time entries">
        {loading && history.length === 0 ? (
          <p className="text-sm text-gray-500">Loading...</p>
        ) : history.length === 0 ? (
          <p className="text-sm text-gray-500">No time entries yet.</p>
        ) : (
          <ul className="divide-y divide-gray-100">
            {history.map((entry) => (
              <li key={entry.id} className="flex flex-col gap-1 py-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-900">
                    {formatDate(entry.started_at)}
                  </p>
                  <p className="text-xs text-gray-500">
                    {formatDateTime(entry.started_at)}
                    {entry.ended_at ? ` → ${formatDateTime(entry.ended_at)}` : ''}
                  </p>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-sm font-semibold text-gray-900">
                    {formatMinutesAsHM(entry.duration_minutes)}
                  </span>
                  <Badge variant={entryStatusVariant(entry.status)} size="sm">
                    {formatStatusLabel(entry.status)}
                  </Badge>
                </div>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  )
}

// src/views/time/TechnicianPortal.vue
<template>
  <div class="space-y-6">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">My Time</h1>
        <p class="text-sm text-gray-600">Review assignments and control your timer.</p>
      </div>
      <Button variant="secondary" @click="loadPortal">Refresh</Button>
    </div>

    <p v-if="portalError" class="text-sm text-red-600">{{ portalError }}</p>

    <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
      <Card class="md:col-span-2 space-y-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm text-gray-600">Active timer</p>
            <p class="text-xl font-semibold text-gray-900">
              {{ portal.active_entry ? `Started ${formatTime(portal.active_entry.started_at)}` : 'No active timer' }}
            </p>
            <p v-if="portal.active_entry?.is_mobile" class="text-xs text-amber-700">Mobile repair — location required on stop.</p>
          </div>
          <div class="flex gap-2">
            <Button v-if="!portal.active_entry" :loading="saving" @click="startTimer">Start</Button>
            <Button v-else variant="danger" :loading="saving" @click="stopTimer">Stop</Button>
          </div>
        </div>

        <p v-if="locationError" class="text-sm text-red-600">{{ locationError }}</p>

        <div class="grid grid-cols-1 gap-3 md:grid-cols-2">
          <div>
            <label class="block text-sm font-medium text-gray-700">Assign to job</label>
            <select
              v-model="selectedJobId"
              class="mt-1 w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
              <option value="">Unassigned</option>
              <option v-for="job in portal.jobs" :key="job.id" :value="job.id">
                {{ job.title }} ({{ job.estimate_number }})
              </option>
            </select>
          </div>
          <div class="rounded-md bg-gray-50 p-3 text-sm text-gray-700">
            <p class="font-semibold">Today</p>
            <p>{{ Number(portal.totals.today_minutes || 0).toFixed(2) }} minutes</p>
            <p class="font-semibold mt-2">This week</p>
            <p>{{ Number(portal.totals.week_minutes || 0).toFixed(2) }} minutes</p>
            <p class="mt-2 text-[11px] text-gray-500">Pending manual entries are excluded until approved.</p>
          </div>
        </div>

        <div>
          <h3 class="text-lg font-semibold text-gray-900 mb-2">Assigned jobs</h3>
          <div v-if="portal.jobs.length === 0" class="rounded border border-dashed border-gray-300 p-4 text-sm text-gray-600">
            No jobs assigned.
          </div>
          <div v-else class="grid grid-cols-1 gap-3 md:grid-cols-2">
            <Card v-for="job in portal.jobs" :key="job.id" class="border border-gray-200">
              <p class="font-semibold text-gray-900">{{ job.title }}</p>
              <p class="text-xs text-gray-600">Estimate {{ job.estimate_number }}</p>
              <p v-if="job.is_mobile" class="text-[11px] font-medium text-amber-700">Mobile repair</p>
              <p class="text-xs text-gray-500">Customer: {{ job.customer_name }}</p>
              <p class="text-xs text-gray-500">Vehicle: {{ job.vehicle_vin || '—' }}</p>
            </Card>
          </div>
        </div>
      </Card>

      <Card>
        <h3 class="text-lg font-semibold text-gray-900 mb-2">Recent entries</h3>
        <div v-if="portal.history.length === 0" class="text-sm text-gray-600">No recorded time entries yet.</div>
        <ul v-else class="divide-y divide-gray-200">
          <li v-for="entry in portal.history" :key="entry.id" class="py-2">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm font-semibold text-gray-900">{{ formatTime(entry.started_at) }}</p>
                <p class="text-xs text-gray-500">{{ entry.ended_at ? formatTime(entry.ended_at) : 'Active' }}</p>
              </div>
              <div class="flex flex-col items-end gap-1">
                <Badge :variant="entry.manual_override ? 'warning' : 'secondary'">
                  {{ entry.manual_override ? 'Manual' : 'Timer' }}
                </Badge>
                <Badge :variant="statusVariant(entry.status)" size="sm">{{ statusLabel(entry.status) }}</Badge>
              </div>
            </div>
            <p class="text-xs text-gray-500">Duration: {{ Number(entry.duration_minutes || 0).toFixed(2) }} mins</p>
          </li>
        </ul>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import Badge from '@/components/ui/Badge.vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import timeTrackingService from '@/services/time-tracking.service'

const portal = reactive({ jobs: [], history: [], totals: {}, active_entry: null })
const selectedJobId = ref('')
const saving = ref(false)
const locationError = ref('')
const portalError = ref('')

function formatTime(value) {
  if (!value) return '—'
  const date = new Date(value)
  return date.toLocaleString()
}

function statusVariant(value) {
  if (value === 'pending') return 'warning'
  if (value === 'rejected') return 'danger'
  return 'success'
}

function statusLabel(value) {
  if (!value) return 'Unknown'
  return value.charAt(0).toUpperCase() + value.slice(1)
}

async function loadPortal() {
  portalError.value = ''
  try {
    const data = await timeTrackingService.technicianPortal()
    portal.jobs = data.jobs || []
    portal.history = data.history || []
    portal.totals = data.totals || {}
    portal.active_entry = data.active_entry || null
    if (!selectedJobId.value && portal.jobs.length > 0) {
      selectedJobId.value = portal.jobs[0].id
    }
  } catch (error) {
    portalError.value = error.response?.data?.message || 'Unable to load your time data right now. Please try again.'
  }
}

async function captureLocation() {
  locationError.value = ''

  if (!navigator.geolocation) {
    locationError.value = 'Geolocation is not supported in this browser.'
    return null
  }

  return new Promise((resolve) => {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        resolve({
          lat: position.coords.latitude,
          lng: position.coords.longitude,
          accuracy: position.coords.accuracy,
          altitude: position.coords.altitude,
          speed: position.coords.speed,
          heading: position.coords.heading,
          recorded_at: new Date(position.timestamp).toISOString(),
          source: 'browser_geolocation',
        })
      },
      (error) => {
        locationError.value = error.message || 'Unable to capture location.'
        resolve(null)
      },
      { enableHighAccuracy: true, timeout: 10000 }
    )
  })
}

async function startTimer() {
  locationError.value = ''
  saving.value = true
  try {
    let location = null
    const selectedJob = portal.jobs.find((job) => String(job.id) === String(selectedJobId.value))
    if (selectedJob?.is_mobile) {
      location = await captureLocation()
      if (!location) return
    }

    await timeTrackingService.start({ estimate_job_id: selectedJobId.value ? Number(selectedJobId.value) : null, location })
    locationError.value = ''
    await loadPortal()
  } catch (error) {
    locationError.value = error.response?.data?.message || 'Unable to start the timer.'
  } finally {
    saving.value = false
  }
}

async function stopTimer() {
  if (!portal.active_entry) return
  locationError.value = ''
  saving.value = true
  try {
    let location = null
    if (portal.active_entry?.is_mobile) {
      location = await captureLocation()
      if (!location) return
    }

    const payload = location ? { location } : {}
    await timeTrackingService.stop(portal.active_entry.id, payload)
    locationError.value = ''
    await loadPortal()
  } catch (error) {
    locationError.value = error.response?.data?.message || 'Unable to stop the timer.'
  } finally {
    saving.value = false
  }
}

loadPortal()
</script>
