// old-views/settings/ServiceTypes.vue
<template>
  <div>
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Service Types</h1>
        <p class="mt-1 text-sm text-gray-500">Manage service categories used across bundles and estimates.</p>
      </div>
      <Button @click="startCreate">
        <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        New Service Type
      </Button>
    </div>

    <Alert v-if="errorMessage" variant="danger" class="mb-4">{{ errorMessage }}</Alert>

    <Card>
      <div class="flex flex-col gap-4">
        <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
          <div>
            <label class="block text-sm font-medium text-gray-700">Search</label>
            <Input
              v-model="search"
              class="mt-1"
              placeholder="Search service types"
              @input="handleSearch"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Status</label>
            <select
              v-model="statusFilter"
              class="mt-1 w-full rounded border-gray-300"
              @change="loadServiceTypes"
            >
              <option value="all">All</option>
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
            </select>
          </div>
        </div>

        <div class="relative">
          <Table :columns="columns" :data="serviceTypes" :loading="loading">
            <template #cell(name)="{ row }">
              <div class="flex items-start gap-3">
                <span
                  v-if="row.color"
                  class="mt-1 h-3 w-3 rounded-full border border-gray-200"
                  :style="{ backgroundColor: row.color }"
                ></span>
                <div>
                  <div class="font-semibold text-gray-900">{{ row.name }}</div>
                  <div v-if="row.description" class="text-xs text-gray-500">
                    {{ row.description }}
                  </div>
                </div>
              </div>
            </template>
            <template #cell(alias)="{ value }">
              <span class="text-sm text-gray-600">{{ value || '—' }}</span>
            </template>
            <template #cell(color)="{ value }">
              <span class="text-sm text-gray-600">{{ value || '—' }}</span>
            </template>
            <template #cell(active)="{ value }">
              <Badge :variant="value ? 'success' : 'secondary'" rounded>
                {{ value ? 'Active' : 'Inactive' }}
              </Badge>
            </template>
            <template #actions="{ row }">
              <div class="flex flex-wrap justify-end gap-2">
                <Button size="sm" variant="secondary" @click="startEdit(row)">Edit</Button>
                <Button
                  size="sm"
                  variant="secondary"
                  :loading="togglingId === row.id"
                  @click="toggleActive(row)"
                >
                  {{ row.active ? 'Deactivate' : 'Activate' }}
                </Button>
                <Button
                  size="sm"
                  variant="danger"
                  :loading="deletingId === row.id"
                  @click="deleteServiceType(row)"
                >
                  Delete
                </Button>
              </div>
            </template>
            <template #empty>
              <p class="text-sm text-gray-500">No service types found.</p>
            </template>
          </Table>
        </div>
      </div>
    </Card>

    <Modal v-model="showModal" :title="modalTitle" size="lg" @close="closeModal">
      <div class="space-y-4">
        <Alert v-if="formError" variant="danger">{{ formError }}</Alert>
        <div class="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div>
            <label class="block text-sm font-medium text-gray-700">Name</label>
            <Input v-model="form.name" class="mt-1" placeholder="General Service" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Alias</label>
            <Input v-model="form.alias" class="mt-1" placeholder="general" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Color</label>
            <Input v-model="form.color" class="mt-1" placeholder="#1D4ED8" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Icon</label>
            <Input v-model="form.icon" class="mt-1" placeholder="wrench" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700">Display Order</label>
            <Input v-model.number="form.display_order" class="mt-1" type="number" min="0" />
          </div>
          <div class="flex items-center gap-2 pt-7">
            <input
              id="service-type-active"
              v-model="form.active"
              type="checkbox"
              class="h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
            />
            <label for="service-type-active" class="text-sm text-gray-700">Active</label>
          </div>
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700">Description</label>
          <Textarea v-model="form.description" class="mt-1" rows="3" placeholder="Optional description" />
        </div>
      </div>

      <template #footer>
        <div class="flex justify-end gap-3">
          <Button variant="secondary" @click="closeModal">Cancel</Button>
          <Button :loading="saving" @click="saveServiceType">
            {{ editingItem ? 'Save Changes' : 'Create Service Type' }}
          </Button>
        </div>
      </template>
    </Modal>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import Alert from '@/components/ui/Alert.vue'
import Badge from '@/components/ui/Badge.vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import Input from '@/components/ui/Input.vue'
import Modal from '@/components/ui/Modal.vue'
import Table from '@/components/ui/Table.vue'
import Textarea from '@/components/ui/Textarea.vue'
import api from '@/services/api'
import { useToast } from '@/stores/toast'

const toast = useToast()
const serviceTypes = ref([])
const loading = ref(false)
const saving = ref(false)
const deletingId = ref(null)
const togglingId = ref(null)
const showModal = ref(false)
const editingItem = ref(null)
const search = ref('')
const statusFilter = ref('all')
const errorMessage = ref('')
const formError = ref('')
const searchTimeout = ref(null)

const form = reactive({
  name: '',
  alias: '',
  color: '',
  icon: '',
  description: '',
  active: true,
  display_order: 0,
})

const columns = [
  { key: 'name', label: 'Name' },
  { key: 'alias', label: 'Alias' },
  { key: 'color', label: 'Color' },
  { key: 'display_order', label: 'Order' },
  { key: 'active', label: 'Status' },
]

const modalTitle = computed(() => (editingItem.value ? 'Edit Service Type' : 'New Service Type'))

const resetForm = () => {
  form.name = ''
  form.alias = ''
  form.color = ''
  form.icon = ''
  form.description = ''
  form.active = true
  form.display_order = 0
}

const loadServiceTypes = async () => {
  loading.value = true
  errorMessage.value = ''
  try {
    const params = {}
    if (search.value.trim()) {
      params.query = search.value.trim()
    }
    if (statusFilter.value === 'active') {
      params.active = 1
    }
    if (statusFilter.value === 'inactive') {
      params.active = 0
    }
    const response = await api.get('/service-types', { params })
    serviceTypes.value = response.data || []
  } catch (err) {
    console.error(err)
    errorMessage.value = 'Unable to load service types.'
    serviceTypes.value = []
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  if (searchTimeout.value) {
    clearTimeout(searchTimeout.value)
  }
  searchTimeout.value = setTimeout(() => {
    loadServiceTypes()
  }, 300)
}

const startCreate = () => {
  editingItem.value = null
  resetForm()
  formError.value = ''
  showModal.value = true
}

const startEdit = (item) => {
  editingItem.value = item
  form.name = item.name || ''
  form.alias = item.alias || ''
  form.color = item.color || ''
  form.icon = item.icon || ''
  form.description = item.description || ''
  form.active = Boolean(item.active)
  form.display_order = item.display_order ?? 0
  formError.value = ''
  showModal.value = true
}

const closeModal = () => {
  showModal.value = false
  editingItem.value = null
  resetForm()
  formError.value = ''
}

const saveServiceType = async () => {
  saving.value = true
  formError.value = ''
  try {
    const payload = {
      name: form.name,
      alias: form.alias || null,
      color: form.color || null,
      icon: form.icon || null,
      description: form.description || null,
      active: form.active,
      display_order: Number(form.display_order) || 0,
    }

    if (editingItem.value) {
      await api.put(`/service-types/${editingItem.value.id}`, payload)
      toast.success('Service type updated')
    } else {
      await api.post('/service-types', payload)
      toast.success('Service type created')
    }

    closeModal()
    await loadServiceTypes()
  } catch (err) {
    console.error(err)
    formError.value = err.response?.data?.message || 'Unable to save service type.'
  } finally {
    saving.value = false
  }
}

const toggleActive = async (item) => {
  const nextActive = !item.active
  const actionLabel = nextActive ? 'activate' : 'deactivate'
  if (!confirm(`Are you sure you want to ${actionLabel} ${item.name}?`)) return

  togglingId.value = item.id
  try {
    await api.put(`/service-types/${item.id}`, { active: nextActive })
    toast.success(`Service type ${nextActive ? 'activated' : 'deactivated'}`)
    await loadServiceTypes()
  } catch (err) {
    console.error(err)
    toast.error('Unable to update service type status')
  } finally {
    togglingId.value = null
  }
}

const deleteServiceType = async (item) => {
  if (!confirm(`Delete ${item.name}? This cannot be undone.`)) return

  deletingId.value = item.id
  try {
    await api.delete(`/service-types/${item.id}`)
    toast.success('Service type deleted')
    await loadServiceTypes()
  } catch (err) {
    console.error(err)
    toast.error('Unable to delete service type')
  } finally {
    deletingId.value = null
  }
}

onMounted(() => {
  loadServiceTypes()
})
</script>

// src/react/views/settings/ServiceTypes.jsx
import { useCallback, useEffect, useMemo, useState } from 'react'

import Alert from '../../components/ui/Alert'
import Button from '../../components/ui/Button'
import Card from '../../components/ui/Card'
import ColorPicker from '../../components/ui/ColorPicker'
import IconPicker from '../../components/ui/IconPicker'
import Input from '../../components/ui/Input'
import Modal from '../../components/ui/Modal'
import Table from '../../components/ui/Table'
import Textarea from '../../components/ui/Textarea'
import {
  createServiceType,
  deleteServiceType,
  fetchServiceTypes,
  updateServiceType,
} from '../../../services/service-types.service'
import * as OutlineIcons from '@heroicons/react/24/outline'

const initialFormState = {
  name: '',
  alias: '',
  color: '',
  icon: '',
  description: '',
  displayOrder: 0,
  active: true,
}

const generateAlias = (name) => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, '_')
    .replace(/^_+|_+$/g, '')
}

export default function ServiceTypes() {
  const [form, setForm] = useState(initialFormState)
  const [serviceTypes, setServiceTypes] = useState([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [editingId, setEditingId] = useState(null)
  const [aliasManuallyEdited, setAliasManuallyEdited] = useState(false)
  const [deleteConfirmId, setDeleteConfirmId] = useState(null)

  const loadServiceTypes = useCallback(async () => {
    setLoading(true)
    setError('')

    try {
      const data = await fetchServiceTypes()
      setServiceTypes(Array.isArray(data) ? data : [])
    } catch (fetchError) {
      setError(fetchError?.message || 'Unable to load service types.')
      setServiceTypes([])
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    loadServiceTypes()
  }, [loadServiceTypes])

  const updateField = (key, value) => {
    setForm((prev) => {
      const updated = { ...prev, [key]: value }

      if (key === 'name' && !aliasManuallyEdited) {
        updated.alias = generateAlias(value)
      }

      return updated
    })
  }

  const handleAliasChange = (value) => {
    setAliasManuallyEdited(true)
    setForm((prev) => ({ ...prev, alias: value }))
  }

  const resetForm = () => {
    setForm(initialFormState)
    setEditingId(null)
    setAliasManuallyEdited(false)
  }

  const openCreateModal = () => {
    resetForm()
    setShowModal(true)
  }

  const openEditModal = (serviceType) => {
    setEditingId(serviceType.id)
    setForm({
      name: serviceType.name || '',
      alias: serviceType.alias || '',
      color: serviceType.color || '',
      icon: serviceType.icon || '',
      description: serviceType.description || '',
      displayOrder: serviceType.display_order ?? 0,
      active: serviceType.active ?? true,
    })
    setAliasManuallyEdited(true)
    setShowModal(true)
  }

  const closeModal = () => {
    setShowModal(false)
    resetForm()
  }

  const handleSubmit = async (event) => {
    event?.preventDefault()
    setSaving(true)
    setMessage('')
    setError('')

    const payload = {
      name: form.name,
      alias: form.alias,
      color: form.color,
      icon: form.icon,
      description: form.description,
      display_order: Number(form.displayOrder) || 0,
      active: form.active,
    }

    try {
      if (editingId) {
        await updateServiceType(editingId, payload)
        setMessage('Service type updated successfully.')
      } else {
        await createServiceType(payload)
        setMessage('Service type created successfully.')
      }
      closeModal()
      await loadServiceTypes()
    } catch (submitError) {
      setError(submitError?.response?.data?.message || submitError?.message || 'Failed to save service type.')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async (id) => {
    setDeleting(true)
    setError('')

    try {
      await deleteServiceType(id)
      setMessage('Service type deleted successfully.')
      setDeleteConfirmId(null)
      await loadServiceTypes()
    } catch (deleteError) {
      setError(deleteError?.response?.data?.message || deleteError?.message || 'Failed to delete service type.')
    } finally {
      setDeleting(false)
    }
  }

  const columns = useMemo(() => ([
    { key: 'name', label: 'Name' },
    { key: 'alias', label: 'Alias' },
    { key: 'color', label: 'Color' },
    { key: 'icon', label: 'Icon' },
    { key: 'active', label: 'Active' },
    { key: 'display_order', label: 'Order' },
    { key: 'actions', label: '' },
  ]), [])

  const cellRenderers = useMemo(() => ({
    active: (value) => (value ? 'Yes' : 'No'),
    color: (value) => value ? (
      <div className="flex items-center gap-2">
        <span
          className="inline-block w-5 h-5 rounded border border-gray-300"
          style={{ backgroundColor: value }}
        />
        <span className="text-sm text-gray-600">{value}</span>
      </div>
    ) : '-',
    icon: (value) => {
      if (!value) return '-'
      const IconComponent = OutlineIcons[value]
      return IconComponent ? (
        <div className="flex items-center gap-2">
          <IconComponent className="h-5 w-5 text-gray-600" />
          <span className="text-sm text-gray-600">{value.replace(/Icon$/, '')}</span>
        </div>
      ) : (
        <span className="text-sm text-gray-600">{value}</span>
      )
    },
    actions: (_, row) => (
      <div className="flex items-center justify-end gap-2">
        <Button variant="outline" size="sm" onClick={() => openEditModal(row)}>
          Edit
        </Button>
        <Button variant="danger" size="sm" onClick={() => setDeleteConfirmId(row.id)}>
          Delete
        </Button>
      </div>
    ),
  }), [])

  return (
    <div>
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Service types</h1>
            <p className="mt-1 text-sm text-gray-500">
              Manage the categories used for estimates, bundles, and public request forms.
            </p>
          </div>
          <Button onClick={openCreateModal}>Add Service Type</Button>
        </div>
      </div>

      {message ? <Alert variant="success" className="mb-4">{message}</Alert> : null}
      {error ? <Alert variant="danger" className="mb-4">{error}</Alert> : null}

      <Card>
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Existing service types</h2>
        <Table
          columns={columns}
          data={serviceTypes}
          loading={loading}
          hoverable
          cellRenderers={cellRenderers}
          renderEmpty="No service types have been created yet."
        />
      </Card>

      <Modal
        open={showModal}
        title={editingId ? 'Edit Service Type' : 'Add Service Type'}
        size="lg"
        onClose={closeModal}
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Name <span className="text-red-500">*</span>
              </label>
              <Input
                value={form.name}
                placeholder="Steering & Suspension"
                className="mt-1"
                required
                onChange={(event) => updateField('name', event.target.value)}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Alias <span className="text-red-500">*</span>
              </label>
              <Input
                value={form.alias}
                placeholder="steering_suspension"
                className="mt-1"
                required
                onChange={(event) => handleAliasChange(event.target.value)}
              />
              <p className="mt-1 text-xs text-gray-500">
                Auto-generated from name. Use lowercase letters, numbers, and underscores.
              </p>
            </div>
            <ColorPicker
              label="Color"
              value={form.color}
              onChange={(value) => updateField('color', value)}
            />
            <IconPicker
              label="Icon"
              value={form.icon}
              onChange={(value) => updateField('icon', value)}
            />
            <div>
              <label className="block text-sm font-medium text-gray-700">Display order</label>
              <Input
                type="number"
                min="0"
                value={form.displayOrder}
                className="mt-1"
                onChange={(event) => updateField('displayOrder', event.target.value)}
              />
            </div>
            <div className="flex items-center space-x-2 pt-6">
              <input
                id="service-type-active"
                type="checkbox"
                checked={form.active}
                className="h-4 w-4 text-indigo-600 border-gray-300 rounded"
                onChange={(event) => updateField('active', event.target.checked)}
              />
              <label htmlFor="service-type-active" className="text-sm font-medium text-gray-700">
                Active
              </label>
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Description</label>
            <Textarea
              value={form.description}
              rows={3}
              placeholder="Describe what this service type covers."
              className="mt-1"
              onChange={(event) => updateField('description', event.target.value)}
            />
          </div>
          <div className="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onClick={closeModal}>
              Cancel
            </Button>
            <Button type="submit" loading={saving}>
              {editingId ? 'Update' : 'Create'} Service Type
            </Button>
          </div>
        </form>
      </Modal>

      <Modal
        open={!!deleteConfirmId}
        title="Delete Service Type"
        size="sm"
        onClose={() => setDeleteConfirmId(null)}
      >
        <p className="text-gray-600">
          Are you sure you want to delete this service type? This action cannot be undone.
        </p>
        <div className="flex justify-end gap-2 mt-6">
          <Button variant="outline" onClick={() => setDeleteConfirmId(null)}>
            Cancel
          </Button>
          <Button
            variant="danger"
            loading={deleting}
            onClick={() => handleDelete(deleteConfirmId)}
          >
            Delete
          </Button>
        </div>
      </Modal>
    </div>
  )
}
