// src/react/views/auth/Login.jsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'

import { securityService } from '../../../services/security.service'
import { useAuthStore } from '../../stores/auth.jsx'

const RECAPTCHA_SCRIPT_ID = 'recaptcha-v3-script'

export default function Login() {
  const { login, verifyTwoFactor, loading, error, pendingChallenge } = useAuthStore()
  const location = useLocation()
  const [form, setForm] = useState({
    email: '',
    password: '',
    remember: false,
  })
  const [code, setCode] = useState('')
  const [errorMessage, setErrorMessage] = useState(null)
  const [sessionExpiredMessage, setSessionExpiredMessage] = useState(null)
  const [recaptchaEnabled, setRecaptchaEnabled] = useState(false)
  const [recaptchaSiteKey, setRecaptchaSiteKey] = useState('')
  const [recaptchaReady, setRecaptchaReady] = useState(false)
  const [recaptchaLoading, setRecaptchaLoading] = useState(false)
  const [recaptchaLoadError, setRecaptchaLoadError] = useState(null)

  const isVerifying = useMemo(() => !!pendingChallenge, [pendingChallenge])

  const loadRecaptcha = useCallback(async () => {
    if (typeof window === 'undefined' || !recaptchaSiteKey) {
      return null
    }

    if (window.grecaptcha?.execute) {
      return window.grecaptcha
    }

    const existingScript = document.getElementById(RECAPTCHA_SCRIPT_ID)

    const scriptPromise = new Promise((resolve, reject) => {
      const handleLoad = () => resolve(window.grecaptcha)

      if (existingScript) {
        if (window.grecaptcha) {
          resolve(window.grecaptcha)
        } else {
          existingScript.addEventListener('load', handleLoad, { once: true })
        }
        return
      }

      const script = document.createElement('script')
      script.id = RECAPTCHA_SCRIPT_ID
      script.src = `https://www.google.com/recaptcha/api.js?render=${recaptchaSiteKey}`
      script.async = true
      script.defer = true
      script.onload = handleLoad
      script.onerror = reject
      document.head.appendChild(script)
    })

    return scriptPromise
  }, [recaptchaSiteKey])

  useEffect(() => {
    const params = new URLSearchParams(location.search)
    if (params.get('expired') === '1' && params.get('message')) {
      setSessionExpiredMessage(params.get('message'))
    }
  }, [location.search])

  useEffect(() => {
    const loadSettings = async () => {
      try {
        const settings = await securityService.getRecaptchaSettings()
        setRecaptchaEnabled(!!settings.enabled)
        setRecaptchaSiteKey(settings.site_key || '')
      } catch (err) {
        setRecaptchaEnabled(false)
        setRecaptchaSiteKey('')
        console.error('Failed to load reCAPTCHA settings', err)
      }
    }

    loadSettings()
  }, [])

  useEffect(() => {
    if (!recaptchaEnabled || !recaptchaSiteKey) {
      setRecaptchaReady(false)
      setRecaptchaLoading(false)
      setRecaptchaLoadError(null)
      return
    }

    let isActive = true
    setRecaptchaLoading(true)
    setRecaptchaLoadError(null)

    loadRecaptcha()
      .then((grecaptcha) => {
        if (!grecaptcha?.ready || !grecaptcha?.execute) {
          throw new Error('reCAPTCHA is not available')
        }

        return new Promise((resolve) => {
          grecaptcha.ready(resolve)
        })
      })
      .then(() => {
        if (!isActive) return
        setRecaptchaReady(true)
      })
      .catch((err) => {
        if (!isActive) return
        setRecaptchaReady(false)
        setRecaptchaLoadError(err)
      })
      .finally(() => {
        if (!isActive) return
        setRecaptchaLoading(false)
      })

    return () => {
      isActive = false
    }
  }, [loadRecaptcha, recaptchaEnabled, recaptchaSiteKey])

  const handleChange = (field) => (event) => {
    const value = field === 'remember' ? event.target.checked : event.target.value
    setForm((prev) => ({ ...prev, [field]: value }))
  }

  const handleLogin = async (event) => {
    event.preventDefault()
    setErrorMessage(null)

    try {
      if (isVerifying) {
        if (!code.trim()) {
          setErrorMessage('Please enter the verification code')
          return
        }

        await verifyTwoFactor(code.trim())
        return
      }

      let token = null

      if (recaptchaEnabled) {
        if (!recaptchaSiteKey) {
          throw new Error('reCAPTCHA is not configured')
        }

        if (!recaptchaReady) {
          throw new Error('reCAPTCHA is still loading. Please wait a moment and try again.')
        }

        const grecaptcha = await loadRecaptcha()

        if (!grecaptcha?.execute) {
          throw new Error('reCAPTCHA is not available')
        }

        token = await grecaptcha.execute(recaptchaSiteKey, { action: 'login' })

        if (!token) {
          throw new Error('Failed to verify reCAPTCHA. Please try again.')
        }
      }

      const result = await login(form.email, form.password, false, token)

      if (result?.status === '2fa_required') {
        return
      }
    } catch (err) {
      setErrorMessage(err.response?.data?.message || err.message || 'Invalid credentials')
    }
  }

  const displayError = errorMessage || error
  const disableSubmit = loading || (!isVerifying && recaptchaEnabled && !recaptchaReady)

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Auto Repair Shop Management
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">Staff Login</p>
        </div>

        <form className="mt-8 space-y-6" onSubmit={handleLogin}>
          {sessionExpiredMessage ? (
            <div className="rounded-md bg-yellow-50 p-4 border border-yellow-200">
              <p className="text-sm text-yellow-800">{sessionExpiredMessage}</p>
            </div>
          ) : null}

          {displayError ? (
            <div className="rounded-md bg-red-50 p-4">
              <p className="text-sm text-red-800">{displayError}</p>
            </div>
          ) : null}

          {!isVerifying ? (
            <div className="rounded-md shadow-sm -space-y-px">
              <div>
                <label htmlFor="email" className="sr-only">
                  Email address
                </label>
                <input
                  id="email"
                  value={form.email}
                  onChange={handleChange('email')}
                  name="email"
                  type="email"
                  autoComplete="email"
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                  placeholder="Email address"
                  disabled={loading}
                />
              </div>
              <div>
                <label htmlFor="password" className="sr-only">
                  Password
                </label>
                <input
                  id="password"
                  value={form.password}
                  onChange={handleChange('password')}
                  name="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                  placeholder="Password"
                  disabled={loading}
                />
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <label htmlFor="code" className="block text-sm font-medium text-gray-700">
                Authentication code
              </label>
              <input
                id="code"
                value={code}
                onChange={(event) => setCode(event.target.value)}
                name="code"
                type="text"
                inputMode="numeric"
                autoComplete="one-time-code"
                required
                className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
                placeholder="Enter 6-digit code"
                disabled={loading}
              />
              <p className="text-xs text-gray-500">
                Open your authenticator app to retrieve the current code.
              </p>
            </div>
          )}

          {!isVerifying ? (
            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <input
                  id="remember-me"
                  checked={form.remember}
                  onChange={handleChange('remember')}
                  name="remember-me"
                  type="checkbox"
                  className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                />
                <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-900">
                  Remember me
                </label>
              </div>

              <div className="text-sm">
                <Link to="/forgot-password" className="font-medium text-primary-600 hover:text-primary-500">
                  Forgot your password?
                </Link>
              </div>
            </div>
          ) : null}

          <div>
            <button
              type="submit"
              disabled={disableSubmit}
              className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span>
                {loading
                  ? 'Logging in...'
                  : !isVerifying && recaptchaEnabled && !recaptchaReady
                    ? 'Loading security check...'
                    : 'Sign in'}
              </span>
            </button>
          </div>

          {!isVerifying && recaptchaEnabled && (recaptchaLoading || recaptchaLoadError) ? (
            <p className="text-xs text-gray-500 text-center">
              {recaptchaLoadError
                ? 'Trouble loading reCAPTCHA. Please wait a moment and try again.'
                : 'Loading reCAPTCHA...'}
            </p>
          ) : null}

          <div className="text-center">
            <Link to="/customer-login" className="text-sm text-primary-600 hover:text-primary-500">
              Customer? Login here
            </Link>
          </div>
        </form>
      </div>
    </div>
  )
}

// src/views/auth/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Auto Repair Shop Management
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Staff Login
        </p>
      </div>

      <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
        <!-- Session expiration warning -->
        <div v-if="sessionExpiredMessage" class="rounded-md bg-yellow-50 p-4 border border-yellow-200">
          <p class="text-sm text-yellow-800">{{ sessionExpiredMessage }}</p>
        </div>

        <!-- Error message -->
        <div v-if="error" class="rounded-md bg-red-50 p-4">
          <p class="text-sm text-red-800">{{ error }}</p>
        </div>

        <div v-if="!isVerifying" class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="email" class="sr-only">Email address</label>
            <input
              id="email"
              v-model="form.email"
              name="email"
              type="email"
              autocomplete="email"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
              placeholder="Email address"
              :disabled="loading"
            />
          </div>
          <div>
            <label for="password" class="sr-only">Password</label>
            <input
              id="password"
              v-model="form.password"
              name="password"
              type="password"
              autocomplete="current-password"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
              placeholder="Password"
              :disabled="loading"
            />
          </div>
        </div>

        <div v-else class="space-y-2">
          <label for="code" class="block text-sm font-medium text-gray-700">Authentication code</label>
          <input
            id="code"
            v-model="code"
            name="code"
            type="text"
            inputmode="numeric"
            autocomplete="one-time-code"
            required
            class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
            placeholder="Enter 6-digit code"
            :disabled="loading"
          />
          <p class="text-xs text-gray-500">Open your authenticator app to retrieve the current code.</p>
        </div>

        <div v-if="!isVerifying" class="flex items-center justify-between">
          <div class="flex items-center">
            <input
              id="remember-me"
              v-model="form.remember"
              name="remember-me"
              type="checkbox"
              class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
            />
            <label for="remember-me" class="ml-2 block text-sm text-gray-900">
              Remember me
            </label>
          </div>

          <div class="text-sm">
            <router-link to="/forgot-password" class="font-medium text-primary-600 hover:text-primary-500">
              Forgot your password?
            </router-link>
          </div>
        </div>

        <div>
          <div class="flex justify-center">
            <div v-if="recaptchaEnabled" ref="recaptchaContainer"></div>
          </div>

          <button
            type="submit"
            :disabled="loading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="loading">Logging in...</span>
            <span v-else>Sign in</span>
          </button>
        </div>

        <div class="text-center">
          <router-link to="/customer-login" class="text-sm text-primary-600 hover:text-primary-500">
            Customer? Login here
          </router-link>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useRoute } from 'vue-router'
import { securityService } from '@/services/security.service'
import { useRecaptcha } from '@/composables/useRecaptcha'

const authStore = useAuthStore()
const route = useRoute()

const form = ref({
  email: '',
  password: '',
  remember: false,
})

const code = ref('')

const loading = ref(false)
const error = ref(null)
const sessionExpiredMessage = ref(null)
const recaptchaEnabled = ref(false)
const recaptchaSiteKey = ref('')
const { recaptchaContainer, recaptchaToken, resetRecaptcha } = useRecaptcha(recaptchaSiteKey)

const isVerifying = computed(() => !!authStore.pendingChallenge)

onMounted(async () => {
  // Check for session expiration message from query params
  if (route.query.expired === '1' && route.query.message) {
    sessionExpiredMessage.value = route.query.message
  }

  try {
    const settings = await securityService.getRecaptchaSettings()
    recaptchaEnabled.value = !!settings.enabled
    recaptchaSiteKey.value = settings.site_key || ''
  } catch (err) {
    recaptchaEnabled.value = false
    recaptchaSiteKey.value = ''
    console.error('Failed to load reCAPTCHA settings', err)
  }
})

async function handleLogin() {
  loading.value = true
  error.value = null

  try {
    if (isVerifying.value) {
      await authStore.verifyTwoFactor(code.value)
      return
    }

    if (recaptchaEnabled.value) {
      if (!recaptchaSiteKey.value) {
        throw new Error('reCAPTCHA is not configured')
      }

      if (!recaptchaToken.value) {
        throw new Error('Please complete the reCAPTCHA challenge.')
      }
    }

    const token = recaptchaEnabled.value ? recaptchaToken.value : null
    const result = await authStore.login(form.value.email, form.value.password, false, token)

    if (result?.status === '2fa_required') {
      return
    }
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Invalid credentials'
  } finally {
    loading.value = false
    resetRecaptcha()
  }
}
</script>
