// src/react/components/ui/Modal.jsx
import { useEffect, useMemo } from 'react'
import { createPortal } from 'react-dom'

export default function Modal({
  modelValue,
  open,
  title = '',
  size = 'md',
  closable = true,
  closeOnBackdrop = true,
  header,
  footer,
  content,
  onClose,
  onUpdateModelValue,
  className = '',
  children,
}) {
  const isOpen = typeof open === 'boolean' ? open : !!modelValue

  const modalSizeClasses = useMemo(() => {
    const sizes = {
      sm: 'sm:max-w-sm w-full',
      md: 'sm:max-w-lg w-full',
      lg: 'sm:max-w-2xl w-full',
      xl: 'sm:max-w-4xl w-full',
      full: 'sm:max-w-7xl w-full',
    }
    return sizes[size] || sizes.md
  }, [size])

  const handleClose = () => {
    onUpdateModelValue?.(false)
    onClose?.()
  }

  useEffect(() => {
    if (!isOpen) {
      document.body.style.overflow = ''
      return
    }

    document.body.style.overflow = 'hidden'

    return () => {
      document.body.style.overflow = ''
    }
  }, [isOpen])

  if (!isOpen) {
    return null
  }

  const headerContent = header ?? (title ? (
    <h3 id="modal-title" className="text-lg font-medium text-gray-900">
      {title}
    </h3>
  ) : null)

  const modalBody = (
    <div
      className="fixed inset-0 z-50 overflow-y-auto"
      aria-labelledby="modal-title"
      role="dialog"
      aria-modal="true"
    >
      <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div
          className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
          aria-hidden="true"
          onClick={() => {
            if (closeOnBackdrop) {
              handleClose()
            }
          }}
        />

        <span className="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">
          &#8203;
        </span>

        <div
          className={`inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle ${modalSizeClasses} ${className}`}
        >
          {headerContent ? (
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                {headerContent}
                {closable ? (
                  <button
                    type="button"
                    onClick={handleClose}
                    className="text-gray-400 hover:text-gray-500 focus:outline-none"
                  >
                    <span className="sr-only">Close</span>
                    <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                ) : null}
              </div>
            </div>
          ) : null}

          <div className="px-6 py-4">{content ?? children}</div>

          {footer ? (
            <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">{footer}</div>
          ) : null}
        </div>
      </div>
    </div>
  )

  return createPortal(modalBody, document.body)
}

// src/components/ui/Modal.vue
<template>
  <teleport to="body">
    <transition
      enter-active-class="transition ease-out duration-300"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition ease-in duration-200"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div
        v-if="modelValue"
        class="fixed inset-0 z-50 overflow-y-auto"
        aria-labelledby="modal-title"
        role="dialog"
        aria-modal="true"
      >
        <!-- Backdrop -->
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
          <div
            class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
            aria-hidden="true"
            @click="closeOnBackdrop && close()"
          ></div>

          <!-- Center modal -->
          <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

          <transition
            enter-active-class="transition ease-out duration-300"
            enter-from-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            enter-to-class="opacity-100 translate-y-0 sm:scale-100"
            leave-active-class="transition ease-in duration-200"
            leave-from-class="opacity-100 translate-y-0 sm:scale-100"
            leave-to-class="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          >
            <div
              v-if="modelValue"
              :class="modalSizeClasses"
              class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle"
            >
              <!-- Header -->
              <div v-if="title || $slots.header" class="px-6 py-4 border-b border-gray-200">
                <div class="flex items-center justify-between">
                  <slot name="header">
                    <h3 id="modal-title" class="text-lg font-medium text-gray-900">
                      {{ title }}
                    </h3>
                  </slot>
                  <button
                    v-if="closable"
                    @click="close"
                    type="button"
                    class="text-gray-400 hover:text-gray-500 focus:outline-none"
                  >
                    <span class="sr-only">Close</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>

              <!-- Body -->
              <div class="px-6 py-4">
                <slot />
              </div>

              <!-- Footer -->
              <div v-if="$slots.footer" class="px-6 py-4 bg-gray-50 border-t border-gray-200">
                <slot name="footer" />
              </div>
            </div>
          </transition>
        </div>
      </div>
    </transition>
  </teleport>
</template>

<script setup>
import { computed, watch } from 'vue'

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  title: {
    type: String,
    default: '',
  },
  size: {
    type: String,
    default: 'md',
    validator: (value) => ['sm', 'md', 'lg', 'xl', 'full'].includes(value),
  },
  closable: {
    type: Boolean,
    default: true,
  },
  closeOnBackdrop: {
    type: Boolean,
    default: true,
  },
})

const emit = defineEmits(['update:modelValue', 'close'])

const modalSizeClasses = computed(() => {
  const sizes = {
    sm: 'sm:max-w-sm w-full',
    md: 'sm:max-w-lg w-full',
    lg: 'sm:max-w-2xl w-full',
    xl: 'sm:max-w-4xl w-full',
    full: 'sm:max-w-7xl w-full',
  }
  return sizes[props.size]
})

function close() {
  emit('update:modelValue', false)
  emit('close')
}

// Prevent body scroll when modal is open
watch(() => props.modelValue, (isOpen) => {
  if (isOpen) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
})
</script>
