// src/react/components/ui/Table.jsx
import { useEffect, useMemo, useRef, useState } from 'react'

import Loading from './Loading'

export default function Table({
  columns = [],
  data = [],
  loading = false,
  selectable = false,
  hoverable = true,
  rowKey = 'id',
  pagination = false,
  perPage = 10,
  total = 0,
  currentPage = 1,
  onRowClick,
  onSort,
  onSelectionChange,
  onPageChange,
  renderEmpty,
  renderActions,
  cellRenderers = {},
}) {
  const [sortKey, setSortKey] = useState('')
  const [sortOrder, setSortOrder] = useState('asc')
  const [selectedRows, setSelectedRows] = useState([])
  const selectAllRef = useRef(null)

  const sort = (key) => {
    const newOrder = sortKey === key ? (sortOrder === 'asc' ? 'desc' : 'asc') : 'asc'
    setSortKey(key)
    setSortOrder(newOrder)
    onSort?.({ key, order: newOrder })
  }

  const getRowKey = (row, index) => row?.[rowKey] ?? index

  const getCellValue = (row, key) => key.split('.').reduce((obj, part) => obj?.[part], row)

  const isSelected = (row) => {
    return selectedRows.some((selected) => getRowKey(selected) === getRowKey(row))
  }

  const allSelected = useMemo(() => {
    return data.length > 0 && selectedRows.length === data.length
  }, [data.length, selectedRows])

  const someSelected = useMemo(() => {
    return selectedRows.length > 0 && selectedRows.length < data.length
  }, [data.length, selectedRows.length])

  const toggleRow = (row) => {
    const key = getRowKey(row)
    setSelectedRows((prev) => {
      const index = prev.findIndex((selected) => getRowKey(selected) === key)
      let next
      if (index > -1) {
        next = prev.filter((selected) => getRowKey(selected) !== key)
      } else {
        next = [...prev, row]
      }
      onSelectionChange?.(next)
      return next
    })
  }

  const toggleAll = () => {
    const next = allSelected ? [] : [...data]
    setSelectedRows(next)
    onSelectionChange?.(next)
  }

  const totalPages = useMemo(() => Math.ceil(total / perPage), [total, perPage])
  const startIndex = useMemo(() => (currentPage - 1) * perPage + 1, [currentPage, perPage])
  const endIndex = useMemo(() => Math.min(currentPage * perPage, total), [currentPage, perPage, total])

  const displayedPages = useMemo(() => {
    const pages = []
    const maxPages = 7

    if (totalPages <= maxPages) {
      for (let i = 1; i <= totalPages; i += 1) pages.push(i)
    } else if (currentPage <= 4) {
      for (let i = 1; i <= 5; i += 1) pages.push(i)
      pages.push('...')
      pages.push(totalPages)
    } else if (currentPage >= totalPages - 3) {
      pages.push(1)
      pages.push('...')
      for (let i = totalPages - 4; i <= totalPages; i += 1) pages.push(i)
    } else {
      pages.push(1)
      pages.push('...')
      for (let i = currentPage - 1; i <= currentPage + 1; i += 1) pages.push(i)
      pages.push('...')
      pages.push(totalPages)
    }

    return pages.filter((page) => page !== '...')
  }, [currentPage, totalPages])

  const goToPage = (page) => {
    if (page !== currentPage) {
      onPageChange?.(page)
    }
  }

  const previousPage = () => {
    if (currentPage > 1) {
      onPageChange?.(currentPage - 1)
    }
  }

  const nextPage = () => {
    if (currentPage < totalPages) {
      onPageChange?.(currentPage + 1)
    }
  }

  const hasActions = typeof renderActions === 'function'

  const columnCount = useMemo(() => {
    let count = columns?.length ?? 0
    if (selectable) count += 1
    if (hasActions) count += 1
    return count
  }, [columns, hasActions, selectable])

  const handleRowClick = (row) => {
    if (hoverable) {
      onRowClick?.(row)
    }
  }

  useEffect(() => {
    setSelectedRows([])
  }, [data])

  useEffect(() => {
    if (selectAllRef.current) {
      selectAllRef.current.indeterminate = someSelected
    }
  }, [someSelected])

  return (
    <div className="flex flex-col">
      <div className="overflow-x-auto">
        <div className="inline-block min-w-full align-middle">
          <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg">
            <table className="min-w-full divide-y divide-gray-300">
              <thead className="bg-gray-50">
                <tr>
                  {selectable ? (
                    <th scope="col" className="relative px-4 py-3.5 sm:w-12 sm:px-6">
                      <input
                        ref={selectAllRef}
                        type="checkbox"
                        checked={allSelected}
                        onChange={toggleAll}
                        className="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-600"
                      />
                    </th>
                  ) : null}

                  {columns.map((column) => (
                    <th
                      key={column.key}
                      scope="col"
                      className={`px-3 py-3.5 text-left text-sm font-semibold text-gray-900 ${column.sortable ? 'cursor-pointer select-none hover:bg-gray-100' : ''}`}
                      onClick={() => column.sortable && sort(column.key)}
                    >
                      <div className="flex items-center gap-2">
                        <span>{column.label}</span>
                        {column.sortable && sortKey === column.key ? (
                          <span className="flex-none">
                            {sortOrder === 'asc' ? (
                              <svg className="h-4 w-4 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                <path
                                  fillRule="evenodd"
                                  d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            ) : (
                              <svg className="h-4 w-4 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                                <path
                                  fillRule="evenodd"
                                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            )}
                          </span>
                        ) : null}
                      </div>
                    </th>
                  ))

                  {hasActions ? (
                    <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span className="sr-only">Actions</span>
                    </th>
                  ) : null}
                </tr>
              </thead>

              <tbody className="divide-y divide-gray-200 bg-white">
                {loading ? (
                  <tr>
                    <td colSpan={columnCount} className="px-3 py-12 text-center">
                      <div className="flex justify-center">
                        <Loading size="lg" />
                      </div>
                    </td>
                  </tr>
                ) : data.length === 0 ? (
                  <tr>
                    <td colSpan={columnCount} className="px-3 py-12 text-center">
                      <div className="text-gray-500">
                        {typeof renderEmpty === 'function'
                          ? renderEmpty()
                          : renderEmpty || <p className="text-sm">No data available</p>}
                      </div>
                    </td>
                  </tr>
                ) : (
                  data.map((row, rowIndex) => (
                    <tr
                      key={getRowKey(row, rowIndex)}
                      className={`${rowIndex % 2 === 0 ? 'bg-white' : 'bg-gray-50'} ${hoverable ? 'hover:bg-gray-100 cursor-pointer' : ''}`}
                      onClick={() => handleRowClick(row)}
                    >
                      {selectable ? (
                        <td className="relative px-4 sm:w-12 sm:px-6">
                          <input
                            type="checkbox"
                            checked={isSelected(row)}
                            onChange={() => toggleRow(row)}
                            onClick={(event) => event.stopPropagation()}
                            className="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-600"
                          />
                        </td>
                      ) : null}

                      {columns.map((column) => {
                        const value = getCellValue(row, column.key)
                        const renderer = cellRenderers?.[column.key]
                        return (
                          <td key={column.key} className="whitespace-nowrap px-3 py-4 text-sm text-gray-900">
                            {renderer ? renderer({ row, value }) : value}
                          </td>
                        )
                      })}

                      {hasActions ? (
                        <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                          {renderActions(row)}
                        </td>
                      ) : null}
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {pagination && !loading ? (
        <div className="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6 mt-4">
          <div className="flex flex-1 justify-between sm:hidden">
            <button
              onClick={previousPage}
              disabled={currentPage === 1}
              className="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Previous
            </button>
            <button
              onClick={nextPage}
              disabled={currentPage === totalPages}
              className="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
          <div className="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
            <div>
              <p className="text-sm text-gray-700">
                Showing <span className="font-medium">{startIndex}</span> to{' '}
                <span className="font-medium">{endIndex}</span> of{' '}
                <span className="font-medium">{total}</span> results
              </p>
            </div>
            <div>
              <nav className="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
                <button
                  onClick={previousPage}
                  disabled={currentPage === 1}
                  className="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <span className="sr-only">Previous</span>
                  <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                </button>

                {displayedPages.map((page) => (
                  <button
                    key={page}
                    onClick={() => goToPage(page)}
                    className={`relative inline-flex items-center px-4 py-2 text-sm font-semibold focus:z-20 ${
                      page === currentPage
                        ? 'z-10 bg-primary-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600'
                        : 'text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0'
                    }`}
                  >
                    {page}
                  </button>
                ))}

                <button
                  onClick={nextPage}
                  disabled={currentPage === totalPages}
                  className="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <span className="sr-only">Next</span>
                  <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                </button>
              </nav>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}

// src/components/ui/Table.vue
<template>
  <div class="flex flex-col">
    <!-- Table Container -->
    <div class="overflow-x-auto">
      <div class="inline-block min-w-full align-middle">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <!-- Header -->
            <thead class="bg-gray-50">
              <tr>
                <!-- Selection checkbox column -->
                <th v-if="selectable" scope="col" class="relative px-4 py-3.5 sm:w-12 sm:px-6">
                  <input
                    type="checkbox"
                    :checked="allSelected"
                    :indeterminate="someSelected"
                    @change="toggleAll"
                    class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-600"
                  />
                </th>

                <!-- Column headers -->
                <th
                  v-for="column in columns"
                  :key="column.key"
                  scope="col"
                  class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                  :class="[column.sortable ? 'cursor-pointer select-none hover:bg-gray-100' : '']"
                  @click="column.sortable && sort(column.key)"
                >
                  <div class="flex items-center gap-2">
                    <span>{{ column.label }}</span>
                    <span v-if="column.sortable && sortKey === column.key" class="flex-none">
                      <svg v-if="sortOrder === 'asc'" class="h-4 w-4 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd" />
                      </svg>
                      <svg v-else class="h-4 w-4 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                      </svg>
                    </span>
                  </div>
                </th>

                <!-- Actions column -->
                <th v-if="$slots.actions" scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Actions</span>
                </th>
              </tr>
            </thead>

            <!-- Body -->
            <tbody class="divide-y divide-gray-200 bg-white">
              <!-- Loading state -->
              <tr v-if="loading">
                <td :colspan="columnCount" class="px-3 py-12 text-center">
                  <div class="flex justify-center">
                    <Loading size="lg" />
                  </div>
                </td>
              </tr>

              <!-- Empty state -->
              <tr v-else-if="data.length === 0">
                <td :colspan="columnCount" class="px-3 py-12 text-center">
                  <div class="text-gray-500">
                    <slot name="empty">
                      <p class="text-sm">No data available</p>
                    </slot>
                  </div>
                </td>
              </tr>

              <!-- Data rows -->
              <tr
                v-else
                v-for="(row, rowIndex) in data"
                :key="getRowKey(row, rowIndex)"
                :class="[
                  rowIndex % 2 === 0 ? 'bg-white' : 'bg-gray-50',
                  hoverable ? 'hover:bg-gray-100 cursor-pointer' : ''
                ]"
                @click="handleRowClick(row)"
              >
                <!-- Selection checkbox -->
                <td v-if="selectable" class="relative px-4 sm:w-12 sm:px-6">
                  <input
                    type="checkbox"
                    :checked="isSelected(row)"
                    @change="toggleRow(row)"
                    @click.stop
                    class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-primary-600 focus:ring-primary-600"
                  />
                </td>

                <!-- Data cells -->
                <td
                  v-for="column in columns"
                  :key="column.key"
                  class="whitespace-nowrap px-3 py-4 text-sm text-gray-900"
                >
                  <slot :name="`cell(${column.key})`" :row="row" :value="getCellValue(row, column.key)">
                    {{ getCellValue(row, column.key) }}
                  </slot>
                </td>

                <!-- Actions -->
                <td v-if="$slots.actions" class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <slot name="actions" :row="row" />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <div v-if="pagination && !loading" class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6 mt-4">
      <div class="flex flex-1 justify-between sm:hidden">
        <button
          @click="previousPage"
          :disabled="currentPage === 1"
          class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Previous
        </button>
        <button
          @click="nextPage"
          :disabled="currentPage === totalPages"
          class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Next
        </button>
      </div>
      <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
        <div>
          <p class="text-sm text-gray-700">
            Showing
            <span class="font-medium">{{ startIndex }}</span>
            to
            <span class="font-medium">{{ endIndex }}</span>
            of
            <span class="font-medium">{{ total }}</span>
            results
          </p>
        </div>
        <div>
          <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
            <button
              @click="previousPage"
              :disabled="currentPage === 1"
              class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Previous</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
              </svg>
            </button>

            <button
              v-for="page in displayedPages"
              :key="page"
              @click="goToPage(page)"
              :class="[
                page === currentPage
                  ? 'z-10 bg-primary-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-600'
                  : 'text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0',
                'relative inline-flex items-center px-4 py-2 text-sm font-semibold focus:z-20'
              ]"
            >
              {{ page }}
            </button>

            <button
              @click="nextPage"
              :disabled="currentPage === totalPages"
              class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <span class="sr-only">Next</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
              </svg>
            </button>
          </nav>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch, useSlots } from 'vue'
import Loading from './Loading.vue'

const props = defineProps({
  columns: {
    type: Array,
    default: () => [],
    // Format: [{ key: 'id', label: 'ID', sortable: true }, ...]
  },
  data: {
    type: Array,
    default: () => [],
  },
  loading: {
    type: Boolean,
    default: false,
  },
  selectable: {
    type: Boolean,
    default: false,
  },
  hoverable: {
    type: Boolean,
    default: true,
  },
  rowKey: {
    type: String,
    default: 'id',
  },
  pagination: {
    type: Boolean,
    default: false,
  },
  perPage: {
    type: Number,
    default: 10,
  },
  total: {
    type: Number,
    default: 0,
  },
  currentPage: {
    type: Number,
    default: 1,
  },
})

const slots = useSlots()

const emit = defineEmits([
  'row-click',
  'sort',
  'selection-change',
  'page-change',
])

// Sorting
const sortKey = ref('')
const sortOrder = ref('asc')

function sort(key) {
  if (sortKey.value === key) {
    sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc'
  } else {
    sortKey.value = key
    sortOrder.value = 'asc'
  }
  emit('sort', { key: sortKey.value, order: sortOrder.value })
}

// Selection
const selectedRows = ref([])

const allSelected = computed(() => {
  return props.data.length > 0 && selectedRows.value.length === props.data.length
})

const someSelected = computed(() => {
  return selectedRows.value.length > 0 && selectedRows.value.length < props.data.length
})

function isSelected(row) {
  return selectedRows.value.some(r => getRowKey(r) === getRowKey(row))
}

function toggleRow(row) {
  const key = getRowKey(row)
  const index = selectedRows.value.findIndex(r => getRowKey(r) === key)

  if (index > -1) {
    selectedRows.value.splice(index, 1)
  } else {
    selectedRows.value.push(row)
  }

  emit('selection-change', selectedRows.value)
}

function toggleAll() {
  if (allSelected.value) {
    selectedRows.value = []
  } else {
    selectedRows.value = [...props.data]
  }
  emit('selection-change', selectedRows.value)
}

// Pagination
const totalPages = computed(() => Math.ceil(props.total / props.perPage))

const startIndex = computed(() => (props.currentPage - 1) * props.perPage + 1)
const endIndex = computed(() => Math.min(props.currentPage * props.perPage, props.total))

const displayedPages = computed(() => {
  const pages = []
  const maxPages = 7

  if (totalPages.value <= maxPages) {
    for (let i = 1; i <= totalPages.value; i++) {
      pages.push(i)
    }
  } else {
    if (props.currentPage <= 4) {
      for (let i = 1; i <= 5; i++) pages.push(i)
      pages.push('...')
      pages.push(totalPages.value)
    } else if (props.currentPage >= totalPages.value - 3) {
      pages.push(1)
      pages.push('...')
      for (let i = totalPages.value - 4; i <= totalPages.value; i++) pages.push(i)
    } else {
      pages.push(1)
      pages.push('...')
      for (let i = props.currentPage - 1; i <= props.currentPage + 1; i++) pages.push(i)
      pages.push('...')
      pages.push(totalPages.value)
    }
  }

  return pages.filter(p => p !== '...')
})

function goToPage(page) {
  if (page !== props.currentPage) {
    emit('page-change', page)
  }
}

function previousPage() {
  if (props.currentPage > 1) {
    emit('page-change', props.currentPage - 1)
  }
}

function nextPage() {
  if (props.currentPage < totalPages.value) {
    emit('page-change', props.currentPage + 1)
  }
}

// Utilities
const columnCount = computed(() => {
  let count = props.columns?.length ?? 0
  if (props.selectable) count++
  if (slots.actions) count++
  return count
})

function getRowKey(row, index) {
  return row[props.rowKey] ?? index
}

function getCellValue(row, key) {
  return key.split('.').reduce((obj, k) => obj?.[k], row)
}

function handleRowClick(row) {
  if (props.hoverable) {
    emit('row-click', row)
  }
}

// Clear selection when data changes
watch(() => props.data, () => {
  selectedRows.value = []
})
</script>
